### ISSUE TITLE
Misleading Title

### ISSUE THREAD

**Issue by rpou0830** [NonFactors/MVC6.Grid#1]
Why are you trying to mislead assigning a Title to this project suggesting that is a solution for MVC6 grid and publishing in September 2015 when a lot of programmer are looking information about MVC6.
After downloading and open the project you see that is not an MVC6 project.
*%#@%*

**Comment by Muchiachio** [comment]
It is MVC6 solution, what are you talking about? Oo

**Comment by rpou0830** [comment]
https://github.com/NonFactors/MVC6.Grid

[image: Inline image 1]

**Comment by Muchiachio** [comment]
Can you show me the files which indicates that this project is not MVC6?
Because I'm sorry, but I still don't get it :disappointed:

**Comment by rpou0830** [comment]
Thanks for your response, I hope I am wrong and I can get your help.
I downloaded the solution from  "https://github.com/NonFactors/MVC6.Grid" 
That solution has two project in .Net Framework 4.0 
Please see the attached image 
![mvc6grid](https://cloud.githubusercontent.com/assets/5871312/10102703/ede31f0c-636d-11e5-98ef-7a0327962106.PNG)

**Comment by Muchiachio** [comment]
Grid.Mvc.Demo and Grid.Mvc.Ajax are definitely not my projects, you can see that from the source. It seems to be [GridMvc](https://gridmvc.codeplex.com/), maybe the download is broken :confused:

**Comment by rpou0830** [comment]
Sorry if was something wrong, here is the link and file list.
Thanks for trying to solve this issue.
[image: Inline image 1]
