### ISSUE TITLE
Problem compiling 0.9.5-rc2-final

### ISSUE THREAD

**Issue by primico** [NonFactors/MVC6.Grid#10]
Hi, a couple months ago I started using your MVC6 grid (version "0.9.0-rc1-final") and it was working great. I notice there is a new version so I updated to "0.9.5-rc2-final" but my project won't build. I am using DNX46, Do you know if there are any dependencies in the new version that aren't supported in DNX46? Thanks!

**Comment by Muchiachio** [comment]
You can't mix `RC1` and `RC2` packages together, so you will have to upgrade every MVC package to `RC2` and use `net46` moniker with dotnet tooling. You can read about it more [here](https://docs.asp.net/en/latest/migration/rc1-to-rc2.html).
