### ISSUE TITLE
Filter popup problem on multiple filterable grids in the same page

### ISSUE THREAD

**Issue by Tizianov86** [NonFactors/MVC6.Grid#103]
Hi,
I have a problem with Filter popup with double grids initizialization in the same page (like http://mvc6-grid.azurewebsites.net/Grid/Multiple with .Filterable()).

If I set two Filterable Grids, I have only one popup available (only on the first grid).

There is a fix for this question?

Thanks in advance.

**Comment by Muchiachio** [comment]
You mean it only works on one grid or it works on both, but it's a single pop up?

**Comment by Tizianov86** [comment]
I apologize, I did not study my contest compared to a neutral case. I will explain:
I have due grids, the first on the normal page, the seconds into a bootstrap modal; when I click on a row of the first grid the modal is shown (in overlaying mode) with the second grid. 
At this point if i click on the filter icons i don't see the popup (which however exists). 
instead if a put two grid in the same page (one beside the other) i don't have the issue and all works fine: i will have always only one popup but that's okay.
 
I do not know if this can be considered an issue; even if bootstrap is very used. 
if you would like to solve this case I will be happy :)

Thanks for the attention

**Comment by Muchiachio** [comment]
I think you just need to increase `z-index` on `.mvc-grid-popup`, bootstrap modal usually has it at 1050 so anything above that should work, if it works I will add it to default grid style sheet.

**Comment by Tizianov86** [comment]
yes, now with a z-index: 1050 I see the popup of the grid in the modal.

Thanks
