### ISSUE TITLE
RenderBody fails with no exception

### ISSUE THREAD

**Issue by kitzler-walli** [NonFactors/MVC6.Grid#104]
I currently try to get this grid to work but somehow the output stops.
When I view the html source it stops right after `<div class="container body-content">`

I'm using ASP.NET MVC Core 2.0 with Visual Studio 2017. (Fresh download of VS today)
The only difference I could find compared to the "Get started docs" is the async Index Function:

> public async Task<IActionResult> Index()
        {
            return View(await _context.SendejournalFailed.ToListAsync());
        }

I already tried to catch every exception there is but the html stream simply stops instead of any exception.

**Comment by kitzler-walli** [comment]
I found the issue after compiling the Grid source myself instead of using the Nuget package - the location of the shared views was wrong in my solution.

**Comment by Muchiachio** [comment]
You are probably missing namespace includes or grid is not registered at start up, it should be visible in the logs tho even if it's not thrown.
