### ISSUE TITLE
Unable to get property 'lang' of undefined or null reference

### ISSUE THREAD

**Issue by pieterverwey** [NonFactors/MVC6.Grid#105]
I am experimenting with using the the grid. Functions as expected except I cannot get the filtering to work.

It fails here. Any thoughts?

![filterissue](https://user-images.githubusercontent.com/35309301/35420496-a3312d5c-01f2-11e8-975b-e9fdeee13671.jpg)

**Comment by Muchiachio** [comment]
Search for `mvcgrid.lang` references, maybe you are clearing it somewhere.
Because it's declared in the [scripts below](https://github.com/NonFactors/MVC6.Grid/blob/v2.2.0/src/Mvc.Grid/Scripts/MvcGrid/mvc-grid.js#L798), so it should be not null.

**Comment by Muchiachio** [comment]
Did you managed to resolve your issue?

**Comment by pieterverwey** [comment]
Yes thanks
