### ISSUE TITLE
Wrong position of the filter window (popup) with the horizontal scroll

### ISSUE THREAD

**Issue by Kitkevich** [NonFactors/MVC6.Grid#106]
Wrong position of the filter window (popup) with the horizontal scroll

If the grid is placed in a window that has a horizontal scroll, 
the filter window (popup) in the last columns is displayed in the wrong position.

Possible fix:

setFilterPosition: function (column, popup) {
            var filter = column.header.find('.mvc-grid-filter');
            var arrow = popup.find('.popup-arrow');
            var filterLeft = filter.offset().left;
            var filterTop = filter.offset().top;
            var filterHeight = filter.height();
            var winWidth = $(window).width();
            **var popupWidth = 200;** 
            var popupTop = filterTop + filterHeight / 2 + 14;
            var popupLeft = filterLeft - 8;
            var arrowLeft = 15;
            **var actualInnerscrollWidth = document.body.scrollWidth;** 
            **if (filterLeft + popupWidth + 5 > actualInnerscrollWidth) {** 
                **popupLeft = actualInnerscrollWidth - popupWidth - 14;** 
                arrowLeft = filterLeft - popupLeft + 7;
            }
            arrow.css('left', arrowLeft + 'px');
            popup.css('left', popupLeft + 'px');
            popup.css('top', popupTop + 'px');
            **popup.css('width', popupWidth + 'px');** 
        },

Please check this.

**Comment by Muchiachio** [comment]
Which version are you using? I recently published `2.3.0` which fixed some of the positioning issues.
So maybe it was fixed, or did I introduce regressions?

**Comment by Kitkevich** [comment]
Version 2.3.0 installed

**Comment by Muchiachio** [comment]
How does it look? I still can't reproduce, this is what I get on `2.3.0`
![image](https://user-images.githubusercontent.com/6647444/35576121-ea246da8-05e6-11e8-866a-d2fe0b4fcb86.png)
and on `2.2.0`
![image](https://user-images.githubusercontent.com/6647444/35576198-176c3bba-05e7-11e8-820b-b2def2056627.png)

**Comment by Kitkevich** [comment]
[image: Встроенное изображение 1]

2018-01-30 18:59 GMT+03:00 Muchiachio <notifications@github.com>:

**Comment by Muchiachio** [comment]
Sorry, but your image doesn't load.

**Comment by Kitkevich** [comment]
![test1](https://user-images.githubusercontent.com/13627871/35576676-a27b0070-05f0-11e8-80ad-cfef61b2aaeb.png)

In this case "Text Stufe 1" column selected

**Comment by Kitkevich** [comment]
I have many columns and document.body.scrollWidth= 2868 but winWidth si only 1280

**Comment by Muchiachio** [comment]
Are you really using `2.3.0` scripts (they have to be copied over manually)?
Because `winWidth` was removed in `2.3.0`, so it shouldn't be in your code.

**Comment by Kitkevich** [comment]
Oh, updated using NuGet package manager

**Comment by Kitkevich** [comment]
Sorry
