### ISSUE TITLE
More exposed filters

### ISSUE THREAD

**Issue by maks232** [NonFactors/MVC6.Grid#107]
It would be nice to have a more significant feedback for the filter function. Maybe some kind of labels or the possibility to show the filter function in a second row under the titles.

**Comment by Muchiachio** [comment]
It now goes from
![image](https://user-images.githubusercontent.com/6647444/35738804-99d955bc-0838-11e8-9803-4a1ebfd0b430.png)
to
![image](https://user-images.githubusercontent.com/6647444/35738563-e40def7c-0837-11e8-9242-fed3e9f48429.png)
and it can be restyled using css, row filter is planned for next major release.

**Comment by maks232** [comment]
great, nice to hear about row filters 👍
