### ISSUE TITLE
Simple Demo does not render

### ISSUE THREAD

**Issue by bblair2018** [NonFactors/MVC6.Grid#108]
I am trying to do this in ASP.NET Core and followed your installation instructions completely. I have double and tripple checked. But, the grid does not render at all... It won't even do this below. I am no sure what I am doing wrong, I can send you the code if that would help.

            @(Html
            .Grid(Model)
            .Build(columns =>
            {
                columns.Add(model => model.Name).Titled("Name");
                columns.Add(model => model.Email).Titled("Email");
                columns.Add(model => model.Subject).Titled("Subject");
                columns.Add(model => model.Message).Titled("Message");
                columns.Add(model => model.TimeStampSent).Titled("TimeStampSent");
            })
            .Filterable()
            .Sortable()
            .Pageable()
            )

**Comment by Muchiachio** [comment]
Yes, create repro on github and I can take a look.

**Comment by bblair2018** [comment]
Do mean by creating a "repro" to create a project on github for this? Do you have a sample project for this?

**Comment by Muchiachio** [comment]
[Examples site](https://github.com/NonFactors/MVC6.Grid.Web) can be used as an example project, if you want to check for differences in your code.

**Comment by bblair2018** [comment]
This is too much for me to go through. I will upload my simple code to a repository for you to take a look at it. I will post again once it is ready. Thanks in advance for your help.

**Comment by bblair2018** [comment]
I have created repository: https://github.com/bblair2018/Assistance.Requested.NonFactors.MVC6.Grid
This is a project where I try many new things out. Your grid controller is under "NonFactorsMVCGridController" However, the file name for that controller is "MVCGridController" I forgot to change the name of the file. The view is called "NonFactorsMVCGrid", of course. 

Thanks for taking a look and please let me know what changes I need to make! I really appreciate it and looking forward to getting this to work!

**Comment by Muchiachio** [comment]
Move `MvcGrid` views to shared folder, otherwise they can't be found.
I will fix installation example as it's only written to move to shared folder, but visual example is not updated.

**Comment by bblair2018** [comment]
I made the update, but it is still blank. Also checked in the changes. In the index file for "NonFactorsMVCGrid" has the script files at the top, otherwise they will not be read after the "@Html" code.

**Comment by bblair2018** [comment]
I also checked in the above changes, so you can see them if desired.

**Comment by Muchiachio** [comment]
You moved your view to shared folder, you have to move three grid partials to the shared folder instead.

**Comment by bblair2018** [comment]
I have the shared views in the in the shared folder and the index.cshyml in the NonFactorsMVCGrid folder. I have also removed all the controllers and views not related to this project. However, this is still not working. Changes to the project have been checked in.

**Comment by bblair2018** [comment]
I just noticed that I have Nonfactors.Grid.MVC6 installed from nuget and not Nonfactors.Grid.**Core**.MVC6. Perhaps I need to uninstall the non core and use the core? However, in "C:\Users\bblair\.nuget\packages" both core and non-core versions are there.

**Comment by bblair2018** [comment]
Put in the core version, checked it in. Still is not working for me.

**Comment by Muchiachio** [comment]
I will make a pull request with a fix, so you can check that out.
And grid installs the core as a dependency so it's not shown in project files.

**Comment by bblair2018** [comment]
Thank you, looking forward to it.

**Comment by bblair2018** [comment]
I got your pull request and now merged it! I see the changes that you did, thanks for the help, it was much appreciated!
