### ISSUE TITLE
UI Question

### ISSUE THREAD

**Issue by bblair2018** [NonFactors/MVC6.Grid#109]
So, it looks like I have to create my own search algorithms for my datatype for search to be integrated in the grid, according to your example site. It also looks like I need to render by own search box as well.

For page size, I can statically create the page size, but to do this from the UI it looks like a  drop down for the page is not available, and I need to render that. 

Is all this correct?

**Comment by bblair2018** [comment]
What I am ultimately trying to do is to create a grid exactly as you have it here...

http://mvcgrid.net/

**Comment by Muchiachio** [comment]
You can create global search like [this](http://mvc-grid.azurewebsites.net/Grid/GlobalSearch).

**Comment by jathridge** [comment]
Is there a way to do something similar to this, but nonglobally? As in, use the following:

$('.mvc-grid').mvcgrid({
            query: 'search=' + this.value,
            reload: true
        });

But specific which columns to search or filter by?

**Comment by Muchiachio** [comment]
It's not actually global as you are doing the filtering part on your own so you could just exclude columns you don't want to be filtered. On the other hand if you know column names you could theoretically build the query string yourself, for example `query: 'Name-Contains=adam'` and if filtering is enabled on that column grid will filter it for you.

**Comment by jathridge** [comment]
So I could do something like this:

$(".mvc-grid").mvcgrid({
        query: "myName-Contains=" + name,
        reload: true
    });

Do you have any documentation on the query language used?

**Comment by Muchiachio** [comment]
I don't have documentation on query language, because it's implementation detail.
But now it's `<grid name + "-" or empty if no name is provided><column name>-<filter type>=<filter value>`

**Comment by jathridge** [comment]
Excellent, this worked perfectly. Thank you!
