### ISSUE TITLE
@Html.AjaxGrid(Url.Action("NonFactorsSearch"))

### ISSUE THREAD

**Issue by dpedrelli** [NonFactors/MVC6.Grid#11]
Hi,

I am trying to use RC2 with an existing, RC2 project.  I downloaded MVC6.Grid.Web and it works just fine.  However, in my own project, the AjaxGrid HTML helper never seems to call the Url.Action.  I sent a breakpoint in my controller and can confirm that it does not execute.  If I make my own AJAX call to a <div> tag, the grid display fine.  However, clicking on it does not work - I assume because it is not inside of the Html.AjaxGrid call.  I have tried adding the .js, .css, and .mvcgrid() to my specific view and _Layout.cshtml.  I am calling an action NonFactorsSearch.  I have tried specifying the controller name and not specifying.  I adding a @using clause to _ViewImports.cshtml and service.AddMvcGrid to startup.cs.

Is there anything that may cause Html.AjaxGrid to not call the Url.Action?

Thanks,

David

**Comment by Muchiachio** [comment]
Try debugging `mvc-grid.js` scripts to see what's happening.
If that doesn't bring anything, try comparing your project with [MVC6 documentation sources](https://github.com/NonFactors/MVC6.Grid.Web), maybe you will be able to find what's missing, so I can update installation notes based on your situation.
And if everything fails, create a repro project and I will look it up.

**Comment by dpedrelli** [comment]
I reviewed the demo project.  There doesn't seem to be a lot to call.  I created a repository with a test project.  [https://github.com/dpedrelli/NonFactorsGrid-Test](url)  I used the default MVC6 template.  I modified startup.cs, copied the shared views, modified _ViewImports, and copied the .js and .css.  /Home/Index calls @Html.AjaxGrid().  I used your model, repository, and _AjaxGrid view.  If you put a break point in the Home controller, you can see that it isn't hit, and the page is blank.  I added a separate, AJAX call, which is commented out.  If you restore it, AJAX will call the controller, and display the grid.  However, clicking on the grid does nothing.

Thanks.

**Comment by Muchiachio** [comment]
Your home controller return full view for ajax grid, but it should only return partial view as shown [here](http://mvc6-grid.azurewebsites.net/Grid/Ajax?mainParam=mainValue).
Also you need to include css and js in your `_Layout`. Your partial with includes is never called, because there is still nothing that can call that partial.

**Comment by dpedrelli** [comment]
I had tried both return View and return PartialView, but didn't seem to make a difference.  Also, I had, originally, put the .css and .js into _Layout, but it produces a "$ is not defined" error.  So, I moved them to the partial view.  Additionally, I tried putting the .mvcgrid() call into site. js, like you have, but that gives me an error that the "Object doesn't support property or method mvcgird."  So, I moved that to the partial view as well.  I changed all of those things back and updated the repository.  However, the controller is still not hit.  I am not sure what you mean that there is nothing to call the partial.  Is there a line of code that I need to add somewhere?

**Comment by Muchiachio** [comment]
You see your page is now like this
```HTML
<body>
    <!-- Index content rendered by ajax grid call, no css, no js, no partial code -->
    <div class="mvc-grid" data-source-url="/Home/NonFactorsSearch">
    </div>
</body>
```
There is no code in there to start rendering mvc grid, because its in your partial which never gets rendered into a runnable page path. I applied the changes mentioned above and got it working, like this
```HTML
<head>
  <!-- mvc grid styling -->
</head>
<body>
    <!-- Code generated by current ajax grid call -->
    <div class="mvc-grid" data-source-url="/Home/NonFactorsSearch">
    </div>
    <!-- jquery scripts -->
    <!-- bootstrap scripts -->
    <!-- mvc grid scripts -->
    <!-- script for initializing .mvcgrid(), which then calls home controller for a partial view, simple view will not work -->
</body>
```

**Comment by dpedrelli** [comment]
The problem there ended-up being that I forgot to move the scripts from the bottom of _Layout to the top.  So, the mvcgrid() call was being made before the references to jquery.  I got that working.  From there, I got my original app working.

Thanks.
