### ISSUE TITLE
Multi level grid

### ISSUE THREAD

**Issue by kdabakus** [NonFactors/MVC6.Grid#110]
Hi 

How can I use NonFactors grid to display master details data ? I am looking for a solution similar to
http://www.dotnetawesome.com/2014/07/nested-webgrid-with-expand-collapse-in-aspnet-mvc4.html, but working in Core 2 framework.  Can You help me ?

**Comment by Muchiachio** [comment]
It can be done the same way shown in the blog post, but it's a lot of hacking through manipulating dom after table is loaded. The other option would be to implement your own partial for the nesting, like shown [here](http://mvc6-grid.azurewebsites.net/Grid/Partial).
