### ISSUE TITLE
Colspan table header element (th) for action buttons

### ISSUE THREAD

**Issue by neman** [NonFactors/MVC6.Grid#111]
Is it possible for action columns to have one (merged) value.

For example, can I easily name table header for two edit buttons _action_  label without css hacking

![image](https://user-images.githubusercontent.com/350314/36646301-38a37ffc-1a76-11e8-8fbe-3c0623247ec9.png)
![image](https://user-images.githubusercontent.com/350314/36646358-dec39070-1a76-11e8-98bb-ed5093df9a4a.png)

**Comment by Muchiachio** [comment]
Currently it's not possible, unless you make some kind of custom partial.
I usually just remove action header borders with `th.action + th.action` selector and leave it empty.

**Comment by neman** [comment]
Ok, I did the same with borders.
Maybe it could be a good feature to have ActionTitle property for such thing. I used to have it in similar custom grids.

**Comment by Muchiachio** [comment]
How would an action title help? I'm seeing this as a column grouping feature.
It was requested a few times, but I can't think of a solution which would carry it's own complexity weight.

**Comment by neman** [comment]
Ok, you can close this issue.
If I catch some spare time, I could try to create prototype.
