### ISSUE TITLE
Data Attributes to Column

### ISSUE THREAD

**Issue by nbw71791** [NonFactors/MVC6.Grid#112]
I had read in other issues that it was possible to add a data-attribute to an MVC6 grid table, and not possible to add the data attribute to Row's.

Is it possible to add a data-attribute to each column on definition?

Thanks!

**Comment by nbw71791** [comment]
For my specific use case (which is controlling the visibility of columns by using a popover checklist), I ended up just using a class for each column to designate whether the column should be visible or not on loading the table. My original plan was to pass in the state as an attribute for each column but a class works just as well.

Thanks for the prompt response!

**Comment by Muchiachio** [comment]
Yes, if it's only for hiding/showing a column on client side, column class is enough.

**Comment by vbisbest** [comment]
Has this been added yet?  I also need to set data attributes for a popover.  Thanks.

**Comment by Muchiachio** [comment]
It's committed, but not yet released as I still have some breaking changes to merge.
I should be finished with testing in 1-2 weeks and I would still need to update documentation.
