### ISSUE TITLE
Passing a Pre-Built Grid? 

### ISSUE THREAD

**Issue by jpl2nd** [NonFactors/MVC6.Grid#113]
First, thank you for this project. I've used this in a core app, and I loved it. 

I'm facing another project where I will need to have an option for users to hide / un-hide columns. I've seen some discussion on this in the issues; but if I understand correctly, this is not currently a feature. I'm really just trying to be able to hinge adding a column on any given setting. I've setup different views one showing all, and another the default, but I haven't been able to find a way to dynamically build the grid column by column. 

Is it possible to build the grid before passing the model to the view? 

Something like: 

```
Grid<ModelClass> thisGrid = new Grid<ModelClass>(items);
thisGrid.Columns.Add(model => model.id).Titled("Project");
if (tssUser.ShoCustGroup == true)
{
    thisGrid.Columns.Add(model => model.SQuoteNoNavigation.Adcucl).Titled("Group");
}

return View(thisGrid);
```

Or should I be looking into the Javascript API? 

thanks!

Jon

**Comment by Muchiachio** [comment]
Yes, you can pre-build a grid in a controller for example, if you can't have `tssUser` information in the view.
You would just need to create a `HtmlGrid` instance in the view like this:
```C#
@(new HtmlGrid<ModelClass>(Model))
```
I would also recommend you checking out if it's possible to implement using extensions, [here's an example on how we hide columns based on privileges](https://github.com/NonFactors/MVC6.Template/blob/a4e944bfdb085c232eb43477b41b4f4a462f9ac9/src/MvcTemplate.Components/Extensions/MvcGrid/MvcGridExtensions.cs#L21), maybe the same could be applied to your user options.
