### ISSUE TITLE
Javascript a way to go to a specific page?

### ISSUE THREAD

**Issue by dotnetshadow** [NonFactors/MVC6.Grid#115]
Hi there,

I was wondering if there is a way to externally tell the grid to reload to a specific page when using ajax

i.e Currently I'm on Page 7 of the grid and I click a button on my page and I want it to go to Page 2 for example?

**Comment by Muchiachio** [comment]
You can manipulate the query
```JS
var currentQuery = $('.mvc-grid').mvcgrid('instance').query;

$('.mvc-grid').mvcgrid({
    query: '<current query with replaced page value>',
    reload: true
});
```
