### ISSUE TITLE
Dll missing after nuget package installation

### ISSUE THREAD

**Issue by singhswat** [NonFactors/MVC6.Grid#118]
Hya,

I've installed the nuget package but cannot seem to find the dll in my references.
Screen grab for reference... am i missing something?

because of this I'm not able to register the grid on startup.

![dllmissing](https://user-images.githubusercontent.com/8418638/37030520-2482901c-2133-11e8-8062-2765ba709fe3.PNG)

Thanks
S

**Comment by Muchiachio** [comment]
You seem to be using older mvc5 framework on full .NET, in that case you should install `NonFactors.Grid.Mvc5` instead.

**Comment by singhswat** [comment]
Thanks for the super quick response!
