### ISSUE TITLE
Keeping Checkbox Selection When Changing Page

### ISSUE THREAD

**Issue by jathridge** [NonFactors/MVC6.Grid#119]
I am currently setting one column to a check box which can be selected and grabbed later for user selecting to do something with the row selected. Problem I'm encountering is, when the user moves to a new page, the checkbox selection does not persist, because the grid is rendered again, so when they go back to the previous page, the checkbox they selected is no longer selected.

I have some ideas for how to keep it in a client side list, and check whenever the grid renders for selected values, but I didn't know if this was covered already with existing functionality, or if someone has already implemented something like this and has an example.

**Comment by Muchiachio** [comment]
No, its not covered by grid functionality, so you will have to preserve custom state yourself.
I would do something similar, keeping selected check boxes and updating them on `reloadEnded` event.
