### ISSUE TITLE
Grid Sorting on non db Column

### ISSUE THREAD

**Issue by vbisbest** [NonFactors/MVC6.Grid#120]
Is it possible to sort on a column that is a calculated property?  Other grids cannot seem to do it and you get an error: "the specified type member is not supported in LINQ to Entities"

Example property:

```
    public string SaleDateMonthYear
    {
        get
        {
            return SaleDate.ToString("MMMM") + " " + SaleDate.Year;
        }
    }
```
And I want to do:
`columns.Add(item => item.SaleDateMonthYear).Titled(Html.DisplayNameFor(file => file.SaleDateMonthYear).ToString()).Sortable(true);`

Thanks for your help.

**Comment by Muchiachio** [comment]
Yes, this won't work.
Because database providers don't usually implement property to query or date to string conversions.

**Comment by vbisbest** [comment]
Thank you for your response!  No, its not that its a date, it cant sort on calculated string fields either.  It has to be a real DB field.   Now having said that, a great feature would be to specify the sort column.   For instance.columns.Add(item => item.CalculatedField).Titled(Html.DisplayNameFor(file => file.CalculatedField).ToString()).**Sortable(true, "SortColumn");**

Notice the extra param to Sortable, and then you can modify the linq query to use that field instead.  Thoughts?

**Comment by Muchiachio** [comment]
It doesn't have to be real db field, it has to be translatable to db query and custom C# property getter isn't.
As for sorting you can already do that by using `.Add(<real column>).RenderedAs(<anything else>)`

**Comment by nbw71791** [comment]
I am able to successfully add a [NotMapped] field to the MVC6 Grid, however the fields that are not mapped have a huge difference in performance when sorting. Something like 3 seconds to sort on a mapped field vs 50 seconds to sort on a NotMapped field both sorting around 500,000 records.

This is probably due to the current lack of an index for the non-mapped properties right?

**Comment by Muchiachio** [comment]
Yes, it's most likely that, you can check the generated query and see the execution plan.
Sorting is always a problem on big tables with a lot of columns, because they are usually not indexed.

**Comment by Muchiachio** [comment]
Did you sorted our your issues @vbisbest?

**Comment by hercules999** [comment]
> I am able to successfully add a [NotMapped] field to the MVC6 Grid, however the fields that are not mapped have a huge difference in performance when sorting. Something like 3 seconds to sort on a mapped field vs 50 seconds to sort on a NotMapped field both sorting around 500,000 records.
> 
> This is probably due to the current lack of an index for the non-mapped properties right?

hello my friend, how were you able to even get the [NotMapped] field to the MVC6 Grid? When I add a NotMapped Field on an Entity/Model and then add a column to my MVC6Grid with it, even if I turn off filtering/sorting for that column, the other column with mapped fields then error our when filtering or sorting on them.

Could you please tell me how you did it? It would help more than you know

**Comment by Muchiachio** [comment]
I'm not sure if nbw added it, it's the same problem as with normal query entity framework can't sort/filter on computed fields. You can add then, but without filter/sort. To get it work you would need a view model mapped using `.Select(model => new ViewModel { })` syntax.

**Comment by hercules999** [comment]
Awesome, thats most excellent, that actually solved the issue
