### ISSUE TITLE
GET requests for sorting/filter going to root instead of view

### ISSUE THREAD

**Issue by cdurth** [NonFactors/MVC6.Grid#121]
Attempting to use with a .net core 2.0.5 mvc project.

I have the follow code in a view 

```
@model IEnumerable<dotnetcorestarter.Models.Data.Stand_Order_Sheet>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <p>
        <a asp-action="Create">Create New</a>
    </p>

    @(Html
        .Grid(Model)
        .Build(columns =>
        {
            columns.Add(model => model.DateCreated).Titled("Created Date");
            columns.Add(model => model.Kiosk.KioskCD).Titled("Kiosk");

            columns.Add(model => model.Description).Titled("Description");
        })
        .Filterable()
        .Sortable()
        .Pageable()
    )
</body>
</html>

```

This will correctly display and pull the necessary css/js files and load the grid when you navigate to /StandOrderSheet

However, when i click a sortable column or accept a filter, it issues a GET to the root url, i.e. `/?Sort=DateCreated&Order=Asc` instead of `/StandOrderSheet?Sort=DateCreated&Order=Asc`

I currently have initializing all grids in my _Layout, but i have also tried removing that and initializing on that view specifically, and also setting the `sourceUrl` property to no avail.

Anyone know what might be wrong?

**Comment by Muchiachio** [comment]
Strange, it's using `window.location.href = '?' + '...'`, which should take current url.
Could you debug and see if `window.location.href` points to the current page?

**Comment by cdurth** [comment]
window.location.href
"http://localhost:64132/StandOrderSheet"

**Comment by Muchiachio** [comment]
Can you debug [reload method](https://github.com/NonFactors/MVC6.Grid/blob/78c55287f426a4e94eae2d7395928bfcb089affd/src/Mvc.Grid/Scripts/MvcGrid/mvc-grid.js#L196) and see why it changes?

**Comment by cdurth** [comment]
it hits the else block, grid.sourceUrl is ""

inside the else block, the window.location.href is set correctly, but then it is set to ? + query

**Comment by Muchiachio** [comment]
You don't have to pass source url, no source url means it's a normal grid (not ajax one).
What else blocks does is "refresh current page with given query", maybe `window.location.href` doesn't work the same in all browsers, which browser are you using? And maybe you can create a small repro project?

**Comment by cdurth** [comment]
Does not work in Chrome 64.0.3282.186 or Firefox 58.0.2

Works in IE 11 & Edge 41.16299.15.0

Going to start a new project and see if the results are the same.

**Comment by Muchiachio** [comment]
So paging doesn't work correctly [here](http://mvc6-grid.azurewebsites.net/Home) either?
I'm using chrome and it sets the query correctly.

**Comment by cdurth** [comment]
paging and all works fine there. a clean project works fine in all browsers.

strange that our implementation on works in IE and Edge.

Our project is not much more complex and this is the only JS file (aside from requiring jquery for it).

going to see if i can troubleshoot our specific project further

**Comment by Muchiachio** [comment]
Did you find what causes the issue?
