### ISSUE TITLE
grid not working when have areas

### ISSUE THREAD

**Issue by h4m3d66** [NonFactors/MVC6.Grid#122]
When I have Area in my project, grid not rendering and not showing any errors but when I dont have Area in my project its working.

**Comment by Muchiachio** [comment]
Maybe your area didn't include grid namespaces? And errors are not shown by mvc core, but instead are logged using logger factory so you can also check there.

**Comment by h4m3d66** [comment]
this is the logged error:
The tag helper 'div' must not have C# in the element's attribute declaration area

**Comment by Muchiachio** [comment]
Look like one of your tag helpers getting executed on a grid div, which has inline c# code.
It's currently a limitation of razor and is tracked [here](https://github.com/aspnet/Razor/issues/96).

You could change that line to
```
<div id="@Model.Name" class="mvc-grid">
```

And in the mean time I will try to think of a workaround for this problem.
