### ISSUE TITLE
Paging And Sorting Error - Ajax Grid

### ISSUE THREAD

**Issue by robgraham123** [NonFactors/MVC6.Grid#124]
Hi,

Followed your set up instructions for http://mvc6-grid.azurewebsites.net/Grid/Ajax?mainParam=mainValue

Getting a javascript error that is stopping the paging and sorting working.
It is calling back to the IndexGrid Action result but the UI is broken due to JS error.
Grid loads correctly first time.

```JS
mvc-grid.js:223 Uncaught TypeError: Cannot read property 'element' of undefined
    at Object.<anonymous> (mvc-grid.js:223)
    at fire (jquery.js:3182)
    at Object.fireWith [as resolveWith] (jquery.js:3312)
    at done (jquery.js:8754)
    at XMLHttpRequest.<anonymous> (jquery.js:9120)
(anonymous) @ mvc-grid.js:223
fire @ jquery.js:3182
fireWith @ jquery.js:3312
done @ jquery.js:8754
(anonymous) @ jquery.js:9120
XMLHttpRequest.send (async)
send @ jquery.js:9172
ajax @ jquery.js:8653
reload @ mvc-grid.js:200
MvcGrid @ mvc-grid.js:45
(anonymous) @ mvc-grid.js:825
each @ jquery.js:360
each @ jquery.js:137
$.fn.mvcgrid @ mvc-grid.js:813
(anonymous) @ (index):74
fire @ jquery.js:3182
fireWith @ jquery.js:3312
ready @ jquery.js:3531
completed @ jquery.js:3547
```
Any ideas greatly appreciated.

VS2017
MVC .net core 2.0.3

**Comment by Muchiachio** [comment]
Is your `_IndexGrid` partial only rendering grid content?

**Comment by robgraham123** [comment]
Thanks for getting back to me.

I had wrapped the Grid code in a simple <div>.  No id's etc.

It is maybe a little fragile with regard finding the grid again?

Anyway, thanks muchly.

**Comment by robgraham123** [comment]
Above should say div

**Comment by Muchiachio** [comment]
Yes, your `_IndexGrid` partial should only contain a grid, if you want to wrap them, you can do that before using the grid in the main view.
```
<div class="wrapper">
    @Html.AjaxGrid(Url.Action("IndexGrid"))
</div>
```
