### ISSUE TITLE
Using asp.net core Razor Pages, allmost working

### ISSUE THREAD

**Issue by paulvanbladel** [NonFactors/MVC6.Grid#126]
this is a brilliant project. Thanks a lot.
I'm using razor pages. Is this a supported scenario?
I followed the installation guide and needed to adapt slightly.
This is the folder structure

![image](https://user-images.githubusercontent.com/4886272/38089238-02cabc22-335f-11e8-9fdb-c3b0c19a3e90.png)

So, I created also a Views/Shared folder and added the suggested partial views.
This is the result
![image](https://user-images.githubusercontent.com/4886272/38089379-83bd793c-335f-11e8-87d8-c605dde36f95.png)

It looks ok, but filtering and sorting isn't working.
This is how I setup the PageModel.
```
public class IndexModel : PageModel
    {
        private readonly MyContext _context;

        public IndexModel(MyContext context)
        {
            _context = context;
        }

        public IList<Order> Orders { get;set; }
        

        public async Task OnGetAsync()
        {

            Orders = await _context
                .Set<Order>().OrderBy(d => d.Id)
                .ToListAsync();
        }
    }

```
The Page:
```
@page
@Api.Domain;
@model Mvc.Pages_Orders.IndexModel

@{
    ViewData["Title"] = "Index";
}

<h2>Orders</h2>


@(Html
        .Grid(Model.Orders)
        .Build(columns =>
        {
            columns.Add(model => model.Id).Titled("Id");
            columns.Add(model => model.OwnDescription).Titled("Own Description").Sortable(true).Filterable(true);
            columns.Add(model => model.CreationDate).Titled("CreationDate");
            columns.Add(model => model.LastModified).Titled("LastModified");
            columns.Add(model => model.GrossPrice).Titled("GrossPrice");

        })
        .Filterable()
        .Sortable()
        .Pageable()
)

``` 
Thank you for helping me out.
Warm regards
paul.

**Comment by Muchiachio** [comment]
Did you initialize the grid using javascript?

**Comment by paulvanbladel** [comment]
Thanks for your prompt reply.
In _Layout.cshtml I added:

  <script src="~/js/mvc-grid.js"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script>
            $('.mvc-grid').mvcgrid();
        </script>

**Comment by paulvanbladel** [comment]
Ouch Ouch... i was in a  <environment exclude="Development">
My apologies for wasting your time.
Sorry !!!!
