### ISSUE TITLE
Not able to view the different pages on clicking the page number displayed.

### ISSUE THREAD

**Issue by arul-selvan** [NonFactors/MVC6.Grid#127]
My development environment is asp.net core 2.0. Trying pagination for the MVC6 grid. Records are displayed in the grid but i am not able able to switch pages. There are no errors, but there is no response as well.

The view page has the following code.
```
@(Html
    .Grid(Model)
    .Build(columns =>
    {
        columns.Add(model => model.customercode).Titled("Customer");
        columns.Add(model => model.jobstage).Titled("Stage");

        columns.Add(model => model.jobsubid_1).Titled("Journal");
        columns.Add(model => model.jobvolissue).Titled("Vol/Issue");
        columns.Add(model => model.jobid).Titled("MS ID");
    })
    .Pageable(pager =>
    {
        pager.ProcessorType = GridProcessorType.Manual;
        pager.TotalRows = (int)ViewBag.TotalRows;
        pager.RowsPerPage = 20;
    })
)


<script>
    $('.mvc-grid').mvcgrid();
</script>
```

**Comment by Muchiachio** [comment]
Does it happen with just `Pageable()`?

**Comment by arul-selvan** [comment]
When i use .Pageable() only one page is displayed and moreover the page number bar displays the number "1" only.

**Comment by Muchiachio** [comment]
Maybe you don't return more than 20 rows? Does it work with this?
```
.Pageable(pager =>
{
    pager.RowsPerPage = 1;
});
```

**Comment by arul-selvan** [comment]
I return more than 200 rows to be displayed. When pager.RowsPerPage = 1; is used One row is displayed. The page number bar displays 1,2,3,4,5, >, >>. But none of them is Selectable.

**Comment by Muchiachio** [comment]
A small project which shows the problem, so I can run it and see why it doesn't work.
Because [this page](http://mvc6-grid.azurewebsites.net/Grid/Paging) works, so you are probably doing something differently, but I don't see what.

**Comment by arul-selvan** [comment]
Attached the View page and Controller code snapshot.

`View Index Page`
@model IEnumerable<Job>
@using NonFactors.Mvc.Grid;


@{
    ViewData["Title"] = "Incoming";
}


    <link href="~/css/mvc-grid.css" rel="stylesheet" />
    
    <script src="~/js/mvc-grid.js"></script>

<BR>
<div style="margin-left:-100px">
    <h2>@ViewData["Title"]</h2>
</div>

<style>
    .label, .textbox, .dropdownlist, .button {
        margin: 10px;
        width: 150px;
        text-align: left;
        float: left;
        display: inline-block;
    }

    table td {
        border: 1px solid #F58220;
    }
</style>





<BR>

<div style="margin-left:-100px">
    <form asp-controller="JobMonitorController" method="POST">

        @Html.TextBox("DownloadDate", (string)ViewBag.dd)

        <input type="submit" id="btnview" value="View" asp-action="ViewJobDetails" />
        <BR>
        

        @(Html
            .Grid(Model)
            .Build(columns =>
            {
                columns.Add(model => model.customercode).Titled("Customer");
                columns.Add(model => model.jobstage).Titled("Stage");

                columns.Add(model => model.jobsubid_1).Titled("Journal");
                columns.Add(model => model.jobvolissue).Titled("Vol/Issue");
                columns.Add(model => model.jobid).Titled("MS ID");
            })
            .Pageable(pager =>
            {
                pager.RowsPerPage = 1;
            })
         )
        

        <script>
            $('.mvc-grid').mvcgrid();
        </script>

    </form>
</div>
/////////
"Controller Function"

 [HttpGet]
 [HttpPost]
public IActionResult ViewJobDetails(Int32? page, Int32? rows)
        {
            List<Job> model;
            UserDataModel umodel = new UserDataModel();
            model = umodel.ViewJobDetails();
            ViewBag.TotalRows = model.Count;
             
            return View("~/Views/JobMonitor/Index.cshtml", model.AsQueryable());
        }

**Comment by arul-selvan** [comment]
Correction, Its  "@model IEnumerable<Job>"

**Comment by Muchiachio** [comment]
No, you should upload your repro code on github or any other service.

**Comment by arul-selvan** [comment]
Sorry, i am trying for grid replacement for an ongoing project, the project size is huge and its difficult to cut it down.

In short, i am trying to do the following, 
1) Pick the records from database and store it into a List variable.
2) Display the List contents in the MVC6 Grid in the view page.

**Comment by Muchiachio** [comment]
You can create a new project and try doing the same or use current [documentation](https://github.com/NonFactors/MVC6.Grid.Web) code as a base.

**Comment by arul-selvan** [comment]
Having added the Nuget package "Nonfactors.Core.Grid.Mvc6" to my package and then making the changes in View & controller as shown in my previous comment.

Will this be sufficient (or) i should do something more.?

**Comment by Muchiachio** [comment]
How is your repro project going?

**Comment by ChrisKaszuba** [comment]
Just an FYI, I was having the exact same issues as above. Figured it out to be IE 11 as and when testing in IISExpress/IE the paging/filtering/sorting extensions were empty. Works fine in Chrome and Edge.
