### ISSUE TITLE
Blazor

### ISSUE THREAD

**Issue by boukenka** [NonFactors/MVC6.Grid#128]
Hello,

There is that new project: [Blazor](https://github.com/aspnet/Blazor)
Will it make sense to propose a Grid based on that implementation, with the features of MVC6.Grid and with a minimum of Javascript?

**Comment by Muchiachio** [comment]
I don't think it would lower the javascript surface it already has, but I will reconsider making a port or extension of the current grid based on blazor, once it reaches a production ready state.
