### ISSUE TITLE
Remote Operations

### ISSUE THREAD

**Issue by KiarashS** [NonFactors/MVC6.Grid#13]
Dear,

Thanks a lot for MVC Grid.
In the demo, your controller is doing:
```
[HttpGet]
public ActionResult Index()
{
    return View(PeopleRepository.GetPeople());
}
```
This is likely to first fetch `All` of rows from Database, and then paging them! But i want to fetch just `Current` page rows from Database, and not `All` of rows.

Thanks

**Comment by Muchiachio** [comment]
What do you mean by desired data?
You can filter out any data you want, before it goes back to the grid or you can use grid filters for that.

**Comment by KiarashS** [comment]
In the demo, your controller is kike to:

```
[HttpGet]
public ActionResult Index()
{
    return View(PeopleRepository.GetPeople());
}
```

This is likely to first fetch `All` of rows from Database, and then paging them! But i want to fetch just `Current` page rows from Database, and not `All` of rows.

**Comment by Muchiachio** [comment]
Why would you want to page database rows yourself, if grid does that automatically?
You can access request query to check current paging values, if you need them for some reason.

**Comment by KiarashS** [comment]
Yes, grid does that automatically, But in local and not in database! and that has an overhead.

Here is a best practice to fetching only `current` page rows from database. you should not fetching `all` of rows from database and then paging them in local!

**Comment by Muchiachio** [comment]
Grid does not fetch all data from the database, it only fetches as many rows as needed (if used correctly).
You can try that with your own tables which has millions of rows.

Because in the database scenario you return `FetchAll` query, which is then paged and only then enumerated on the database.
