### ISSUE TITLE
Filtering functionality not working

### ISSUE THREAD

**Issue by elliscnck** [NonFactors/MVC6.Grid#130]
I just started to implement this grid. I'm able to get the JavaScript box to appear but when I attempt to execute a filter nothing happens, wondering what I maybe missing within my code to get this functionality? Thank you.

Using 3.0.0 and ASP.net core /Razor pages.

**Comment by Muchiachio** [comment]
Can you share a repro?

**Comment by elliscnck** [comment]
https://github.com/elliscnck/MailMan

**Comment by Muchiachio** [comment]
Hmm, I couldn't run it with preview bits, so I downgraded to 2.0 and it worked as expected.
Try looking at the logger output, maybe it has something interesting.
Maybe it has something to do with https or what not?

**Comment by elliscnck** [comment]
can you send me your working copy...

**Comment by elliscnck** [comment]
Is there an example using Razor Pages.   I've been directed to use them? Thank you.

**Comment by Muchiachio** [comment]
Usage is the same, just different shared partial view location.
I will try to update the installation notes with a razor pages structure in coming days.

**Comment by elliscnck** [comment]
Ok, I downgraded still seeing the same issue.  can you send me your working version to see what I'm missing? Thank you.

**Comment by Muchiachio** [comment]
I think I found the problem, you have included `mvc-grid.js` twice in your page.

**Comment by elliscnck** [comment]
not following only see it once.

**Comment by Muchiachio** [comment]
Here's a project. [MailMan-master.zip](https://github.com/NonFactors/MVC6.Grid/files/1932811/MailMan-master.zip)

**Comment by elliscnck** [comment]
Thx you for the help, finally got it to work under 2.0, still had issues under 2.1.
