### ISSUE TITLE
No Border: columns.Add

### ISSUE THREAD

**Issue by elliscnck** [NonFactors/MVC6.Grid#131]
Is there a way of not showing the column border when using columns.Add(model => model.email).Titled("Email");? Thank you.

**Comment by Muchiachio** [comment]
You can style the grid with css in any way it fits you.

**Comment by elliscnck** [comment]
I able to change the styling but not able to remove the borders

columns.Add(model => model.email).Titled("Email").Css("TESTING");

**Comment by Muchiachio** [comment]
Borders are created by css, so you should be able to remove them.
Maybe you meant some kind of other borders?

**Comment by elliscnck** [comment]
I referring to the Grid/cell borders create with the "columns.Add"  I don't want the border for the table/cell of said column.

**Comment by Muchiachio** [comment]
So css solution didn't work?

**Comment by elliscnck** [comment]
I couldn't get it to work.

**Comment by Muchiachio** [comment]
This should definitely force no borders, not sure which css you tried
```CSS
.mvc-grid th, .mvc-grid td {
    border: none !important;
}
```
