### ISSUE TITLE
column has an extra '-' in its name when doing the sort

### ISSUE THREAD

**Issue by vpoorshab** [NonFactors/MVC6.Grid#132]
There is a issue when the grid is sorted by column that has a name like ColumnName , the issue is when sorting is applied the column name is changed to 'column-name' which will cause error on server side.
(model=>model.ColumnName)

i found the below code in the source 
`private String GetName(Expression<Func<T, TValue>> expression)
        {
            return String.Join("-", Regex.Split(ExpressionHelper.GetExpressionText(expression), "(?<!^)(?=[A-Z])")).ToLower();
                    }`

after changing it to 
`return ExpressionHelper.GetExpressionText(expression).ToLowerInvariant();`

the issue was resolved.
so could you please fix this ?

**Comment by Muchiachio** [comment]
It should be this way, what exactly doesn't work on server side?

**Comment by vpoorshab** [comment]
on server side we receive the column name and we try to create expression based on column name out of the model but that '-' makes it crash so every time we have to replace '-' with '' , 
i still don't understand the "Should" of splitting the column name base of [A-Z] ?
we have a column called BookId so we receive book-id which we have to replace the extra '-'

**Comment by Muchiachio** [comment]
Are you doing filtering by hand on server side? Because grid doesn't use that name to create expressions.
If you are you can just use named columns `columns.Add(model => model.ColumnName).Named("ColumnName");`.

**Comment by vpoorshab** [comment]
Thanks for your comment but this is not what we want.the column name is what exactly in expression so i don't see why it cannot be kept same.(`model=>model.ColumnName` )there is no reason to Name it again.

Thanks for your support.

**Comment by vpoorshab** [comment]
Thank you so much.
