### ISSUE TITLE
Ajax Grid with RazorPages

### ISSUE THREAD

**Issue by rickduarte** [NonFactors/MVC6.Grid#133]
Is it possible to use ajax grid with RazorPage?
Is there an example of how to implement?
I could populate the first page, but the pagination is not working.

**Comment by Muchiachio** [comment]
It should work the same, is the click event bound on the pager? Does a network error occur?
If it doesn't do any thing, then it's probably not initialized by javascript.
If there is a network error it should be enough for you to fix the problem.

**Comment by rickduarte** [comment]
I was able to implement it after reading the documentation again.
[Ajax Grid](http://mvc6-grid.azurewebsites.net/Grid/Ajax)

Thank you!!
