### ISSUE TITLE
Ajax Grid/Razor pages

### ISSUE THREAD

**Issue by elliscnck** [NonFactors/MVC6.Grid#135]
Based on the updated info for Razor pages. What am I missing syntax wise, it runs but doesn't show anything?

http://mvc6-grid.azurewebsites.net/Grid/Ajax
[MailMan (Ajax Grid).zip](https://github.com/NonFactors/MVC6.Grid/files/1938694/MailMan.Ajax.Grid.zip)

**Comment by Muchiachio** [comment]
You need to add
```
@page
@model NotifyIndexModel
```
to `NotifyIndex.cshtml`, also split `IndexGrid` to a normal page with it's own classes and a generated page, because currently it's just a view (it doesn't work if you declare it inside the same class as other page).

**Comment by elliscnck** [comment]
I made the suggested changes.. they "NotifyIndex" link take me to the NotifyIndex page which still shows no grid then quickly redirects back to the default index page.

**Comment by Muchiachio** [comment]
You need to remove the `<!-- Should only include the grid -->` part, because every razor page has to start to a `@page` symbol. I think you should start with less error prone mvc pages before moving to newer concepts like razor pages.

**Comment by elliscnck** [comment]
Thank you that  was the solution, I think I have one finally question regarding "Grid Global Search" based on looking the Ajax Grid it would be basically be implemented in the same manner correct? if so what am I doing wrong?

[MailMan(Ajax Grid).zip](https://github.com/NonFactors/MVC6.Grid/files/1939441/MailMan.Ajax.Grid.zip)

**Comment by elliscnck** [comment]
if you could assist on the "Grid Global Search" question it would be greatly appreciated. Thank you.

**Comment by Muchiachio** [comment]
Don't copy paste :smiley:

Your `NotifyIndex` is using `Url.Action` instead of `Url.Page` used in razor pages, resulting in endless recursion, after you change that you just need to add search parameter and filter it on index grid.

It's bad that I'm sharing it, but here's a working copy. [MailMan.zip](https://github.com/NonFactors/MVC6.Grid/files/1943520/MailMan.zip)
