### ISSUE TITLE
Total Count when filtering

### ISSUE THREAD

**Issue by nbw71791** [NonFactors/MVC6.Grid#137]
Is there any way to get the count of paged total records after filtering? I see there is a TotalRows property on the GridPager class, but it is 0 every time. I also see that there is a RowsPerPage and TotalPages property, but TotalPages is also 0 every time.

**Comment by nbw71791** [comment]
Yes the pager is working as expected. I am using the method of creating the grid described on [this page](http://mvc6-grid.azurewebsites.net/Grid/Export) so that I can also use excel export. So the definition of the grid is written in the controller.

**Comment by Muchiachio** [comment]
It becomes available after first grid rows enumeration, so you have to `.Rows.ToArray()` or something else.

**Comment by nbw71791** [comment]
Perfect, thank you. 

For future reference to anyone, be sure to do this **after** setting your columns to filterable or sortable. Enumerating as the last step of my method before returning the grid did the trick.

**Comment by elliscnck** [comment]
is it possible to show the total records and the count for the current paging? 

total records:1518 
Viewing: 1-10

**Comment by Muchiachio** [comment]
Yes you can change pager partial with `.Pageable(pager => pager.PartialViewName = "_YourPartial")`.

**Comment by elliscnck** [comment]
not following... how would the "_YourPartial" look.

**Comment by elliscnck** [comment]
I would like the info above the Grid so I changed the _Grid but I'm not getting the total records using Model.Pager.TotalRows and if I do the rest of the Page... info doesn't work correctly, what am I doing wrong?

    @{
        Int32 totalRows = Model.Rows.Count();
        Int32 currentPage = Model.Pager.CurrentPage;
        Int32 totalPages = Model.Pager.TotalPages;
    }
    Total Records: @totalRows, Page @currentPage of @totalPages

**Comment by elliscnck** [comment]
not sure why I have to query Model.Rows.Count(); to get this to work.

    @{
        Int32 dummy = Model.Rows.Count();
        Int32 totalRows = Model.Pager.TotalRows;
        Int32 currentPage = Model.Pager.CurrentPage;
        Int32 totalPages = Model.Pager.TotalPages;
    }
    Total Records: @totalRows, Page @currentPage of @totalPages

**Comment by Muchiachio** [comment]
It's needed, because everything is calculated after filters are applied, and because of fluent nature of grid initialization you can go `.Pageable` and then `.Filterable`, which would results in bad data at the end.

I think this can be improved somehow so I will think of a way for next releases.
