### ISSUE TITLE
Action Links

### ISSUE THREAD

**Issue by Wayne-Mather** [NonFactors/MVC6.Grid#14]
Hi,

I have the following code:

```
columns.Add(model => model.Username)
            .Encoded(false)
            .Sortable(false)
            .Filterable(false)
            .RenderedAs(o =>
            {
                var encoder = HtmlEncoder.Default;
                using (var writer = new System.IO.StringWriter())
                {
                    Html.ActionLink("Edit", "Edit", new {id = o.Username}).WriteTo(writer, encoder);
                    writer.Write(" ");
                    Html.ActionLink("Delete", "Delete", new {id = o.Username}).WriteTo(writer, encoder);
                    return writer.ToString();
                }
            });
```

With your intrinsic knowledge of the code base/.NET, is there an easy way of achieving this in the razor view? 

I am thinking of just using the new <a asp-controllerxxx syntax and string.concat to achieve the same goal, but thought it would be interesting to see how you would implement this with your grid.

**Comment by Muchiachio** [comment]
You can pass `Html.ActionLink` to `Add` or `RenderedAs` methods and it will be rendered as html by default without a need of string writer and encoding stuff. [Here](http://mvc6-grid.azurewebsites.net/Column/Encoding) are some examples, so in your case it would be
```C#
columns.Add(model => Html.ActionLink("Edit", "Edit", new { id = model.Username }));
columns.Add(model => Html.ActionLink("Delete", "Delete", new { id = model.Username }))
```
Sorting and filtering will be disabled by default, because your content is not a property.

**Comment by Wayne-Mather** [comment]
Hi, 

This is great if you don't want to worry about the column widths, but my actions need to be close together. Without trying to resort to some fancy DOM hacks, it's easier to stick my actions in the same cell of the table for UI/UX requirement that I have.

**Comment by Muchiachio** [comment]
You could style both column to be close together, or use classes like `TagBuilder` or `IHtmlContentBuilder` to create one big html content in some sort of grid extension.
