### ISSUE TITLE
NonFactors.Grid.Mvc 6 stopped working after updating to newer version 3.0.0. I can see the error in console "ERR_INCOMPLETE_CHUNKED_ENCODING"

### ISSUE THREAD

**Issue by prasad-varade** [NonFactors/MVC6.Grid#140]

**Comment by Muchiachio** [comment]
As per [contribution](https://github.com/NonFactors/MVC6.Grid/blob/12a58a98f7929e1d89ef443e0d76e3ae9115e042/CONTRIBUTING.md) guidelines, please provide a repro project I can look at or analyze the problem first and tell how exactly does the "grid" and not your project configuration contribute to this problem.

**Comment by Fleahole** [comment]
I had the same error. After some testing I found the issue. One of the Child Objects which had fields in the grid was NULL for some records. I entered an empty object and then it was okay.

**Comment by Muchiachio** [comment]
That should be plainly visible in the logs then.

**Comment by Fleahole** [comment]
Yes, you are right. I have to get my logging up to par to find issues like this more easily. Thank you for the excellent component by the way! Really, really good work! Thank you very much!

**Comment by prasad-varade** [comment]
not able to figure out can someone please help

**Comment by Muchiachio** [comment]
Does it happen only when grid is included? Are there any errors visible in the logger output?
If you provide a repro I can take a look too.
