### ISSUE TITLE
Post data (referenced to #123)

### ISSUE THREAD

**Issue by Iztoksson** [NonFactors/MVC6.Grid#141]
I need to post grid data back to the server. I saw your reply to a now closed issue #123 and I understand the principle, here's how I did it:

    columns.Add(model => model.FirstName)
        .Titled("First name")
        .Encoded(false)
        .RenderedAs(m => m.FirstName + "<input type=\"hidden\" name=\"Persons[0].FirstName\" value=\"" + +m.FirstName + "\" />");

The question is how can I get an indexer of rows to correctly number them inside [n] (at the Persons[n].FirstName)? Is there like a "RowIndex" property or something similar?

**Comment by Muchiachio** [comment]
Make a row index and increase it on the last column, similar to this
```C#
.Build(columns =>
{
    int row = 0;

    columns.Add(model => model.FirstName).RenderedAs(m => row);
    columns.Add(model => model.LastName).RenderedAs(m => row++);
}
```

**Comment by Iztoksson** [comment]
Thank you, your suggestion is working as expected. This is my final solution:

	.Build(columns =>
	{
		int row = 0;

		columns.Add(model => model.FirstName)
			.Titled("First name")
			.Encoded(false)
			.RenderedAs(m => m.FirstName + "<input type=\"hidden\" name=\"Persons[" + row + "].FirstName\" value=\"" + m.FirstName + "\" />");
		
		// more columns ...
		
		// Increment row at the last property.
		columns.Add(model => model.LastName)
			.Titled("Last name")
			.Encoded(false)
			.RenderedAs(m => m.LastName + "<input type=\"hidden\" name=\"Persons[" + row++ + "].LastName\" value=\"" + m.LastName + "\" />"); ;
		
		columns.Add(model => $"<a href=\"#\">Edit</a>").Encoded(false);
	})

Also thank you for this great extension!
