### ISSUE TITLE
Custom sorting

### ISSUE THREAD

**Issue by Itakna** [NonFactors/MVC6.Grid#142]
Hi!

I have a question about grid sorting. In my project all filtering and sorting is done by stored procedures. I disabled mvc6 grid filtering by creating extension class to BaseGridFilter and by overriding Apply method.
Then I registerd it in StartUp.cs as mentioned in tutorial : 
  `services.AddMvcGrid(filters =>
{       
                filters.Register(typeof(String), "contains-extended", typeof(GridExtendedFilter));
            });`
Everything works as I intended with these filters.
My question is - could there be something similar done with sorting? Thanks in advance.

**Comment by Muchiachio** [comment]
If you disabled default grid sorting you can sort directly in your controller and it will just render the data in the order you gave it to the grid.

**Comment by Itakna** [comment]
If I disable sorting for the grid (not using .Sortable()), then I am losing ability to click on header rows for activating sort.
Do I have to manually do that in JavaScript?

**Comment by Muchiachio** [comment]
Hmm, that way you will need to implement your own `IGridColumnSort` and set it for each column, either with single column extension or a grid one to iterate every column after the build function is called.

**Comment by Muchiachio** [comment]
It's not as complex as you think, you just need to set column sort to your own implementation which would not sort. I'm just suggesting extensions to keep consistency with current grid method chaining.
You can use current grid column extensions like `.Sortable(Boolean)` as an example.

Here's a raw set example without extensions.

```C#
columns.Add(model => model.Name).Sort = new DoNothingSort<MyModel, String>();
```
```C#
public class DoNothingSort<T, TValue> : IGridColumnSort<T, TValue>
{
    public IQueryable<T> Apply(IQueryable<T> items)
    {
        return items;
    }
}
```

**Comment by Itakna** [comment]
Sorry if it is a dumb question, but is there a way to pass grid column from grid html code (`columns.Add(model => model.Name).Sort = new DoNothingSort<MyModel, String>();`) to this "DoNothingSort" class? When I implement IGridColumnSort interface there is also some public members that needs to be implemented like `public IGridColumn<T, TValue> Column { get; set; }
`
In your code its done through constructor 

```c#
public GridColumnSort(IGridColumn<T, TValue> column)
{   
      Column = column;
      IsEnabled = column.Expression.Body is MemberExpression ? (Boolean?)null : false;
}
```

**Comment by Muchiachio** [comment]
`.Add(model => model.Name)` returns the column you need, but you don't have to necessary implement the same constructor, because you are not using those variables.

**Comment by Itakna** [comment]
Thank you for your patience and support. I ended up with creating extension method as you mentioned above.
Keep up the great work with grid. It is awesome ;)

**Comment by nickwade-phl** [comment]
Is there any way to use this methodology to implement a "natural sort" for string columns which contain mixed alphabetical / numeric characters?

**Comment by Muchiachio** [comment]
Yes, the above comment with example implementation still applies.

**Comment by nickwade-phl** [comment]
> `.Add(model => model.Name)` returns the column you need, but you don't have to necessary implement the same constructor, because you are not using those variables.

I am a little stuck on my specific use case, because I think I do need the Column Expression property to apply the sort.

How would I pass the column into the constructor from my controller? My Sort method currently looks like this (I haven't applied any natural sort logic yet):

```
public class NaturalSort<T, TValue> : IGridColumnSort<T, TValue>
    {
        public bool? IsEnabled { get; set; }
        public GridSortOrder? Order { get; set; }
        public GridSortOrder? FirstOrder { get; set; }
        public GridSortOrder? InitialOrder { get; set; }
        public IQueryable<T> Apply(IQueryable<T> items)
        {
            if (IsEnabled != true || Order == null)
            {
                return items;
            }

            if (Order == GridSortOrder.Asc)
            {
                return items.OrderBy(Column.Expression);
            }

            return items.OrderByDescending(Column.Expression);
        }
        public NaturalSort(IGridColumn<T, TValue> column)
        {
            Column = column;
            IsEnabled = column.Expression.Body is MemberExpression ? (Boolean?)null : false;
        }
        public IGridColumn<T, TValue> Column { get; set; }
    }
```
And I am calling it like this
```
            grid.Columns.Add(m => m.Number)
                .Css("tglRecommendationId isDefault")
                .Titled("Id")
                .Sort = new NaturalSort<DetailedRecommendation, string>();
```

But I am not sure how to pass the column in to the constructor.

**Comment by Muchiachio** [comment]
`.Add(m => m.Number)` returns a column.

**Comment by nickwade-phl** [comment]
I see, I didn't think to assign the result of the .Add method to a variable. Instead I had just tried re-using the .Add method inside of my NaturalSort declaration, and was getting a duplicate column.
```
            var numberColumn = grid.Columns.Add(m => m.Number);
            numberColumn
             .Css("tglRecommendationId isDefault")
             .Titled("Id")
             .Sort = new NaturalSort<DetailedRecommendation, string>(numberColumn);
```
