### ISSUE TITLE
What is simplest way in Razor pages to get an anchor tag column with link to row details

### ISSUE THREAD

**Issue by paulvanbladel** [NonFactors/MVC6.Grid#144]
So, I have a grid on page  http://localhost:5110/Baskets
and the details of row are on: http://localhost:5110/Baskets/Details?id=x (where x is the id of the row data)

I'm trying with
```
   columns.Add(model => Html.ActionLink("Details", "Details", new { id = model.Id }));
```
but no success.
Hints?
Thanks a lot in advance
warm regards
paul.

**Comment by Muchiachio** [comment]
It should work, does the link generate outside the grid? Maybe routing doesn't work correctly.
And what are you getting? No link? Bad link? Something else?

**Comment by paulvanbladel** [comment]
Yeah, it doesn't work outside the grid.
Is there an alternative way for something so simple as an anchor tag in razor pages ?

**Comment by Muchiachio** [comment]
Don't know about razor pages, but you could use not encoded strings together with `Url.Page`.
Or make an extension to create tag builder based anchor tags.

**Comment by paulvanbladel** [comment]
Thx. Indeed an issue not directly related to the grid. 
BTW, great work and very useful.
