### ISSUE TITLE
Handling Null Object

### ISSUE THREAD

**Issue by wildanmuhlis2** [NonFactors/MVC6.Grid#145]
How to handle Null object but still make sort functionality working?
I've tried this code on OrganizationUnit object, but sorting functionality not shown

```
@(Html
    .Grid(Model)
    .Build(columns =>
    {
        columns.Add(model => model.UserName).Titled("UserName");
        columns.Add(model => model.OrganizationUnit == null ? ".": model.OrganizationUnit.Name).Titled("Departemen");
  

    }).Filterable().Sortable(true).Named("User")
)
```

**Comment by Muchiachio** [comment]
Easiest approach is to map your data to a view model, like this
```
Models.Select(model => new UserView
{
    OrganizationUnitName = model.OrganizationUnit.Name
})
```
and use those new models in the grid.

Sorting is disabled for non property expressions, but you can still force sorting on that column
by using `.Sortable(true)` on the column, keep in mind that it will try creating
```
.OrderBy(model => model.OrganizationUnit == null ? "." : model.OrganizationUnit.Name)
```
expression, which might or might not working with your provider.
