### ISSUE TITLE
Retain POST body parameter on sort / filter with server-side grid

### ISSUE THREAD

**Issue by nbw71791** [NonFactors/MVC6.Grid#146]
I have a grid that is being created on the controller as exemplified [here](http://mvc6-grid.azurewebsites.net/Grid/Export). I also have a text area where users can input a comma separated list of identifiers which is then posted to the controller as a filter and filters and returns a new grid.

When I try to sort this newly filtered grid, the sort is applied but the filter is lost. I tried storing the list in TempData, but when sorting this type of grid the request comes back as a GET and the TempData is passed back in the header, which throws an error stating the header is too long.

So the question is: how can I make the sort return a POST request with a server side designed grid?

I noticed that it was possible with an AJAX grid, but can I implement an AJAX grid with the server side designed grid?

**Comment by Muchiachio** [comment]
You can make ajax grid on the server side, all ajax does is use partial action to get rendered grid.
So you can create grid on the controller and then render it in the partial with
```
@model IGrid<YourModel>

@(new HtmlGrid<Person>(Html, Model))
```

**Comment by nbw71791** [comment]
Works like a charm with the partial view / ajax grid. Thanks again!
