### ISSUE TITLE
Small documentation error

### ISSUE THREAD

**Issue by Prusias** [NonFactors/MVC6.Grid#147]
On the page: http://mvc6-grid.azurewebsites.net/Grid/Paging there is a small error under the code for the View.

the following line is wrong:
" pager.PageSizes = new DictionaryInt32, String> { { 0, "All" }, { 2, "2" }, { 4, "4" } }; "
it should be:
" pager.PageSizes = new Dictionary<Int32, String> { { 0, "All" }, { 2, "2" }, { 4, "4" } }; "

**Comment by Muchiachio** [comment]
Fixed.

**Comment by tjoudeh** [comment]
https://mvc6-grid.azurewebsites.net/paging still there :(

**Comment by Muchiachio** [comment]
Was wondering how it got fixed without a commit reference 😔
