### ISSUE TITLE
Ajax - method parameters not passed

### ISSUE THREAD

**Issue by Bimbinbiribong** [NonFactors/MVC6.Grid#148]
Hey.
I have following components in my source:

Controller:
```csharp
[HttpGet]
[HttpPost]
 public PartialViewResult Grid(string name)
{
    return PartialView("_CarsGrid",
       *GetModel*);
}
```

_CarsGrid.cshtml:
```csharp
...
@Html.Grid(Model).Build(columns =>
{
...
}).Pageable(pager =>
{ pager.RowsPerPage = 1; })
```

List.cshtml:
```csharp
<!DOCTYPE html>

<html>
<head>
    <link rel="stylesheet" href="~/css/mvc-grid.css" />
</head>
<body>
    @Html.AjaxGrid(Url.Action("Grid"))

    <script src="~/js/jquery.min.js" type="text/javascript"></script>
    <script src="~/js/mvc-grid.js" type="text/javascript"></script>
    <script>
        $('.content-refresh').on('click', function () {
            $('.mvc-grid').mvcgrid({
                requestType: 'post', // defaults to get
                reload: true,
                data: {
                    name: 'Joe'
                }
            });
        });
    </script>
    <script>
        $('.mvc-grid').mvcgrid();
    </script>
</body>
</html>
```

If I refresh browser page (or turn to other grid page), method *Grid* is called on the controller, but *name* parameter isn't passed to the method.
The parameter seems to be not even send to the controller.
Is there any mistake in my code that I cannot find? I walked through steps in tutorial many times, but it's never started working.
Thx.

**Comment by Muchiachio** [comment]
This is expected behavior. You refresh the page, you lose all the state it had, unless you save it somehow.
If you still have that data on the page after the refresh you can pass it to the grid on the first initialization.
So instead of
```
.mvcgrid()
```
do
```
.mvcgrid({
    requestType: 'post', // defaults to get
    data: {
        name: 'Joe'
    }
})
```
and it should work after refresh.

**Comment by Bimbinbiribong** [comment]
It works, thank you very much.
Is there any recommended approach to pass complex parameters to the method? For example to pass the data parameter in request body?

Currently I use this:
```javascript
var filter = @Json.Serialize(Model.Filter);

    $('.mvc-grid').mvcgrid({
        data: {
            "filter.BrandId": filter.brandId,
            "filter.ModelId": filter.modelId
        }
    });

    $('.content-refresh').on('click', function () {
        $('.mvc-grid').mvcgrid({
            reload: true,
            data: {
                "filter.BrandId": filter.brandId,
                "filter.ModelId": filter.modelId
            }
        });
    });
```

**Comment by Muchiachio** [comment]
Never used complex models for grid filtering, so I can't say for sure.
But wouldn't it be simpler if your grid action took the filter parameter itself? 
That way you could probably inline the json data, like so?
```JS
$('.mvc-grid').mvcgrid({
  data: filter
});
```

**Comment by Bimbinbiribong** [comment]
It works. Thanks.
