### ISSUE TITLE
A rendered button inside mvc grid doesn't listen to click event

### ISSUE THREAD

**Issue by paulvanbladel** [NonFactors/MVC6.Grid#149]
I have following button OUTSIDE mvc grid:
```
<button id="myButton" class="btn btn-sm btn-default">Test 123</button>
```
with following eventhandler in javascript
 $('#myButton').on('click', executeTestButton)
Works perfectly.
when I do the same for an mvc grid the handler is never called:
```
  columns.Add(model => model.Id).RenderedAs((d) =>
         {
         return Html.Raw("<button class='btn btn-default' id='myButton'>Select</button");
         });
```
I'm using this approach because i'm using asp.net razor pages. ActionLinks doesn't work with razor pages.

**Comment by Muchiachio** [comment]
I think the problem is that you are using id to bind an event. As per html spec:
> 7.5.2 Element identifiers: the id and class attributes
> > This attribute assigns a name to an element. This name **must be unique** in a document.

And from jquery selector documentation:
> Each id value must be used only once within a document. If more than one element has been assigned the same ID, queries that use that ID will only select the **first matched element in the DOM**. This behavior should not be relied on, however; a document with more than one element using the same ID is invalid.

Most likely you are binding your event to the first button only.

**Comment by paulvanbladel** [comment]
@Muchiachio thanks for the valid point, but it's not the root cause, as @MerkavaPL  indicated.
@Muchiachio Just wondering. I'm using razor pages where the usage of tag helpers is encouraged.
Is there a way to use taghelpers inside the RenderAs function of Mvc grid?
For example.
outside mvc grid following markup 
```<a asp-page="./Index">Back to List</a>```
is transformed to
```<a href="Mystuff/" Back to List</a>```
When using this inside mvc grid with:
```   columns.Add(m =>  $"<a asp-page=\"./Index\">Back to List</a>").Encoded(false);
```
the markup is not translated to href.
any idea to get this working?
cheers

**Comment by Muchiachio** [comment]
It was the root cause from the information which you provided me :)
No, mvc core doesn't support using tag helpers like that, but you can use `Url.Page("Index")` for urls.

**Comment by paulvanbladel** [comment]
> It was the root cause from the information which you provided me :)
Sure, and I'm very grateful for your continuous support.
Indeed, for the anchor tag, that's the way to go, but unfortunately the programmatic way, so like ActionLink stuff (which mvc grid fully endorses) is not possible for razor pages.

https://forums.asp.net/t/2141466.aspx?How+can+I+generate+programmatically+a+LINK+in+RAZOR+PAGES

**Comment by Muchiachio** [comment]
Well it's possible if you write your own action link extension for razor pages. I guess mvc team couldn't make action link work for razor pages, because it requires using different url method and there is no way to know if it's going to be used from razor pages or not.

**Comment by paulvanbladel** [comment]
@Muchiachio yeah indeed. Razor pages are very powerful and for 95% of the cases easier/less code than mvc.
Closing the issue. Thanks again for your insights and suggestions.
