### ISSUE TITLE
Grid link button

### ISSUE THREAD

**Issue by salgadonline** [NonFactors/MVC6.Grid#15]
Has someway to create in the grid buttons with some template?
With row clicked event i can only redirect to edit or delete event.

**Comment by salgadonline** [comment]
with row clicked event i can only redirect to edit or delete event

**Comment by Muchiachio** [comment]
You can any any html to your row column using `.Add` or `.RenderedAs` methods, you could also pass any templates that you have in `String` or `IHtmlContent` format. [Here](http://mvc6-grid.azurewebsites.net/Column/Encoding) are some examples.

**Comment by salgadonline** [comment]
Thanks a lot !!!
