### ISSUE TITLE
Filter by default

### ISSUE THREAD

**Issue by AngryShaDoW** [NonFactors/MVC6.Grid#151]
Hi, Is any way to enable filter by default? 
I mean enable filter for first view until user have disabled it.

I am use ajax grid.

**Comment by Muchiachio** [comment]
It's only available through a query, so you would have to set it to your wanted filter one.
You can filter and then check the generated url to use.

**Comment by Muchiachio** [comment]
Yes, it's a workaround, because currently grid doesn't support dong via configuration.
I'm planning to add it in the next release if it will be possible without breaking changes.

**Comment by Muchiachio** [comment]
Sorry, I couldn't find any reasonable way to do it, so I will be closing this for now.
Applying default filter isn't hard, but clearing values and overwriting filter again proves to be a problem.
