### ISSUE TITLE
Unregister basic filter

### ISSUE THREAD

**Issue by irsooti** [NonFactors/MVC6.Grid#152]
Hi,

Basically I can't unregister default filters using the same approch you use in the example page (http://mvc6-grid.azurewebsites.net/Filter/Unregister) 

![image](https://user-images.githubusercontent.com/7157155/41460673-c27b4cba-708d-11e8-9283-350a0d8bc8ab.png)

But it stills here

![image](https://user-images.githubusercontent.com/7157155/41460722-e0850b60-708d-11e8-906d-bef3f60dbe96.png)

![image](https://user-images.githubusercontent.com/7157155/41460888-58d22800-708e-11e8-8182-89cea5f80fdc.png)

Any Ideas? 
Thank you in advice

**Comment by Muchiachio** [comment]
It's only a server side unregistration, as example shows you need to remove them from client side too.
```JS
var CustomTextFilter = (function (base) {
    MvcGridExtends(CustomTextFilter, base);

    function CustomTextFilter() {
        base.apply(this);

        this.methods = ['contains', 'equals', 'not-equals'];
    }

    return CustomTextFilter;
})(MvcGridTextFilter);

$('.mvc-grid').mvcgrid({
    filters: {
        'text': new CustomTextFilter()
    }
});
```

**Comment by irsooti** [comment]
Thank you for the fast response, you made my day!
