### ISSUE TITLE
Question: How to access the result list of a filter

### ISSUE THREAD

**Issue by paulvanbladel** [NonFactors/MVC6.Grid#153]
I want to do an specific operation on the result of the application of one or more filters.
How can I do this?

**Comment by paulvanbladel** [comment]
Hi,
Thanks a lot for the prompt reply.
In fact, I want to do kind of bulk update on the rows that remain in the grid after applying query filters.
So, the screen contains apart from the mvc grid also a button which initiates a post request.
As param for this post I would like to send the ids of the grid rows but if there is a more elegant way to get the selected rows at the server ...

**Comment by Muchiachio** [comment]
If your user process is `filter`->`see if they are ok with the data`->`submit for update`.
I would recommend using inputs in a hidden column.

However if you want to update them `on filter` you would have to move your grid declaration to the controller similar to [export example](http://mvc6-grid.azurewebsites.net/Grid/Export) and use grid's `Rows` property to access the model ids for update before you return the grid for rendering.

**Comment by paulvanbladel** [comment]
My workflow is the first one you suggest: filter->see if they are ok with the data->submit for update.
Could you give an example how to store inputs in hidden column?
Thanks

**Comment by Muchiachio** [comment]
You need to render input values and use a css class which hides the column.
`columns.Add(model => Html.Hidden("ids[]", model.Id)).Css("hidden")`.

**Comment by paulvanbladel** [comment]
Thanks for your continuous support.
Sorry, I don't see it quite well. Using Razor Pages.
Isn't there a way to access the data via javascript?
When I try the data object from 
```var instance = $('.mvc-grid').mvcgrid('instance')```` 
it is undefined.

**Comment by Muchiachio** [comment]
Your call is correct, but data is not available from the javascript's instance.
Maybe you are using older scripts or `$('.mvc-grid')` returns no matches.

**Comment by paulvanbladel** [comment]
Do I understand correctly that when there are data on the screen, instance _**should**_ contain data?
I'm seeing version 3.1.0 in the browser F12.

**Comment by paulvanbladel** [comment]
to be very concrete: I have a grid on screen and I'm in the javascript console of my chrome browser.
I type:  var instance = $('.mvc-grid').mvcgrid('instance');
should instance.data contain data?
Thanks a lot
paul.

**Comment by paulvanbladel** [comment]
No worries.
Your suggestion 
```
columns.Add(model => Html.Hidden("ids[]", model.Id)).Css("hidden")
```
is working great !
Thanks a lot for the help. Very much appreciated.
