### ISSUE TITLE
Always redirect to application host url. Ajax:Off

### ISSUE THREAD

**Issue by daremachine** [NonFactors/MVC6.Grid#158]
Hi all, I used grid from tutorial and I found issue with url. If I have basic setup and do filtering or anything then redirect me always to the application root url.
I guess this line  

https://github.com/NonFactors/MVC6.Grid/blob/05ab1e05cc278bf0ac3c0e15b7c23441eb81b20b/src/Mvc.Grid/Scripts/MvcGrid/mvc-grid.js#L284

should be `window.location.href = window.location.origin + window.location.pathname + '?' + grid.query;`

If I changed this line with code before, everything works.

I have ajax off, and I am using annotation routes in controller/actions in ASP Core 2.1.

Its bug or I do something wrong? Thank you.

**Comment by Muchiachio** [comment]
What kind of url and browser do you have? Strange that it worked for so many years. For example here:
```
> window.location.origin
"https://github.com"

> window.location.pathname
"/NonFactors/MVC6.Grid/issues/158"

> window.location.href
"https://github.com/NonFactors/MVC6.Grid/issues/158"

> window.location.origin + window.location.pathname
"https://github.com/NonFactors/MVC6.Grid/issues/158"
```
It's the same.

**Comment by Muchiachio** [comment]
Perhaps you had the time to check url and different javascript methods?

**Comment by Muchiachio** [comment]
I guess I will change it to `location.search`, still would be nice to know why it happens :(

**Comment by daremachine** [comment]
Hi man,

Thank you for help.
I tried your code but didnt work. I was debug that and location search wont set new value. Its still empty.
Look at pictures pls. I can spend more time to investigate later.

PS: Sorry for late answer due to vacation.

https://prnt.sc/khu2e9
https://prnt.sc/khu2kl
https://prnt.sc/khu2m9

**Comment by Muchiachio** [comment]
I found out that url manipulation using history push state or other methods result in these type of problems, maybe were doing something similar.
