### ISSUE TITLE
Inline Add/Edit functionalities

### ISSUE THREAD

**Issue by saravan23** [NonFactors/MVC6.Grid#16]
Do we've inline edit/add functionalities in this grid?

**Comment by saravan23** [comment]
Opened this in Grid.web

**Comment by yannicksch** [comment]
this functionalities would be great :)

**Comment by Muchiachio** [comment]
Maybe, but it's kind of crossing grid functionality boundaries :)
I will see if I can do something to make this functionality or make it easier to extend for it. :+1:
