### ISSUE TITLE
Export all data from grid (Not only the selected page data) to Excel

### ISSUE THREAD

**Issue by ivansoriabia** [NonFactors/MVC6.Grid#160]
Hello.

I'm trying to export all data from grid, but I always get an Excel file with the data of the selected page on the pagination.

There is a way to get all the data from all the pages and export it to an Excel file?

Thank You.

**Comment by Muchiachio** [comment]
Yes, remove/disable the grid pager when exporting.

**Comment by ivansoriabia** [comment]
Thank You. It was easier that I thought. 

I will close this issue.
