### ISSUE TITLE
Encoding issue when exporting

### ISSUE THREAD

**Issue by ivansoriabia** [NonFactors/MVC6.Grid#161]
Hello!

I'm having some values in my grid that have the character "ñ" and when I want to export them to Excel, the resulting file shows some strange characters instead of "ñ" so I suppose there is a problem with the encoding.

There is any way to set the enconding of the grid while exporting. Or where I have to set the enconding to be able to export successfully my grid to Excel?

Thank You!

**Comment by Muchiachio** [comment]
Grid uses strings, it's up to you how you will save the string to the source. So if you are following example
```C#
Object value = column.ValueFor(gridRow); // Might be int, bool, string or any other type
```
returns a value as an object, you can convert/save string types with a different encoding if you have to.

**Comment by ivansoriabia** [comment]
The problem is that making the convertion to string provokes that character "ñ" is being transformed to &#xD1; character. 

In the photo you'll see what I'm saying:
![tostring encoding problem](https://user-images.githubusercontent.com/33115120/43942751-7988e356-9c79-11e8-89ac-acf08bc5d5b9.PNG)

Thank You!

**Comment by Muchiachio** [comment]
All your letters look upper cased, maybe you are upper casing them somewhere?
At first I thought that `HtmlString` messes up, but this code works
```C#
HtmlString html = new HtmlString("ñ"); // ñ
String str = html .ToString(); // ñ
```
Can you check if your model has the correct value from
```C#
String value = (TablaListaOfrecimientosRow.Model as YourModelType).YourProperty;
```
And what is your column declaration for this value? You might need to disable html encoding on export.

**Comment by ivansoriabia** [comment]
Yes. My model has the correct value. So the problem is when I have to do the transformation with column.ValueFor(gridRow). 

I could leave like you have said
`String value = (TablaListaOfrecimientosRow.Model as YourModelType).YourProperty;`
but for me it's a dirty solution. If there was another less dirty solution. It would be better.

Thank You!

**Comment by Muchiachio** [comment]
It was not meant as a solution, but more as a debugging tool.
If it's correct in there it means your column declaration is not a simple
```C#
columns.Add(model => model.YourProperty).Encoded(false);
```
I tried it on my example website and it worked correctly.

**Comment by ivansoriabia** [comment]
Thank you. Finally worked as expected! 

I been searching a lot for this problem. And finally I you have said the correct solution!

It has been very helpful. So, I will close this issue.
