### ISSUE TITLE
Custom paging and filtering

### ISSUE THREAD

**Issue by gkfischer** [NonFactors/MVC6.Grid#162]
Hi,
I implemented manual paging to get server side paging as described [here](http://mvc6-grid.azurewebsites.net/Grid/ManualPaging).

The problem is, that filtering now searches the current page only and the pagination still refers to the total number of rows set in the viewbag.

Any way to implement server side filtering other than to register services for each column as shown [here](http://mvc6-grid.azurewebsites.net/Filter/Register)

**Comment by Muchiachio** [comment]
Your only option would be implementing `IGridPager` and registering it as a new grid pager.
I'm not sure if it will help though. If you need manual paging you are most likely using hand written queries which can't be filtered using linq to sql anyway.
