### ISSUE TITLE
Dynamic columns with sorting and filtering

### ISSUE THREAD

**Issue by trfletch** [NonFactors/MVC6.Grid#164]
I am trying to display a grid with some dynamic columns, I can get the columns to display with the data but the filtering and sorting doesn't work, I think this is because I am using a lambda expression to get the data. Is there a way I can get the filtering and sorting to work for these dynamic columns?

`@{ `
    `var customAttributes = (List<CustomAttribute>)ViewBag.CustomAttributes;`
`}`

`foreach (var attr in customAttributes)`
`{`
        `columns.Add(item => item.Attributes.Any(x => x.Id == attr.Id) ? item.Attributes.First(x => x.Id == attr.Id).Value : "N/A")`
       ` .Titled(attr.Name);`
     ` }`

**Comment by Muchiachio** [comment]
By default filtering and sorting is applied on class member expression like `=> model.Property` and so on, if you want them to work on complex expressions (given they are in memory), force filtering with
```C#
columns.Add(...).Filterable(true).Named("unique-column-name");
```

**Comment by trfletch** [comment]
When I try what you suggested as follows:

`      foreach (var attr in customAttributes)`
      `{`
        `columns.Add(item => item.Attributes.Any(x => x.Id == attr.Id) ? item.Attributes.First(x => x.Id == attr.Id).Value : "N/A")`
       ` .Titled(attr.Name)`
      `  .Filterable(true)`
     `   .Named(attr.Id.ToString());`
      `}`

I get the following error message:

![capture](https://user-images.githubusercontent.com/9028528/45629597-a881c780-ba8e-11e8-9cd4-3a44cda8096f.JPG)

**Comment by Muchiachio** [comment]
Check if any of your expression elements are null, grid only consumes null reference exceptions, but this was most likely thrown by linq calls like `.Any`, `.First` and such on null value.

**Comment by trfletch** [comment]
Yes problem solved, I had commented out some code that would have ensured there were not any nulls when I couldn't get it working and forgot to put it back in when trying your solution. This is now working correctly.
