### ISSUE TITLE
Grid Server side filtering

### ISSUE THREAD

**Issue by GVX111** [NonFactors/MVC6.Grid#167]
How make Server side filtering. in old version you had DataTableRequest i can't find alternative object for filtering.

**Comment by Muchiachio** [comment]
This library never had `DataTableRequest`, maybe you are confusing two different libraries?
Server side rendering by hand is shown [here](http://mvc-grid.azurewebsites.net/Grid/GlobalSearch).

**Comment by GVX111** [comment]
I think it was in old version:
``  public class DataTableRequest
    {
        public IEnumerable<Column> Columns { get; set; }
        public int Draw { get; set; }
        public int Length { get; set; }
        public SearchQuery SearchQuery { get; set; }
        public int Start { get; set; }
        public IDictionary<string, object> AditionalParameters { get; set; }
    }
