### ISSUE TITLE
Filtering/Paging Broken After Upgrading to Core 2.1

### ISSUE THREAD

**Issue by aeonopolis** [NonFactors/MVC6.Grid#168]
After upgrading our solution to ASP Core 2.1, and upgrading from MVC6.Grid 2.1 to 3.1, filtering and paging no longer works.  I copied the contents of mvc-grid.css, mvc-grid.js, _Grid.cshtml, and _Pager.cshtml from the 3.1 package, but no luck.  Column sorting works just fine.  For flitering, the 'contains' pop-up box does not open or appear (the page just posts back) and for paging, the numbers also just post back.

Also, when including mvc-grid.js, I get an error at line 739:

$.fn.mvcgrid = function (options) {

Uncaught referenceerror:  $ is not defined.

Any help would be greatly appreciated

**Comment by Muchiachio** [comment]
Looks like you didn't include `jquery` before `mvc-grid` scripts.

**Comment by aeonopolis** [comment]
That was the cause of the uncaught reference error, yes, but I'm still not getting the paging/filter functionality.  Any ideas?

**Comment by aeonopolis** [comment]
The grids were working just fine before the Core upgrade, I was mostly wondering if you knew of any compatibility issues with the new 2.1 infrastructure.

**Comment by Muchiachio** [comment]
You can check by downgrading the grid if it's a problem with net core `2.1` or the `2.1` -> `3.1` grid.
