### ISSUE TITLE
Is it possible to use this with a regular ASP MVC project? (Not Core)

### ISSUE THREAD

**Issue by sebasijan** [NonFactors/MVC6.Grid#169]
It seems the package isntalled fine, and I can add `using` references to it, but when I try using it like so
```
@model IEnumerable<SharedLibrary.Grv>

@using NonFactors.Mvc;

@(Html
    .Grid(Model)
    .Build(columns =>
    {
        columns.Add(model => model.Description).Titled("Description");
        columns.Add(model => model.AverageCost).Titled("AverageCost").Formatted("{0:N}");
        columns.Add(model => model.TotalCost).Titled("TotalCost").Formatted("{0:N}");
    })
    .Empty("No data found")
    .Sortable()
)
```
I get 

> 'HtmlHelper<IEnumerable<Grv>>' does not contain a definition for 'Grid' and no accessible extension method 'Grid' accepting a first argument of type 'HtmlHelper<IEnumerable<Grv>>' could be found (are you missing a using directive or an assembly reference?)

Am I just trying to do the impossible?

**Comment by Muchiachio** [comment]
Yes, it can be used, but you have to use mvc 5 version [here](https://github.com/NonFactors/MVC5.Grid).
Also make sure to follow [installation instructions](http://mvc-grid.azurewebsites.net/Home/Installation).

**Comment by Muchiachio** [comment]
Did it help?

**Comment by 437700418** [comment]
no, thank you
