### ISSUE TITLE
Sort filter and page links

### ISSUE THREAD

**Issue by gopusridhar** [NonFactors/MVC6.Grid#17]
Hi 
Sort filter and page links not working for me.. what is it i could be doing wrong ?

TIA 
/Sridhar.

**Comment by Muchiachio** [comment]
Did you initialize your grid with
```JS
$('.mvc-grid').mvcgrid();
```

**Comment by gopusridhar** [comment]
yes, my view looks like below 
@using NonFactors.Mvc.Grid;

@model ICollection<ProductMapModel>

@{
    ViewData["Title"] = "Product Mapping";
}


<link href="~/Content/MvcGrid/mvc-grid.css" rel="stylesheet" />
<script src="~/Scripts/MvcGrid/mvc-grid.js"> </script> 
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script> 

<script type="text/javascript">
    $(document).ready(function () {
        $('.mvc-grid').MvcGrid();
    });
</script>


@(Html
    .Grid(Model)
    .Build(columns =>
    {
        columns.Add(model => model.SupplierName).Titled("LEVERANTÖR");
        columns.Add(model => model.BrandName).Titled("VARUMÄRKE");

        columns.Add(model => model.Name).Titled("PRODUCT");
        columns.Add(model => model.Gpc).Titled("GPC");
        columns.Add(model => model.Identifier).Titled("IDENTIFIERARE");
        columns.Add(model => model.BaseProductName).Titled("BASPRODUCT");
    })
    .Filterable()
    .Sortable()
    .Pageable()
      
)

**Comment by gopusridhar** [comment]
sorry, some javascript code missing in above code 

![image](https://cloud.githubusercontent.com/assets/10964100/18911935/fde59030-857f-11e6-856a-3cf52de027e8.png)

**Comment by Muchiachio** [comment]
You function call needs to be lower cased, also check if you don't get any JS errors on page load.

**Comment by gopusridhar** [comment]
yeah i have lowered the case now , error i can see is 
jQuery.Deferred exception: $(...).mvcgrid is not a function TypeError: $(...).mvcgrid is not a function
    at HTMLDocument.<anonymous> (http://localhost:58217/ProductMap:51:24)
    at j (https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js:2:29568)
    at k (https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js:2:29882) undefined
jquery.min.js:2 Uncaught TypeError: $(...).mvcgrid is not a function(anonymous function) @ ProductMap:51j @ jquery.min.js:2k @ jquery.min.js:2    Thank you very much

**Comment by Muchiachio** [comment]
Strange, seems like `mvc-grid.js` wasn't included in the page.

**Comment by gopusridhar** [comment]
Hi Muchiachio, i figured it out, there was another version of jQuery in one of partial view. thank you ! 
Just one more question, one of the column i want that user should be able to select from a drop down list and save, how will i achive this function ? could you give some pointers? thanks once again

**Comment by Muchiachio** [comment]
You can pass html string or raw string as not encoded column value.
Everything else should be a matter of javascript code.
```C#
columns.Add(model => Html.Dropdown(...));
// or
columns.Add(model => "<dropdown html..../>").Encoded(false);
```
