### ISSUE TITLE
Upgrade to 4.0.1 - Linq Expression Exceptions

### ISSUE THREAD

**Issue by fdbva** [NonFactors/MVC6.Grid#172]
Hi.

I upgraded only the MVC6-Grid in my solution. The Grid appears on my screen correctly, but it was taking a long time, every time, when it usually is very fast.

Then I checked the output window and this are the errors I get (I changed the project and Controller name):

```
Error: 'System.ArgumentException' in System.Linq.Expressions.dll (x60)
Info : Executed action method Project.XptoController.Index, returned ViewResult in 8475.2863ms.
Info : Executing ViewResult, running view Index.
Error: 'System.NullReferenceException' in Mvc.Grid.Core.dll (x6)
```

Just to make sure I was not crazy, I tried again the version without the upgrade and there was no message in the Debug Output panel and no unnecessary delay.

Unfortunately I don't have time in the following days (or weeks) to make a sample project to reproduce this error.
We do have multiple table relationship configured, there are several `.Include` being used and after materializing we run some processing in memory for the data that is passed to MVC6-grid.

```
<PackageReference Include="Microsoft.AspNetCore.App" />
<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="2.1.2" />
```

I don't know how to give more useful information about this case, unfortunately. =/

**Comment by Muchiachio** [comment]
I tried using MySql in my web project, but it didn't throw any exceptions.
I guess there is something deeper in your configuration or how you use the grid.

**Comment by fdbva** [comment]
I don't know why I didn't see the problem in the earlier version, but I think the issue is with EF Core.

I tried searching the projects for Pomelo MySql provider and EF Core and got a hit:
[An new ArgumentException is throw(already catched) with Navigation Property in EFCore2.1? #11765](https://github.com/aspnet/EntityFrameworkCore/issues/11765)
