### ISSUE TITLE
Filter date with datepicker

### ISSUE THREAD

**Issue by jjtryniszewski** [NonFactors/MVC6.Grid#175]
I try add datepicker like in question #155 but this method don't work for me. 

I try several diffrents methods but it doesn't work for me.

Could you pls tell me how to achieve this?

**Comment by Muchiachio** [comment]
This should work, I'm not sure if it covers the cases of your date picker, but you can try it out
```JS
var JqueryUIDateFilter = (function (base) {
    MvcGridExtends(JqueryUIDateFilter, base);

    function JqueryUIDateFilter(column) {
        base.call(this, column);

        this.methods = ['equals', 'not-equals'];
    }

    JqueryUIDateFilter.prototype.bindValues = function (column) {
        var filter = this;

        base.prototype.bindValues.call(this, column);

        [].forEach.call(filter.popup.element.querySelectorAll('.mvc-grid-value'), function (input) {
            $(input).datepicker();
        });
    };

    return JqueryUIDateFilter;
})(MvcGridFilter);

new MvcGrid(element, {
    filters: {
        'date': JqueryUIDateFilter
    }
});
```

**Comment by jjtryniszewski** [comment]
This custom grid work. Thank you. But I have problem with datepicker. If I clik on datepicker to skip next or prev month, filter popup hide and datepicker is still active on site. I try to write custom popup but it doesn't work. Can you help me with this?

**Comment by Muchiachio** [comment]
The only options I see are
- [Overriding](https://github.com/NonFactors/MVC6.Grid/blob/v4.0.2/src/Mvc.Grid/Scripts/MvcGrid/mvc-grid.js#L604) hide function.
- [Unbinding or rebinding](https://github.com/NonFactors/MVC6.Grid/blob/v4.0.2/src/Mvc.Grid/Scripts/MvcGrid/mvc-grid.js#L623-L625) window events.
- Binding your date picker popup and preventing event propagation.

I will look into this, to make it easier in the next release.
