### ISSUE TITLE
Is it possible to add dynamic rows with javascript ?

### ISSUE THREAD

**Issue by RajeshDhalange** [NonFactors/MVC6.Grid#176]

**Comment by Muchiachio** [comment]
Yes why not?

**Comment by RajeshDhalange** [comment]
How can I do this any sample

**Comment by Muchiachio** [comment]
[Here's](https://stackoverflow.com/questions/18333427/how-to-insert-row-in-html-table-body-in-javascript) one of examples on the internet.
