### ISSUE TITLE
How to handle pagination in Razor page .net Core?

### ISSUE THREAD

**Issue by RajeshDhalange** [NonFactors/MVC6.Grid#177]

**Comment by Muchiachio** [comment]
Grid handles the paging on it's own by refreshing the page with paging parameters or refreshing the partial.
Does something not work?

**Comment by RajeshDhalange** [comment]
OnGet(Int32? page, Int32? rows)  is not calling on click of page number

**Comment by Muchiachio** [comment]
If page doesn't refresh when maybe the javascript is not initialized? Did you call
```
new MvcGrid(yourElement);
```
and it didn't throw any errors?

**Comment by RajeshDhalange** [comment]
Yeah grid is displaying on the first load with page size and number but when I click on page no it will showing blank grid.

**Comment by RajeshDhalange** [comment]
one more information my grid is under form tag

**Comment by Muchiachio** [comment]
If you initialized everything and it magically doesn't work without any errors you will have to share a repro :confused:

**Comment by RajeshDhalange** [comment]
My Code
  `<div class="col-md-6" style="margin-top:10px;">

                    @(Html
                           .Grid(Model.judgmentList)
                           .Build(columns => {
                              columns.Add(model => model.Id).Titled("Id").Css("hide");
                           columns.Add(model => model.Description).Encoded(false);
                           })

                          .Attributed(new { data_type = "individuals" })
                          .Empty("No data found")
                          .RowCss(model => model.Id != 0 ? "headnote" : "")
                          .Pageable()
                          .Pageable(pager => {
                          pager.RowsPerPage = 5;
                    })
                    )

                </div>
`

**Comment by Muchiachio** [comment]
I mean a full repro with the project, because for me this code will work 100% I know that.
You are doing something different or forgetting something.

**Comment by RajeshDhalange** [comment]
No errors in console just reloading whole page with empty data

**Comment by RajeshDhalange** [comment]
Can't share all project I have to create same for grid and will share with you

**Comment by RajeshDhalange** [comment]
Hey, it's working after removing grid from form tag.  but is there any way to work with form tag?

**Comment by Muchiachio** [comment]
It should work in the form tag, although it's strange that you would want to refresh the page just for the grid and lose all your data inside the form. Isn't it better to use the grid without paging in forms?
