### ISSUE TITLE
Question-How to create a new grid

### ISSUE THREAD

**Issue by Moxcis** [NonFactors/MVC6.Grid#178]
First of all thank you for your hard work and a great Grid.
This is just a question not an issue. 

- How do I create a new MVC6.Grid in razor pages? 
- How do I create a new MVC6.Grid in controller using c#? 

Can you please give simple examples?

Thank you

**Comment by Muchiachio** [comment]
Does examples [page](http://mvc6-grid.azurewebsites.net/) cover what you are looking for?

**Comment by Moxcis** [comment]
No I couldn't find how to create a new MVC6 Grid.

I tried the following in 

public HtmlGrid<EO> htmlGridTest;// No errors

then
public async Task OnGetAsync()
        {
            htmlGridTest.Grid.Source = _db.EoListTable.Where(x => x.LevelCode.StartsWith("EXA"));
// No errors too
}

But Now I don't know how to use htmlGridTest.Grid.Source in razor page.

-----------
Also how do I create MVC6 HtmlGrid in razor page?

I tried this: @( new HtmlGrid<Models.EO>) but it's not working. Could you please give a simple example.

Thank you

**Comment by Muchiachio** [comment]
Why do you need to create a new html grid instance by hand if `@Html.Grid` extension does that for you?

**Comment by Moxcis** [comment]
I have multiple grids, 2 for now. The 2 grids got the data muddled up. I fixed that by adding IDs to the grids and  .Named("first"), .Named("second") as per your advice and it's working. I think I am going about things the wrong way. 

I realise now that @Html.Grid is indeed a new instance :-).

Thank you very much and all the best to you.
