### ISSUE TITLE
dotnet core > Visual studio Code

### ISSUE THREAD

**Issue by jhallam3** [NonFactors/MVC6.Grid#18]
Hi there,

I'm using VS Code on the mac and working with dot net core MVC. I can't seem to get this working.
Could you tell me how to add it to my project and I will follow the steps and feedback any errors.

Thanks

**Comment by Muchiachio** [comment]
What exactly doesn't work?

**Comment by Muchiachio** [comment]
Did you manage to get it working?

**Comment by jhallam3** [comment]
Morning, 

No unfortunately not. 

Im using Visual Studio Code on a mac. not sure if thats stoping it. Im keen to get them working.

**Comment by Muchiachio** [comment]
Could you share your errors and stuff?
I tested it on .net core and it was working, I would fix vs code and mac issues if they appear on those platforms.

**Comment by jhallam3** [comment]
Could you tell me how to add it to my project and I will follow the steps to get it working and feed back any errors. 

Does that work for you?

Thanks Jon

**Comment by Muchiachio** [comment]
Installation notes can be found on [official web site](http://mvc6-grid.azurewebsites.net/Home/Installation).
The only difference could be, that you would install package by hand in `project.json`.

**Comment by tkappeler** [comment]
I was able to get it working on Core by doing the following:

1) install via nuget per the official installation instructions
2) add to the Startup.cs as per the official installation instructions.

Now came the tricky part.  The installation does not create the javascript, css or views per the Core project structure.  I created a new, temporary MCV5 project and installed the grid per the nuget package.  On this project, all files are created appropriately.  

3) Re-open Core solution
4) Manually add the CSS from the Content/MvcGrid folder of the temp project into the wwwroot/css folder (or other place of your choosing)
5) Manually add the JS from the Scripts/MvcGrid folder of the temp project into the wwwroot/js folder (or other place of your choosing)
6) Copy the entire Views/Shared/MvcGrid folder of the temp project into the Views/Shared folder.
7) Add the css and js files into the _Layout.cshtml file (or specific page)
8) Created a document.ready function and invoked the "$('.mvc-grid').mvcgrid();" command as directed in the instructions.

This took 5 minutes and worked great!!  Hope this helps

**Comment by Muchiachio** [comment]
Yes, `nuget` and `project.json` doesn't play along here. By not adding nuget content files as project content, so it needs to be added by hand :disappointed: Glad to see it worked for you @tkappeler.

@jhallam3 did you managed to install the grid in your project?

**Comment by dkent600** [comment]
I can't find the css and js files *at all* with the MVC6 version.  It is not a question of adding by hand because they simply are not present anywhere on the hard drive.  The installation instructions are in error in that regard (or the nuget package is).  So it sounds like the only way at the moment to get these files, as mentioned above, is by installing the MVC5 version and grabbing them from there (hoping they will work properly with the MVC6 version).

**Comment by Muchiachio** [comment]
Did you restore the packages? I double checked and all the files are in nuget package and are downloaded correctly on restore into this folder `%userprofile%\.nuget\packages\nonfactors.grid.mvc6\1.4.0\content`.

**Comment by dkent600** [comment]
I can see %UserProfile%\.nuget\packages\nonfactors.grid.core.mvc6\1.4.0  (note the "core").

But there is no content folder, just a lib folder containing the dll.

**Comment by Muchiachio** [comment]
Maybe you only installed the core package and not the actual one with the content and ll dependency?

**Comment by dkent600** [comment]
I have not seen an "actual" one with content, and I've looked.  What is the name of the package containing content, for Core MVC6 ?

**Comment by Muchiachio** [comment]
`NonFactors.Grid.Mvc6` contains the content files and contains a dependency on `NonFactors.Grid.Core.Mvc6`.
While `NonFactors.Grid.Core.Mvc6` only contains the dlls.

**Comment by dkent600** [comment]
ok, that works!  My apologies, it appears that I was not following the instructions!
