### ISSUE TITLE
Value of dataset.id lost

### ISSUE THREAD

**Issue by pIIrash** [NonFactors/MVC6.Grid#180]
Hi @Muchiachio,

I hope these images can help to identify my problem. Ajax grid based on this: http://mvc6-grid.azurewebsites.net/Grid/Ajax.

![chrome_2019-01-03_09-07-26](https://user-images.githubusercontent.com/23501709/50628703-89be1880-0f39-11e9-8982-6fb1d14e15f4.png)

![chrome_2019-01-03_09-09-02](https://user-images.githubusercontent.com/23501709/50628708-8dea3600-0f39-11e9-8c2f-f2c675f78af0.png)

![chrome_2019-01-03_09-10-12](https://user-images.githubusercontent.com/23501709/50628717-92aeea00-0f39-11e9-98fe-38a6a7ef76cd.png)

![chrome_2019-01-03_09-38-55](https://user-images.githubusercontent.com/23501709/50629095-7c099280-0f3b-11e9-81d6-b7ac822f80a3.png)

![chrome_2019-01-03_09-39-03](https://user-images.githubusercontent.com/23501709/50629096-8035b000-0f3b-11e9-919b-3eb4c0ec430c.png)

![chrome_2019-01-03_09-11-01](https://user-images.githubusercontent.com/23501709/50628725-96db0780-0f39-11e9-9217-984c6090f075.png)

![chrome_2019-01-03_09-12-38](https://user-images.githubusercontent.com/23501709/50628731-9c385200-0f39-11e9-9ba8-59be55565ce0.png)

`grid = grid.findElement(element);` returns with new HTML element which was overwritten in reload previously.

![chrome_2019-01-03_09-13-23](https://user-images.githubusercontent.com/23501709/50628739-a5292380-0f39-11e9-8ee5-e5b66ff39367.png)

Thanks in advance.

P.S.: thanks for your work. Good job, useful tool.

**Comment by Muchiachio** [comment]
It might not be available in some part of the code, but I can't repro it being lost completely after complete ajax reloads. Are you running into problems, because of resetting grid configuration?

**Comment by pIIrash** [comment]
Hi. 

Meanwhile I found. JS typo caused my problem.

But,
I've tried to implement something similar than this: https://github.com/NonFactors/MVC6.Grid/issues/87

I just put public array into MvcGrid which has same content that mvcgrid.instances array.
I have initailizeGrid method on the View where I set up configuration for the grid.

And here is where I try to refresh my grid content. (User is notified by the program the content has been changed by other user (refresh button appears))
           
```
            var id = parseInt(document.querySelector('.mvc-grid').dataset.id);
            var grid = MvcGrid.grids[id];
            grid.reload();
        });
```

I just want to pointing, based on the code if I call reload on existing grid instance in the constructor it should goes into this code part.

```
    function MvcGrid(element, options) {
...
        if (element.dataset.id) {
            return grid.instances[parseInt(element.dataset.id)].set(options); <---- TO HERE
        }
```

But it never goes into there. It is possible it is some kind of misunderstanding from my side.

**Comment by pIIrash** [comment]
It looks like my typo caused my problem. My original problem was when I changed external filters It worked until I clear filter value for column, but I've upgraded from 4.0.0.0 to 4.0.2.0 and it fixed this problem and now it works fine with

`new MvcGrid(document.querySelector('.mvc-grid')).reload();`

Thank you for your clarification.
