### ISSUE TITLE
Question: Responsive Table

### ISSUE THREAD

**Issue by dotnetshadow** [NonFactors/MVC6.Grid#183]
Hi there 

I was wondering if you had any thoughts on implementing something similar to this
https://datatables.net/extensions/responsive/examples/styling/bootstrap4.html

Where columns could be defined for smaller screens to be visible and having collapsed child for all other columns?

**Comment by Muchiachio** [comment]
No plans you make something similar, it's also already achievable with bootstrap display classes like `.Css("d-sm-none d-xl-table-cell")` or similar if needed.
