### ISSUE TITLE
Question:  Maintaining model state during paging

### ISSUE THREAD

**Issue by aeonopolis** [NonFactors/MVC6.Grid#184]
Hi,

We have an ASP Core page that functions entirely as search; user loads page, enters terms, hits 'search', and the results are bound to the mvc grid (contained in a partial view).  Since the grid reloads the page and triggers the index every time you page up or down, we are losing our search result list.  We've solved it by serializing the results into temp data and restoring the model every time, but I was wondering if there was a recommended solution, as I imagine most people have had to deal with this.  Thanks!

**Comment by Muchiachio** [comment]
Easiest way would be to have your search be a `GET` request, this way grid preserves the query.
If it's post then the only option is to save it somewhere.

**Comment by aeonopolis** [comment]
That's helpful.  Thanks again
