### ISSUE TITLE
.formatted() dosn`t work as expected

### ISSUE THREAD

**Issue by brokenT** [NonFactors/MVC6.Grid#185]
Hi,

why is following not possible ?

columns.Add(model => model.GuVBrutto).Titled("Guv").Formatted("{0:n}").Encoded(false).RenderedAs(model => model.GuVBrutto > 0 ? ("<span style='color: #08A414'>" + model.GuVBrutto + " </span>") : ("<span style='color: #CC4444'>" + model.GuVBrutto + "</span>")));

The .Formatted("{0:n}") does not working. Is it because the RenderdAs Part follows ?
I put the part .Formatted("{0:n}") at the end, still not working.

Is there any way to use both Parameter for one column and both got to work ?

**Comment by Muchiachio** [comment]
Formatting is intended to be used on the original `.Add(expression)`, if you are using `.RenderedAs` you are overriding everything. So formatting has to be done in there, which you are already doing with `(<value>)`.

You can use string interpolation to achieve quick results, for example: `$"({model.GuVBrutto:0.00})"`.

**Comment by brokenT** [comment]
Thanks a lot for the fast response ! I know these are basics, but can you tell me where i can find a reference regarding the " :0.00}" part ? I need thousands seperators only in the view e.g. 100000.56 ist 100.000,56

I found some functions like this but i don`t know how to call this function inside the .RenderedAs area ?

function mach_tausender(zahl) {
   var i;
   var j=0;
   var ergebnis="";

   i=zahl.length-1;
   alert("i="+i);
   while (i >= 0) {
      ergebnis=zahl.substr(i,1)+ergebnis;
      j++;
      if (j==3) {
         ergebnis="."+ergebnis;
         j=0;
      }
      i--;
   }
   return ergebnis;
}

**Comment by brokenT** [comment]
I knew that, but i tried always to use the value.ToString(), now is use it in this way:

$"{String.Format("{0:N2}", model.GuVBrutto)}"

This is also the solution for my case - thanks a lot for your help...

Not relatedt to this topic, but las question - i use this url for examples and it is easy to use it - thanks for your work: http://mvc6-grid.azurewebsites.net/

Can you tell or show me how i can setup my grid to the Fonts and CSS Style you use in the examples on the example site ? My is too small to read it...

**Comment by Muchiachio** [comment]
I use bootstrap with font awesome icons on example pages, you can find the source [here](https://github.com/NonFactors/MVC6.Grid.Web) and run locally.

**Comment by brokenT** [comment]
Thanks a lot for your help :-)
