### ISSUE TITLE
Custom Filter column/grid Not Found

### ISSUE THREAD

**Issue by Spencer-Morris** [NonFactors/MVC6.Grid#187]
I'm trying to create a custom filter on a date column. I am getting an error that grid is not defined. It appears column is not defined either.

Here is the JS:

```Javascript
var CustomDateFilter = (function (base) {
    MvcGridExtends(CustomDateFilter, base);

    function CustomDateFilter(column) {
        base.call(this, column);

        this.methods = ['equals', 'earlier-than-or-equal', 'later-than-or-equal'];
        column.grid.lang.custom = { equals: 'TEST' };
    }

    return CustomDateFilter;
})(MvcGridDateFilter);

$('.mvc-grid').mvcgrid({
    filters: {
        'date': new CustomDateFilter
    }
});
```

Thanks in advance for your help.

**Comment by Muchiachio** [comment]
Grid not found is most likely a sign that you have non grid html in your ajax grid partial.
If it's not the case you can put a breakpoint on that line and see why it happens.

Also it appears that you are mixing code from two different mvc grid versions.
Make sure you are using the same major or exact version as in examples or checkout [older version](https://github.com/NonFactors/MVC6.Grid.Web/releases).

**Comment by Spencer-Morris** [comment]
Thanks, I was able to get this figured out. I didn't realize the nuget package had been updated and not the views/js.
