### ISSUE TITLE
Date Not Passing to Filter

### ISSUE THREAD

**Issue by Spencer-Morris** [NonFactors/MVC6.Grid#188]
I have this datepicker currently opening when trying to filter by date: [BootstrapDatepicker](https://bootstrap-datepicker.readthedocs.io/en/latest/methods.html). I took the code from issue [175](https://github.com/NonFactors/MVC6.Grid/issues/175) and it seems to be opening the datepicker correctly.

The issue that I am having is that when submitting the filter, no value is being passed into the URL. If I manually type in a date to filter by, it works correctly.

Do you have a suggestion on where to look in the JS to find where this problem is occuring?

Thank you.

**Comment by Muchiachio** [comment]
It's probably the same problem jQueryUI datepicker has, it doesn't dispatch a `change` or `input` event after date selection, so you have to add that by hand, unless the library you are using supports that.
