### ISSUE TITLE
Filter popups don't display correctly on android

### ISSUE THREAD

**Issue by dazinator** [NonFactors/MVC6.Grid#19]
Hi there, thanks for the excellent documentation site. I was going through all the examples, but using my android phone and firefox browser. I noticed a bit of a glitch with the grid filters. When you click the filter button the popup appears correctly. But as soon as you focus an input that requires typing - the on screen keyboard appears and this seems to dismiss the filter popup. This has the effect that you cant use the filters.

**Comment by Muchiachio** [comment]
Thanks, I will take a look.

**Comment by chibuagu** [comment]
I am still experiencing this on Grid.Core.Mvc6

**Comment by Muchiachio** [comment]
Might be regression from removing jquery dependency, will check.

**Comment by Muchiachio** [comment]
Fixed it, path version will be released some time this week.
