### ISSUE TITLE
Column encoding &eacute; / é

### ISSUE THREAD

**Issue by geotinc** [NonFactors/MVC6.Grid#191]
Hi,

I try the following :

`@(Html.Grid(this.Model).Build(columns =>
                      {
                          columns.Add(model => model.UserName).Titled("Nom d'utilisateur").RenderAsLink(model => model.UserName, "User", "Edit", model => model.Id);
                          columns.Add(model => model.FirstName).Titled("Nom");
                          columns.Add(model => model.LastName).Titled("Pr&eacute;nom");
                          columns.Add(model => model.Role).Titled("Type de compte");
                      }).Empty("Aucune ligne !").Filterable().Sortable().Pageable(x => x.RowsPerPage = 50))`

But the & eacute; is not working into Titled, I try é too wihtout success.

How to fix that ?

**Comment by Muchiachio** [comment]
String title gets encoded, you can avoid that by passing instance of `IHtmlString` which doesn't apply encoding, for example `new HtmlString("Pr&eacute;nom")`.

**Comment by geotinc** [comment]
For me, columns.Add(model => model.LastName).Titled("Prénom");
Show the following :
![image](https://user-images.githubusercontent.com/20421571/54292240-204c2d00-45ae-11e9-8f7e-5a186e74f421.png)

Same for the .Empty("Élement")

I didn't understand how to pass IHtmlString for titled, new HtmlString()... is not a string for Titled.

Thanks a lot

**Comment by Muchiachio** [comment]
`.Titled` method takes an object, if it sees that you provided an html string it will use that instead.

**Comment by geotinc** [comment]
.Titled method takes a String, 

I have to do the following : 
![image](https://user-images.githubusercontent.com/20421571/54292599-c435d880-45ae-11e9-918b-b627617ce8c3.png)

but how with Empty ? 
Because EmptyText take a string :
![image](https://user-images.githubusercontent.com/20421571/54292672-e3cd0100-45ae-11e9-9344-59973f2cb2e6.png)

**Comment by Muchiachio** [comment]
Sorry, didn't think that empty text would need that.

For now you would have to use your own grid partial, which would add a raw output of [a text here](https://github.com/NonFactors/MVC6.Grid/blob/v4.1.0/src/Mvc.Grid/Views/Shared/MvcGrid/_Grid.cshtml#L136).
Or you can try finding out why you get gibberish output in the first place. I heard there been problems with unicode strings in older asp net core versions, maybe update would be enough?

**Comment by Muchiachio** [comment]
There is already an [extension](https://github.com/NonFactors/MVC6.Grid/blob/v4.1.0/src/Mvc.Grid.Core/Html/GridColumnExtensions.cs#L105-L110) which allows object values, not sure why you need another.

**Comment by geotinc** [comment]
I have the latest version of asp.net core => 2.2.X
And the version 4.1.0 of NonFactors.Grid.MVC6

I didn't have extension with object in my version (4.1) => I think you did not publish the nuget package ;-)
![image](https://user-images.githubusercontent.com/20421571/54294024-36a7b800-45b1-11e9-913c-812f6da460a2.png)

For the empty text, I have put a @this.Html.Raw(Model.EmptyText) and it's work
![image](https://user-images.githubusercontent.com/20421571/54294283-9c943f80-45b1-11e9-91ea-ddbc50110a31.png)

Very great job !

**Comment by Muchiachio** [comment]
I believe I pushed it, otherwise example pages would crash :smiley:
I also see it in Ilasm and in the dll metadada, you might have some cached references
![image](https://user-images.githubusercontent.com/6647444/54295084-0fee7f00-45bb-11e9-92df-db9c60bca9f0.png)
