### ISSUE TITLE
4.0.1 Cssclasses missing on table

### ISSUE THREAD

**Issue by dotnetshadow** [NonFactors/MVC6.Grid#193]
Hi there,

In earlier versions of the library there was CssClasses for the table. 
It looks like this has gone, how can we add classes to the table?

**UPDATE** 
Looks like you need to use the attributes, but the documentation still points to using the cssClasses

**Comment by Muchiachio** [comment]
Underlying implementation changed, but you still need to use `.CssClasses` method on the grid.
Unless you are working with raw grid, which when would required using an attribute with class key.

**Comment by dotnetshadow** [comment]
Cheers, I did try .css() and .appendCss() I don't see the .CssClasses in fact even if you look at the **_Grid.cshtml** it has `<!table@(Model.Attributes)>` no reference to **cssClasses**. Unless I'm misunderstanding it?

**Comment by Muchiachio** [comment]
Yes, `.CssClasses` is just an extension method similar to `TagBuilder.AddCssClass` method, which set's
`attribute["class"] = value;`

**Comment by dotnetshadow** [comment]
```csharp
@(Html
    .Grid(Model.Leaderboard)
    .Build(columns =>
    {
        //columns.Add(model => model.UserId).Titled("Test");
        columns.Add(model => model.Rank).Titled("Rank").Css("rank");
        columns.Add(model => model.Username).Titled("Username").Encoded(false).RenderedAs(model => "<img class='avatar' data-name='" + model.Username + "' /> <span class='u'>" + model.Username + "</span>");
        columns.Add(model => model.Amount).RenderedAs(model => model.Amount.ToString("C")).Titled(@Html.Raw("Amount<sup>*</sup>")).Css("text-right");
    })
    .RowCss(model => model.UserId == (Model.UserPosition?.UserId ?? "") ? "current-user" : null)
    //.Filterable()
    .Sortable()
    .Pageable(pager =>
    {
        //pager.PagesToDisplay = 3;
        pager.CurrentPage = Model.StartingPage;
        pager.RowsPerPage = Model.PageSize;
    })
    .Named("leaderboard-main")
    .Attributed(new { @class = "table leaderboard-main", data_ranking = Model.UserPosition?.Rank ?? 0, data_total = Model.Total })
)
```

Currently the above works.
If I don't use the **.Attributed** way of adding a class and only use **Css** or  **.AppendCss** the class never gets added at all

**Comment by Muchiachio** [comment]
Yes, attributed overwrites everything now, so it has to be used before css classes, will be fixing that.
