### ISSUE TITLE
What is the best practice when consuming large amount of data ? (44000 records/rows)

### ISSUE THREAD

**Issue by EkoZuluDev** [NonFactors/MVC6.Grid#194]
How do you advise on handeling large amount of data? Now it takes 30 second to load the grid because of the large amount of data which was to be expected. 

How can one manage this and keep the full pageable/sortable/filterable/searchable experience?

Do you have any info which can help me in the right direction?

**Comment by Muchiachio** [comment]
First pages of the grid should load fast even if you have millions of rows, because of paging.
Are you using `IQueryable` interfaces or selecting by hand written queries?

**Comment by EkoZuluDev** [comment]
Sorry , I did not describe my issue clearly. There is nothing wrong with the grid. It is my data retrieval which takes long. Retrieving 44000 records takes time. I was investigating ways how to avoid retrieving 44000 records each time the page is initialized or the grid is sorted/searched etc?

Is there a way to parameterize the controller method which returns grid results for example? 
With page number / search criteria/ sort order etc?

This way I can initialize with 1000 records and when there is a search. I can go and retrieve the data based on the search. same with sort/filter. I cannot find examples which do this.

Some background information. Im retrieving person records from an ODATA feed, transform the results into a list of viewmodels and display these in a view.

**Comment by Muchiachio** [comment]
By default grid does everything itself, but if your data is already in memory you would have to implement your own paging (keep in mind that sorting and filtering would not work that way).

You can check [manual paging](http://mvc6-grid.azurewebsites.net/Grid/ManualPaging) example on how to implement that using parameterized controller.

**Comment by EkoZuluDev** [comment]
Yeah sadly my data is already in memory. I'm fetching all persons then I'm creating a list<Model> of my resultset which is a List<ExpandoObject> and finally present it in the view.

Do you have any tips on how to refactor ODATA -> ExpandoObject to a IQueryable like interface?
If it helps I'm using https://github.com/davidyack/Xrm.Tools.CRMWebAPI/tree/master/dotnet/Xrm.Tools.WebAPI to get data.

Thanks for creating this grid. It really works nice if you use it correctly :-) 👍

**Comment by Muchiachio** [comment]
If it's url based service it won't support querying out of the box. The question would be if it support any kind of paging at all, so you can pass that information to the xrm tool and it would return less data.

**Comment by EkoZuluDev** [comment]
Luckily it is possible https://docs.microsoft.com/en-us/aspnet/web-api/overview/odata-support-in-aspnet-web-api/supporting-odata-query-options. So paging could be managed now at first glance.

Is there documentation on ways to override default sorting and filtering with own implementation? So when users filter on "contains "XXX" " I intercept and query the service and return the result set. Do you catch my drift?

**Comment by Muchiachio** [comment]
Yes there are [examples](http://mvc6-grid.azurewebsites.net/Filter/Register) on how to implement the filter, but it's based on using linq queries on the source, so you would have to expose the raw query somehow.

Another option would be to override [column processing function](https://github.com/NonFactors/MVC6.Grid/blob/v4.1.0/src/Mvc.Grid.Core/Columns/GridColumn.cs#L46), you would have access to parsed filter and sorting values, the only thing left would be to apply them on based on the filtering/sorting rules of the xmr.

So the model source class could look like this
```C#
public class XmrRequest<T> : IEnumerable<T>
{
    public String Url { get; private set; }
    public String Query { get; private set; }

    public XmrRequest(String baseUrl)
    {
        Url = baseUrl;
    }

    public IEnumerator<T> GetEnumerator()
    {
        return XmrClient.Request($"{Url}?{Query}");
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }
}
```
`Query` parameter would be populated on column's apply function or similar.

**Comment by EkoZuluDev** [comment]
Can you elaborate more on the second option? I'm not familiar with how to override the processing function but it sounds like it will work for me. :-)

So in essence what I would like (I do not know if it is possible) is before data is retrieved with the filter/sort mechanism to intercept the query details. Then I create a query for my XRM based on the query of the grid and return the sorted/filtered result set.

**Comment by Muchiachio** [comment]
It's nothing fancy, you just create your own grid column class which inherits the base or normal one
```C#
public class XmrGridColumn : GridColumn<T, TValue>
{
    public XmrGridColumn(IGrid<T> grid, Expression<Func<T, TValue>> expression)
        : base(grid, expression)
    {
    }

    public virtual IQueryable<T> Process(IQueryable<T> items)
    {
        if (Filter.First != null)
        {
            XmrRequest<T> request = items as XmrRequest<T>;
            request.Query += $"&{Filter.First.Method}={Filter.First.Value}";
        }

        return items;
    }
}
```
You can make an extension similar to the [.Add](https://github.com/NonFactors/MVC6.Grid/blob/v4.1.0/src/Mvc.Grid.Core/Columns/GridColumns.cs#L20-L27) method, to use your own grid column instead of default one, all the other extensions will work on top. And the final thing is to pass your xmr request as model
```
@Html.Grid(new XmrRequest("<some_url>")).Build(...)
```

**Comment by EkoZuluDev** [comment]
Thanks for the replies! 

This is what I have so far. I'm trying to hit a breakpoint to really understand what is going on :-). 
My model source
```
public class XrmRequest<T> : IQueryable<T>
    {
        public String Url { get;  set; }
        public String Query { get;  set; }

        public Type ElementType => throw new NotImplementedException();

        public Expression Expression => throw new NotImplementedException();

        public IQueryProvider Provider => throw new NotImplementedException();

        public XrmRequest(String baseUrl)
        {
            Url = baseUrl;
        }

        public IEnumerator<T> GetEnumerator()
        {
            return null;
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }
    }
```
This my override of the grid collumns to instantiate XrmGridColumn
```
public class XrmGridColumns<T> : GridColumns<T> where T : class
    {

        public XrmGridColumns(IGrid<T> grid) : base(grid)
        {
            Grid = grid;
        }
        public override IGridColumn<T, TValue> Add<TValue>(Expression<Func<T, TValue>> expression)
        {
            IGridColumn<T, TValue> column = new XrmGridColumn<T, TValue>(Grid, expression);
            Grid.Processors.Add(column);
            Add(column);

            return column;
        }

    }
```
```
 public class XrmGridColumn<T, TValue> : GridColumn<T, TValue> where T : class
    {
        public XrmGridColumn(IGrid<T> grid, Expression<Func<T, TValue>> expression)
            : base(grid, expression)
        {
            var a = expression;
        }

        public override IQueryable<T> Process(IQueryable<T> items)
        {
            if (Filter.First != null)
            {
                XrmRequest<T> request = items as XrmRequest<T>;
                request.Query += $"&{Name}-{Filter.First.Method}={Filter.First.Value}";
            }

            return items;
        }
    }
```
I have difficulties understanding the "passing of the model to the grid". Currently I pass a list of persons like this 
` .Grid(ViewModel.Client.ToList())
 .Build(columns =>
  {               columns.Add(model => model.FirstName);
                  columns.Add(model => model.LastName);
                  .....
`

I feel like i'm getting close...

**Comment by Muchiachio** [comment]
`ViewModel.Client.ToList()` should be replaced by an instance of `XrmRequest<T>` which will have it's service parameters built by the columns and make the request only on enumeration.

Your `ViewModel.Client` is probably set similar to this `ViewModel.Client = Xmr.Something()`, the ` Xmr.Something()` should go to `XrmRequest<T>.GetEnumerator` method and get executed from there.

**Comment by EkoZuluDev** [comment]
```
public IEnumerator<T> GetEnumerator()
        {
            ClientsOverViewModel model = new ClientsOverViewModel();
            return model.GetContacts().GetEnumerator();
        }

```
The getContacts method retrieves the persons and creates a List<ClientViewModel>

How can I make it work with generic <T>?

**Comment by Muchiachio** [comment]
You can make request class non generic, but that way you will have to make a new class for each model.

**Comment by EkoZuluDev** [comment]
In my case , it is only needed for one model. I will play around with and report back. Thanks for the help so far!

**Comment by Muchiachio** [comment]
I don't think thye will be used by the grid, because you are intercepting everything.
Should be fine to leave them not implemented.

**Comment by EkoZuluDev** [comment]
I did not achieve to make it work but I created a workaround. A couple of pre filter fields which the user can fill in . Then I retrieve data based on the criteria (which is never 45000). Then present the data to grid. The grid remembers the lastly used query so sorting filtering is used with a query which result is never 45000 so everything is working fast en smooth.

Thanks for this great piece of code. Is there somewhere I can donate?

**Comment by Muchiachio** [comment]
I guess as long as it works for you :+1: I'm actually getting more and more of these raw query scenarios. I will see if I can it a first class citizen or and easier API in the next major release as it requires breaking changes.

As for donations, if you really want to you can donate through [paypal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=CGQTQRG8AADYE&source=url).
