### ISSUE TITLE
Ajax grid not rendering on server

### ISSUE THREAD

**Issue by noctilucentsw** [NonFactors/MVC6.Grid#195]
Thank you for such a wonderful tool!
I'm sorry to bother you with such a novice question - I can get the grid to render w/o Ajax, but somehow when I use Ajax it doesn't render once installed on server.
The app is installed in a sub-folder, and the "data-source-url" generated to call the grid (by Url.Page()) appears correct when I view the source.
If I run the code in VS using the debugger (root /), it runs beautifully - only a problem once I install on server - which makes me think there is some problem with accessing related files.
Can you offer any insight?

**Comment by Muchiachio** [comment]
Check network tab if request goes through correctly it will be easy to track what goes wrong in js.

**Comment by noctilucentsw** [comment]
Wow! Thank you SO much.
It was actually quite a silly error - I had the production environment referencing the minified version of the mvc-grid.js, but I had a typo in my bundleconfig.json causing the minified version to not be produced, hence generating a 404.
I actually was impressed with how well you respond to comments as well as the quality of the code while trying to decide which grid to use, and I have not been disappointed. Thanks a million!!!
