### ISSUE TITLE
Database connection examples

### ISSUE THREAD

**Issue by PedroNeff** [NonFactors/MVC6.Grid#197]
Hello Muchiachio, would it be possible for you to add a sample project with database connections?
Having a bit of problems conecting the dots!
Thanks in advance
Pedro

**Comment by Muchiachio** [comment]
Passing entity framework's db set is enough for the grid to work, for example
```C#
[HttpGet]
public ViewResult Index()
{
    return View(Context.Set<Person>());
}
```
I guess you can check our [template](https://github.com/NonFactors/MVC6.Template) project for a full project using the grid, not sure where you are stuck.

**Comment by PedroNeff** [comment]
Ok will try it i am a bit of a noob!

**Comment by Muchiachio** [comment]
Did you managed to work it out?
