### ISSUE TITLE
Differentiating between multiple grids on same view

### ISSUE THREAD

**Issue by wasoza** [NonFactors/MVC6.Grid#2]
Looks like in-spite of naming my multiple ajax grids on the same view (with search) I can't seem to have anything(like id / name/etc) to differentiate between the two.
When I explore the dom I see both grids with same html <div class="mvc-grid">
How can I select or What would be correct Java script to select mvc-grid named "allgrid" and another mv-grid named "limitedgrid". 
Posting here as I am not if it's a limitation at this time or if I am not grasping this correctly.
Thanks in advance

**Comment by Muchiachio** [comment]
You can add different classes on tables using [Css(...)](http://mvc6-grid.azurewebsites.net/Grid/Styling) method and select it from that.
I guess, I should not hide [grid's data-name](https://github.com/NonFactors/MVC6.Grid/blob/develop/src/Mvc.Grid/Views/Shared/MvcGrid/_Grid.cshtml#L5) attribute, to make this easier.

**Comment by wasoza** [comment]
Thanks for looking at tit right away. Will it be better to  use the "Named" attribute as an DIV ID ?...since it already works like a charm for sorting and filtering in the same scenario. Not sure if that makes any sense.

**Comment by Muchiachio** [comment]
Naah populating id's could result in duplicates, which are not supported per html spec.

**Comment by wasoza** [comment]
OK I am a beginner don't have comprehensive knowledge but this communication teaches me and gives me confidence. So if I do .Css("onegrid"), .Css("twogrid") how will it impact JS selector statement....var grid = $('.mvc-grid').data("mvc-grid")

**Comment by Muchiachio** [comment]
It would be
```JS
var grid = $('.onegrid').parent().data('mvc-grid');
```

**Comment by wasoza** [comment]
Thanks. I believe it's safe for most normal operation you want to do the two different/multiple grids. Depending so much on style attributes to handle complex client actions in multiple grid scenario scares me though.

**Comment by Muchiachio** [comment]
You can use your own grid partial to render custom grids, if that helps. Too bad I still didn't add an example for that, but I will, for nested grid one.

**Comment by wasoza** [comment]
Sure I got the idea. Thanks for all the hard work... it's a joy to see this grid show, filter, sort your data
