### ISSUE TITLE
Adding a nested subgrid to a grid row to create a details view?

### ISSUE THREAD

**Issue by Armeggadon** [NonFactors/MVC6.Grid#20]
This is a question more than an issue, but I was wondering if it's possible to add a nested grid with a different model so that when you click a row, a new grid expands from it for additional details. Something similar to this: http://www.dotnetawesome.com/2014/07/nested-webgrid-with-expand-collapse-in-aspnet-mvc4.html. 

I've been trying to modify the Grid Custom Partial example in the web docs, but can't actually work out adding an entire new nested grid for each row rather than adding more rows to the same grid.

**Comment by Muchiachio** [comment]
Changing [these lines](https://github.com/NonFactors/MVC6.Grid.Web/blob/d458d68acceb73b0725b64ef12816a5f4ca52a04/src/Mvc.Grid.Web/Views/Grid/_NestedPersonGrid.cshtml#L55-L68) in a custom partial example to this, should be enough to get to started.
I will update custom partial example to use nested grid instead, as it is seems to be used more often.
```HTML
<tr>
    <td colspan="@Model.Columns.Count()">
        @(Html
            .Grid(row.Model.Children)
            .Build(columns =>
            {
                columns.Add(model => model.Name).Titled("Child name");
            })
        )
    </td>
</tr>
```

**Comment by Armeggadon** [comment]
Ah, I feel dumb for not seeing that on my own, but that got me exactly what I wanted. With the row clicked event bound, it was easy to hook up the expanding and collapsing as well. Thanks for this fantastic grid control.

**Comment by bulbul-in-a-nest** [comment]
Hi Armeggadon,

Can you please help  on how you proceeded with row click event bound for expanding and collapsing? And initially how did you hide the child grid?

**Comment by Armeggadon** [comment]
For starting with the child grid hidden, you can just hide the child elements on document ready:
```javascript
.ready(function() {
    $('tr.parent').siblings('[class^=child]').hide();
})
```

As for expanding and collapsing, I have the first column assigned to the glyph icon that I use for expanded or not as well as an id field that I use for the rowclicked event:
```javascript
columns.Add(model => $"<span class=\"glyphicon glyphicon-plus\" id=\"ID_{model.Id}\" style=\"vertical-align: middle; margin-top: -5px\"></span>").Encoded(false);)
```

And then in the script section, for the mvcgrid, hook up the rowclicked event to toggle the expansion:
```javascript
$('.mvc-grid')
    .mvcgrid({
        rowClicked: function (grid, row, data, e) {
            var rowId = "#ID_" + $(row).find("td").eq(1).html();
            $(rowId).toggleClass("glyphicon-plus glyphicon-minus");
            $(rowId).parent().closest("tr").next().slideToggle(50);
        }
    });
```
I honestly don't know if this is the best or most efficient way of doing things since the site I made is basically just for a handful of people, and this was "good enough"
