### ISSUE TITLE
dynamically added columns (using datatable) doesnt create filter

### ISSUE THREAD

**Issue by jswafford1977** [NonFactors/MVC6.Grid#200]
I have created a table using a dynamic list of columns from a System.Data.DataTable.

The grid renders properly and is sorting correctly, but clicking the Filter button throws the below JS error.
Uncaught TypeError: Cannot read property 'show' of undefined
    at HTMLButtonElement.<anonymous> (mvc-grid.js:422)
Putting a break point @ mvc-grid.js line 422 I find that the filter object is undefined.

here is my code.
```C#
@using System.Data
@model DataTable

@(Html
    .Grid(Model.AsEnumerable())
    .Build(columns =>
    {
        foreach (DataColumn column in Model.Columns)
        {
            if (column.ColumnName == "DOB")
            {
                columns.Add(model => model.ItemArray[column.Ordinal]).Titled(column.ColumnName).Formatted("{0:d}").Named(column.ColumnName);
            }
            else if (column.ColumnName == "ABRID" || column.ColumnName == "LastName")
            {
                columns.Add(model => model.ItemArray[column.Ordinal]).Titled(column.ColumnName).Sortable(true).Filterable(true).Named(column.ColumnName);
            }
            else
            {
                columns.Add(model => model.ItemArray[column.Ordinal]).Titled(column.ColumnName).Sortable(true).Filterable(true).Named(column.ColumnName);
            }
        }
    })
    .Empty("No candidates found")
    .Css("css-classes")
    .AppendCss("table-hover small text-center")
    .Filterable()
    .Pageable(pager =>
    {
        pager.PageSizes.Clear();
        pager.CurrentPage = 1;
        pager.RowsPerPage = 25;
        pager.CssClasses = "proctor-dashboard-pager";
    })
)
```
and the table looks like this;
![image](https://user-images.githubusercontent.com/38762565/59307792-1ccf4d00-8c54-11e9-8e1d-d8e6d332738d.png)

**Comment by Muchiachio** [comment]
What is your column data type? You can stop on `140` to see if it got mapped to any known filters.
My guess is that they are objects and there are no filters for an object type.

**Comment by jswafford1977** [comment]
![image](https://user-images.githubusercontent.com/38762565/59374920-db957680-8d01-11e9-80a8-60e7cd9fa260.png)
Appears the filter has no name. The column types are {string, string, string, date, and then x number of int columns}

**Comment by Muchiachio** [comment]
I don't think that datatables array can have static type in an array, grid doesn't check dynamic types of the first row.

**Comment by jswafford1977** [comment]
Line 140 in mvc-grid.js does not match your link.
![image](https://user-images.githubusercontent.com/38762565/59375140-5e1e3600-8d02-11e9-8e69-433e88bc8d66.png)

**Comment by jswafford1977** [comment]
is there a .FilterName() method i can use to set the Type?

**Comment by jswafford1977** [comment]
Ok, i used, .FilteredAs(column.ColumnName) and the filters are now being named, but the array of filters appears empty, see below.
![image](https://user-images.githubusercontent.com/38762565/59375909-f79a1780-8d03-11e9-9a30-4ed11b697fc7.png)

**Comment by Muchiachio** [comment]
It has to be a filter name, please check my initial comment.

**Comment by jswafford1977** [comment]
Something like this?
![image](https://user-images.githubusercontent.com/38762565/59376364-c66e1700-8d04-11e9-8cbf-5c45387dcbb4.png)

**Comment by Muchiachio** [comment]
Yes.

**Comment by jswafford1977** [comment]
Thank you, the filter popup now appears without JS error. It does not however apply the filter after clicking the green submit button. No js error is thrown.
![image](https://user-images.githubusercontent.com/38762565/59376696-780d4800-8d05-11e9-97e6-60da2fd1ee81.png)

**Comment by jswafford1977** [comment]
This may be an implementation error on my end. The filters are empty even though the values are in the URL

**Comment by Muchiachio** [comment]
Looks like it didn't bound, but I'm not sure why.

**Comment by jswafford1977** [comment]
it appears to step through the applyFilter() method just fine. It has the filter (firstName="lisa") defined. Interestingly after grid.reload() it appears the whole page is reloaded, not just the _PartialView which contains the Grid

![image](https://user-images.githubusercontent.com/38762565/59377985-2dd99600-8d08-11e9-8d77-ec7b95efbf9b.png)

**Comment by jswafford1977** [comment]
the grid.query = "FirstName-contains=Lisa&module-assignment-grid-LastName-contains=lisa"

**Comment by Muchiachio** [comment]
Whole page is reloaded because it's not an ajax grid, it doesn't get bound on server side for some reason.

**Comment by jswafford1977** [comment]
sorry, the grid.query = "module-assignment-grid-FirstName-contains=lisa"
i had bad values in my url the first time i got that for you.

**Comment by Muchiachio** [comment]
So it works?

**Comment by jswafford1977** [comment]
no

**Comment by jswafford1977** [comment]
still not bound

**Comment by jswafford1977** [comment]
but the url appears correct now (after I named the grid.
https://localhost:44301/Proctor/ModuleAssignments?module-assignment-grid-FirstName-contains=lisa

**Comment by jswafford1977** [comment]
<div class="mvc-grid" data-name="module-assignment-grid" data-filter-mode="ExcelRow" data-source-url="">
    <table class="css-classes table-hover small text-center">
        <thead>
        <tr class="mvc-grid-headers ">
<th class="filterable sortable"
                    data-name="FirstName"
                    data-filter="True"
                    data-filter-name="text"
                    data-filter-multi=""
                    data-filter-default-method=""
                    data-filter-first-method=""
                    data-filter-first-value=""
                    data-filter-operator=""
                    data-filter-second-method=""
                    data-filter-second-value=""
                    data-sort="True"
                    data-sort-order=""
                    data-sort-first="">
                            <span class="mvc-grid-header-title ">FirstName</span>
                        <select class="mvc-grid-options">
                        </select>
                        <button type="button" class="mvc-grid-filter "></button>
                </th>

**Comment by jswafford1977** [comment]
well... i didnt think that would encode the html
was trying to send the html being written to you

**Comment by neman** [comment]
You should maybe open slack or gitter channel for suport like this :)

**Comment by Muchiachio** [comment]
Or can I force people to read contribution and ask for repro project :)

**Comment by jswafford1977** [comment]
to be fair, I did read contribution.md and investigate down to the point where i was at an undocumented issue. .FilteredAs("text"); does not appear in http://mvc6-grid.azurewebsites.net/ so I could not have discovered it on my own. As for the binding issue. I guess I need more investigation and comparison between my other existing implementations. This thread was a concern with a js error on filters which were not strongly typed in a DataTable. You can close this if you so choose.

**Comment by Muchiachio** [comment]
I remembered why it doesn't work, it's because your data is still an object and linq can't filter that without explicit cast, it would look similar to this:
```C#
table.Rows.Cast<DataRow>().Where(row => (row["name"] as String).Contains("test"));
```
but grid doesn't do that, what I was suggesting people to do before is just to use `.ToString` on the expression
``` C#
@model DataTable

@(Html
    .Grid(Model.Rows.Cast<DataRow>())
    .Build(columns =>
    {
        foreach (DataColumn column in Model.Columns)
        {
            columns.Add(model => model[column].ToString()).Filterable(true)
                .FilteredAs("text").Named(column.ColumnName).Titled(column.Caption);
        }
    })
)
```
I will add an example on the docs I guess.

**Comment by jswafford1977** [comment]
Success! Thank you @Muchiachio for continuing to support me on this. 
Issue 1: Filter div would not open on Grid populated by DataTable.AsEnumerable()
Resolution: DataTable columns are not strongly typed and you must pass in a FilteredAs().
Example: columns.Add(model => model.ItemArray[column.Ordinal]).Titled(column.ColumnName).Formatted("{0:d}").Named(column.ColumnName).FilteredAs("date");
Issue 2: Attempting to filter on data from a dynamic source can fail to bind the grid if the item is an object instead of a string.
Resolution: values passed to grid can call ToString() to cast the object to a string for filtering purposes.
Example: columns.Add(model => model.ItemArray[column.Ordinal].ToString())

Again, thank you for all of your help.

**Comment by Bitz** [comment]
Hey,

I have created https://github.com/Bitz/ReportingTest

The format handling is being done in: https://github.com/Bitz/ReportingTest/blob/master/GridTest/Classes.cs#L8

Please let me know if I can explain anything to clarify the purpose of the code.

You should be able to run the project as is and it will show the issue in it's current state:

You can sort successfully, but filtering on the columns that have filtering enabled causes nothing to happen. (Presumably because at this time the columns are considered objects and not strings). I think the expected behaviour should be filtering should respect -some- kind of typing.

**Comment by Muchiachio** [comment]
It's because your columns have [object values](https://github.com/Bitz/ReportingTest/blob/master/GridTest/Classes.cs#L57-L64) and grid can't do `Object.Contains("something")`.
I'm guessing you used object one because current extensions don't support the lowest needed interfaces to be used like `IGridColumn`. I will try to fix that for next release, for now you can use
`IGridColumn thisColumn;` and set filtering and sorting by hand `thisColumn.Filter.IsEnabled = true;`.

**Comment by Bitz** [comment]
Thank you! Generic implementation works for text strings.
It does mean I lose access to `UsingFilterOptions()` and filtering won't work for numerics, but it is sufficient workaround for text :)

**Comment by Muchiachio** [comment]
`columns.Add` always creates a generic `IGridColumn<T, TValue>` instance, it's just that you need to cast it or introduce a new local variable to use those extensions.

**Comment by Bitz** [comment]
Great, thanks!

As you said, I cast the IGridColumn like so:
` ((IGridColumn<DataRow, string>)thisColumn).UsingFilterOptions();`
(You will need to cast your type appropriately, in my case, string is what I needed) 
And the options work! Thanks for your help!
