### ISSUE TITLE
MVC6.Grid has moved to version 5.0

### ISSUE THREAD

**Issue by gkfischer** [NonFactors/MVC6.Grid#201]
Is there any documentation available what changed or was added to the version. Thanks for the effort of building and mantaining this by the way.

**Comment by Muchiachio** [comment]
[Release notes](https://github.com/NonFactors/MVC6.Grid/releases/tag/v5.0.0) have a list of what has been changed.

Code wise, the main breaking changes were renames. If you have something that is not compiling and you don't know how to replace it, you can always check the changes on the [documentation site](https://github.com/NonFactors/MVC6.Grid.Web/commit/05cadf0553ebfe85af8512dbc42cbe99f49a1e69).

For example if you used `.WithFilterOptions` and it doesn't compile anymore, you can ctrl+f `.WithFilterOptions` to find that it was changed to `.UsingFilterOptions` etc.

**Comment by gkfischer** [comment]
I was looking for these but couldn't find them. Thanks for poiniting me in the right direction.
