### ISSUE TITLE
Pager totalrows

### ISSUE THREAD

**Issue by maspr** [NonFactors/MVC6.Grid#203]
In new version, Pager ignores TotalRows in .Pageable()
I have server paging that returns only a subset of rows. Until last version it worked fine with given grid properties. 
Now Pager ignores TotalRows value and displays only one button.  
GridProcessorType.Manual that fixed this issue does not exist anymore. 
Any solutions?

**Comment by Muchiachio** [comment]
http://mvc6-grid.azurewebsites.net/Grid/ManualProcessing

**Comment by maspr** [comment]
oops! I missed that. Thanks that's great.
