### ISSUE TITLE
Multi-column sort

### ISSUE THREAD

**Issue by M-A-R-K-13** [NonFactors/MVC6.Grid#204]
Is it possible to sort more than one column at a time? For example: First sort column x, then column y.

**Comment by Muchiachio** [comment]
No, only one column sort is possible.

**Comment by M-A-R-K-13** [comment]
Thanks for the quick reply. I think this could be a nice feature for a future release. I really like MVC6.Grid. Many thanks for the fantastic work.

**Comment by Muchiachio** [comment]
Yes it's a needed feature sometimes, but it's hard to add with the way grid is implemented now :frowning_face:
Because every grid column is processing data on it's own, without knowing anything about other columns or the order they should be executing in.

**Comment by M-A-R-K-13** [comment]
Thanks for elaborating on this issue. I would love to assist. But unfortunately, I am too much of a beginner. I would mess up your code.

**Comment by Muchiachio** [comment]
Well it would require a lot of changes so I'm not doing this for now, but keeping it in backlog.
