### ISSUE TITLE
Any way to use async in RenderedAs

### ISSUE THREAD

**Issue by jmalczak** [NonFactors/MVC6.Grid#205]
Hi

Thanks for the grid, we use it all the time and we often use RenderedAs with Html.Partial in columns. Is there a way to use Html.PartialAsync in RenderedAs? We have plenty of warnings like this when using Partial:

  Index.cshtml(42, 55): [MVC1000] Use of IHtmlHelper.Partial may result in application deadlocks. Consider using <partial> Tag Helper or IHtmlHelper.PartialAsync.

Thanks

**Comment by Muchiachio** [comment]
Currently no, you can avoid warning with an extension which does the same as synchronous partial.
```C#
public static IGridColumn<T, TValue> RenderedAs<T, TValue>(this IGridColumn<T, TValue> column, Func<T, Task<Object>> value)
{
    column.RenderValue = (t, i) => value(t).GetAwaiter().GetResult();

    return column;
}
```
and then use it in the grid
```C#
columns.Add().RenderedAs(async model => await Html.PartialAsync("_IdPartial", model.Id));
```
