### ISSUE TITLE
MVC.Grid and Bootstrap

### ISSUE THREAD

**Issue by M-A-R-K-13** [NonFactors/MVC6.Grid#206]
Any plans to make MVC.Grid Bootstrap compatible? I know it is supposed to be independent. On the other hand, I can imagine many users would appreciate a compatible version since Bootstrap is the default for ASP.NET Core Web applications.

I created a Bootstrap version of the pager partial view:

![MVC_Grid_pager_Bootstrap](https://user-images.githubusercontent.com/31850055/60738627-4895d800-9f5f-11e9-8594-6b9351262dfc.png)

I am happy to share the code. I also managed to modify “mvc-grid.css” to display the table correctly. Unfortunately, I am not capable of modifying filter controls and pop-ups.

**Comment by Muchiachio** [comment]
Why it's not compatible though? I made styling feel like bootstrap, previous versions even used bootstrap and jquery classes, but it just didn't scale well if you go outside bootstrap/jquery world :(

**Comment by M-A-R-K-13** [comment]
There are Bootstrap classes that seem to be overriden, for example:

- table-sm: Size remains regular.
- table-dark: Table header remains light.
- Also, input, select and button controls do not share Bootstrap style.

**Comment by Muchiachio** [comment]
Well achieving perfect compatibility might be near impossible. I was on various sides before going no dep.
- you use bootstrap and grid uses bootstrap, awesome, until bootstrap increases major version
- you use foundation, which reuses same class names, then it doesn't look like grid anymore
- you don't use styling toolkit, then you either have black and white grid or semi styled one

Same with jquery, if you don't use jquery you have to include 10k+ loc file just to use the grid. I even had jquery ui integrations in place in earlier version which would add even more code projects don't use.

**Comment by M-A-R-K-13** [comment]
Thanks for your explanations, I think your choice is very understandable. On the other hand, there is a lot to win with Bootstrap:

- In addition to regular size tables there are also compact size tables. That’s an advantage in cases when regular size tables won’t fit.
- You can change the overall appearance of your application simply by applying a Bootswatch theme or by modifying your Bootstrap CSS. That’s a powerful tool to respond to user preferences.

I wonder how Datatables solved the issue. By default, there is an independent stylesheet. But there is also a Bootstrap wrapper. Maybe it’s possible to make MVC.Grid more tolerant? I noticed that it helps to remove these lines from “mvc-grid.css”:

```
tbody tr:nth-of-type(odd) {
    background-color: rgba(0, 0, 0, 0.05);
}

.mvc-grid th,
.mvc-grid td {
    border: 1px solid #dee2e6;
    padding: 0.75em;
}

background-color: #f7f7f7; /* section: .mvc-grid th */
```

Then you can style your MVC.Grid like so: `.Css("table table-striped table-sm")` The result is quite nice as long as you don’t activate filtering. Then input and button controls overlap. Is it possible to style these elements in a more responsive way so that their widths scale according to what’s going on around them?

**Comment by Muchiachio** [comment]
I can lower some of the selector specificity, but not all for example `.table-dark` just puts a background on table instead of table rows, but other rules could be lowered so they can be overridden by bootstrap.

It's not as simple as removing it. It takes a lot of time to make compatibility between css tooling, for example just removing above rules results in a table like this. I don't think it would "sell" for new users :)

![image](https://user-images.githubusercontent.com/6647444/60756719-c8787c80-a009-11e9-8e02-d8ba25c08dc7.png)

Using `.Css("table table-striped table-sm")` didn't look as bad, I'm not sure why you got different results?
![image](https://user-images.githubusercontent.com/6647444/60756763-45a3f180-a00a-11e9-8340-3c4e255bf696.png)

**Comment by M-A-R-K-13** [comment]
I agree. Removing the lines I was specifying will not improve MVC.Grid for general usage. It is just my personal work-around to allow Bootstrap to shine through.

Your screenshot indicates that “table-sm” is working in your project. In my project, I need to modify “mvc-grid.css” to allow “table-sm” to work. I wonder why.

Still, there are issues visible in your screenshot:

- Bootstrap tables should not have borders, unless you specify “table-bordered”.
- Table headers should not have background colour. It does not fit the striped colours and looks out of place when using a theme with dark background.
- First and last examples show oversized rows due to large input fields.

Nevertheless, thanks for digging into this. I think it would be nice if Bootstrap tolerance could be improved.

**Comment by Muchiachio** [comment]
Tried lowering current rules, but couldn't get any feasible results. Because bootstrap uses very generic specificity `0-1-0` or even `0-0-1`. So I will be leaving it as is for now, sorry.
