### ISSUE TITLE
rowclick on Ajax Grid stopped working after upgrade

### ISSUE THREAD

**Issue by Mario-HL-Duarte** [NonFactors/MVC6.Grid#209]
I upgraded MvcGrid to version 5.0 and after that my AjaxGrid stopped working.
I'm looking at the documentation but I do not find anything about it.
Could you help me by pointing out where this is documented?

**Comment by Muchiachio** [comment]
Did you follow newest examples and it didn't work?

**Comment by Mario-HL-Duarte** [comment]
I managed to make it work.
I used jQuery to add the rowclick event.
addEventListener was not working for the Ajax grid.

            [].forEach.call(document.getElementsByClassName('mvc-grid'), function (element) {
               new MvcGrid(element);
            });

        $(document).ready(function () {
            $('.mvc-grid').on('rowclick', function (row) {
                console.log(row.target.dataset.id);
            });
        });
