### ISSUE TITLE
how to access pager and grid properties same as all item Count,Next Caption

### ISSUE THREAD

**Issue by sajadghobadi** [NonFactors/MVC6.Grid#210]
@Muchiachio  thanks for your nice grid component, its very perfect and useful .
i  need to show item count on page after and before filtering grid. and also override some pager button caption .
for example : 
```
 
var GridInstance =  @(Html
      .Grid(Model.ContractPermissions)
      .Build(columns =>
      {
          columns.Add(model => $"<a data-id=\"{model.Id}\"><i class='material-icons black-text'>remove_red_eye</i></button>").Encoded(false).Title = "مشاهده مجوز";
          columns.Add(model => model.Subject);
          columns.Add(model =>  model.Price).RenderedAs(model=>StringExtensions.ToNumeric(model.Price));
          columns.Add(model => model.Person.FullName).Title = "طرف دوم";
      })
      .Empty("No data found")
      .Id("my-ajax-grid")
      .Pageable(pager =>
      {
          pager.TotalRows = Model.ContractPermissions.Count;
          pager.PagesToDisplay = 10000;
          pager.RowsPerPage = 100;

          pager.nextButton.Caption = "next";

      })
      .Filterable(GridFilterType.Double)
      .Sortable()
                          )

<input value="@GridInstance.Count" id="ccount"/>

```
my require is  below lines 
`          pager.nextButton.Caption = "next";`
`<input value="@GridInstance.Count" id="ccount"/>`
`

**Comment by Muchiachio** [comment]
You can create your own version of a pager partial and pass it to `Pageable`
```C#
.Pageable(pager => pager.PartialViewName = "_MyCustomPager")
```

**Comment by sajadghobadi** [comment]
how to access properties same as item count outside from component in host page.
for example in index page that call indexGrid by @Html.AjaxGrid i need all grid item count.

**Comment by Muchiachio** [comment]
Pager partial uses `GridPager` as a model which has variouses properties like `.TotalRows` and so on.
