### ISSUE TITLE
pass filters value to back code 

### ISSUE THREAD

**Issue by sajadghobadi** [NonFactors/MVC6.Grid#211]
hi,
i use this component in razor page application
i want to catch use input filter value in OnGet to handle to some code.
or catch user clicked row in OnPost of IndexGrid page.
thanks for your attention.

**Comment by Muchiachio** [comment]
Filter values are passed in the query, so you can access them from there is you need to.
Grid has a custom [rowclick](http://mvc6-grid.azurewebsites.net/Javascript/RowClicked) event or you can just bind your own javascript handlers where needed.
