### ISSUE TITLE
DropDownList

### ISSUE THREAD

**Issue by dkinga1785** [NonFactors/MVC6.Grid#212]
Is this how I add a column to the grid to create a dropdown

grid.Columns.Add(model => model.Urgencys).Encoded(false).Named("Urgencys")
                .RenderedAs(Html.DropDownListFor(model => model.Urgencys, new SelectList(model.Urgencys, "Value", "Text"), "--select--", new { @class = "form-control" }));

**Comment by Muchiachio** [comment]
Well, try and see if it works :)
There are examples on how to use html helper [here](http://mvc6-grid.azurewebsites.net/Column/Encoding), replacing it to dropdown should work.

**Comment by dkinga1785** [comment]
![Capture](https://user-images.githubusercontent.com/19777914/61797347-d9d4cd80-adec-11e9-900a-43cb6b196f93.PNG)

**Comment by dkinga1785** [comment]
it just renders the text

**Comment by neman** [comment]
Did you even tried to read the docs from page that @Muchiachio linked here

> There are examples on how to use html helper [here](http://mvc6-grid.azurewebsites.net/Column/Encoding), replacing it to dropdown should work.

Looks like you did not, because you are doing it wrong. 

```c#
@model IEnumerable<Person>

@(Html
    .Grid(Model)
    .Build(columns =>
    {
        columns.Add(model => Html.CheckBox("Person_" + model.Id));
        columns.Add(model => $"<button data-id=\"{model.Id}\">Edit</button>").Encoded(false);

        columns.Add(model => model.Name).Titled("Name");
        columns.Add(model => model.Surname).Titled("Surname");
        columns.Add(model => model.MaritalStatus).Titled("Marital status");

        columns.Add(model => model.Age).Titled("Encoded age").RenderedAs(model => "<span>" + model.Age + "</span>");
        columns.Add(model => model.Age).Titled("Not encoded age").Encoded(false).RenderedAs(model => "<span style='color: #CC4444'>" + model.Age + "</span>");
        columns.Add(model => model.Birthday).Titled("Birthday").Formatted("{0:d}");
        columns.Add(model => model.IsWorking).Titled("Employed");
    })
)```

**Comment by dkinga1785** [comment]
I'm creating the grid columns at the controller level.  I see that the examples are at the view level.  But since I would like to use the grid excel export the columns are created within the controller.

**Comment by dkinga1785** [comment]
If I hard code the <select> values it displays.  I want to use Razor syntax. 

grid.Columns.Add(model => model.Urgency).Encoded(false).Named("Urgencys")
                .RenderedAs(model => "<select class=\"form-control\" id=\"Urgency\" name=\"Urgency\"> 
               <option value = \"\" > --select-- </option ><option value=\"High\" >High</option><option 
               value = \"Low\" >Low</option><option value= \"Normal\" >Normal</option></select>");

 grid.Columns.Add(model => model.Urgency).Encoded(true).Named("Urgencys")
     .RenderedAs(model => "@Html.DropDownListFor(model => model.Urgencys, new 
     SelectList(model.Urgencys, \"Value\", \"Text\"), \"--select--\", new { @Class = \"form-control\" })");

**Comment by dkinga1785** [comment]
![Capture](https://user-images.githubusercontent.com/19777914/61808552-3e018c80-ae01-11e9-99db-166a5bb8d31e.PNG)

**Comment by dkinga1785** [comment]
I want the drop down populated from my database and auto select the inserted value from the record.

**Comment by neman** [comment]
The functionality you mentioned is described on the previously mention docs page. Specifically this part of code:

```c#
columns.Add(model => Html.CheckBox("Person_" + model.Id));
columns.Add(model => $"<button data-id=\"{model.Id}\">Edit</button>").Encoded(false); 
```

Also, it would be nice if you could write your code formatted using markdown and to edit your question, instead of adding multiple posts one after another. It is the common practice here at github and also a good behavior how you can attract more users to answer your question. The way you wrote your questions is more spam alike.
