### ISSUE TITLE
Filter in mobile (Android - Chrome)

### ISSUE THREAD

**Issue by estela72** [NonFactors/MVC6.Grid#215]
Hi!

I have a web application using NonFactors.MVC6 (version 4.1.1). When the application is executed in Android with chrome, when the column filter dialog box is opened and you want to write sth, the dialog box is closed. 
Do you know what I'm doing wrong?

Thanks!

**Comment by Muchiachio** [comment]
Yes, it was fixed in later versions.

**Comment by estela72** [comment]
Ok, then I need to update to 5.0.0. Is this version the last one?

Thanks!

**Comment by Muchiachio** [comment]
Yes, 5th is the latest one.
