### ISSUE TITLE
Displaying or passing the values in Grid from ViewBag not working.

### ISSUE THREAD

**Issue by saurabhnachankar** [NonFactors/MVC6.Grid#217]
Trying to pass some values from ViewBag.

It gives following error : 

> An error occurred during the compilation of a resource required to process this request. Please review the following specific error details and modify your source code appropriately.
> D:\ErpOneCore\Views\Voucher\_index1.cshtml
> 
> An expression tree may not contain a dynamic operation
> 
> `columns.Add(model => Html.ActionLink("Details", "Details1", new { id = model.id, mainid=**ViewBag.data.id** })).Titled("Details");`

**Comment by Muchiachio** [comment]
Is this the error of the grid though? :)

**Comment by saurabhnachankar** [comment]
Yes

**Comment by Muchiachio** [comment]
Sorry, but I can't find the code which checks the expression for dynamic usage and throws `An expression tree may not contain a dynamic operation`, can you link me in github?
