### ISSUE TITLE
Support RTL

### ISSUE THREAD

**Issue by KiarashS** [NonFactors/MVC6.Grid#218]
Hi there,

First, Very thanks for MVC6.Grid.
Is there any support for `RTL`? if No, Please support `RTL`!

**Comment by Muchiachio** [comment]
You should be a able to add few css rules to make it rtl?
Or there are some structural changes needed in the grid?

**Comment by KiarashS** [comment]
@Muchiachio I will test it.

**Comment by tareq2** [comment]
> Or there are some structural changes needed in the grid?
I think the problem is with the class **text-left** you need to remove it from the cells if the aligment is not specified 
ex : 
` columns.AddProperty(model => model.Id).Titled("id");`
will produce 
`<td class="text-left">id</td>`

and it should be 
`<td>id</td>`

**Comment by Muchiachio** [comment]
It's because you are using template's .`AddProperty` instead of a raw grid's `.Add` @tareq2.

**Comment by tareq2** [comment]
Just this thing which i have noticed in the RTL and everything else is working as expected.
