### ISSUE TITLE
ajax- export table

### ISSUE THREAD

**Issue by razhir** [NonFactors/MVC6.Grid#219]
first thanks for this  great work
 is there way to export table to excel without refreshing the page?(using ajax)

**Comment by Muchiachio** [comment]
Current export example doesn't refresh the page (because of download), you just need to get query from the grid instance.
```JS
var query = new MvcGrid(<any wanted grid element>).query.toString();
```

**Comment by razhir** [comment]
when export to excel doesn't refresh the page but all action such as (pagination , sorting ,filtering )..refresh the page,  how to use the grid with out refreshing when add (export to excel)

**Comment by Muchiachio** [comment]
Use [ajax grid](http://mvc6-grid.azurewebsites.net/Grid/Ajax) configuration?

**Comment by razhir** [comment]
thanks it works by using ajax configuration....but has a fix 
this tag not updated when using ajax configuration (always export all rows in the database not export only filtered) but if move to end the partial view  its updated

**Comment by razhir** [comment]
thanks it works by using ajax configuration....but has a fix
`<a href="@(Url.Action("ExportIndexPurchase") + ViewContext.HttpContext.Request.QueryString)" >Export to excel`
this tag not updated when using ajax configuration (always export all rows in the database not export only filtered) but if move to end the partial view its worked... export only rows that filtered 
but this tag duplicated when perform (filter,sort,..)
