### ISSUE TITLE
Changing filters, sorting etc reloads the whole page even when it's a partial view

### ISSUE THREAD

**Issue by Jeffrey-Bijkerk** [NonFactors/MVC6.Grid#221]
Hi,

I really like your product but I am have a problem with filtering, setting a different page etc. My grid responds to a Start and enddate on the main form this works perfectly using the onchange event. But... when I press the sort or filter button then the page gets a full reload although it's a partialview so my start and enddate are reset to the initial state.

Is there a solution for this. Code:"

**View:**
@model Abnamro.Alm.FTPPortal.GUI.Areas.Processes.Models.ProcessOverviewModel
@{
    Layout = "~/Views/Shared/_LayoutWithHeader.cshtml";
}

<div class="container">
    <div class="row form-group">
        <div class="col-md-1">
            Period
        </div>
        <div class="col-md-2">
            @Html.TextBoxFor(m => m.StartDate, "{0:dd-MM-yyyy}", new { @class = "form-control datepicker", placeholder = "Select date", id = "StartDate", onchange = "UpdateScreen();" })
        </div>
        till
        <div class="col-md-2">
            @Html.TextBoxFor(m => m.EndDate, "{0:dd-MM-yyyy}", new { @class = "form-control datepicker", placeholder = "Select date", id = "EndDate" })
        </div>

    </div>
</div>
<br />
<div id="grid">
    @{Html.RenderPartial("_ProcessOverview", Model);}
</div>

<script type="text/javascript">

    $(function () { // will trigger when the document is ready
        $('.datepicker').datepicker({
            format: "dd-mm-yyyy"
        });
    });
    function UpdateScreen() {
        var datevarStart = $("#StartDate").val();
        var datevarEnd = $("#EndDate").val();
        @*var link = '@Url.Action("_ProcessOverview", new {startDate = "abc", endDate = "bcd" })';*@
        var link =
            '@Url.Action("_ProcessOverview", "ProcessOverview", new { startDate = "_startdate_", endDate = "_enddate_" })'
                .replace('_startdate_', datevarStart).replace('_enddate_', datevarEnd).replace('&amp;', '&');
        $("#grid").load(link);
    }

</script>

**PartialView**
@using NonFactors.Mvc.Grid;
@model Abnamro.Alm.FTPPortal.GUI.Areas.Processes.Models.ProcessOverviewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@(Html
    .Grid(Model.Processes)
    .Build(columns =>
    {
        columns.Add(c => c.ProcessId);
        columns.Add(c => c.ProcessName).Titled("Processtype").UsingFilterOptions(new[]
        {
            new SelectListItem(),
            new SelectListItem() {Value = "FTPBooking", Text = "FTPBooking"},
            new SelectListItem() {Value = "FTP Validation Report", Text = "FTP Validation Report"},
            new SelectListItem() {Value = "Scorecard run", Text = "Scorecard run"}
        });
        columns.Add(c => c.ProcessStartTime).Formatted("{0:dd-MM-yyyy HH:MM:ss}").Titled("Start time");
        columns.Add(c => c.ProcessEndTime).Formatted("{0:dd-MM-yyyy HH:MM:ss}").Titled("End time");
        columns.Add(c => c.ProcessDuration).Sortable(true).Titled("Duration");
        columns.Add(c => c.ProcessStatus).Titled("Status").Filterable(true);
    })
    .Empty("No data found")
    .Id("MortgageRatesGrid")
    .Filterable()
    .Sortable()
    )

**Controller**
        public async Task<ActionResult> ProcessOverview()
        {
            return View(ProcessResult("2019-01-01", DateTime.Now.ToString("dd-MM-yyyy")));
        }

        [HttpGet]
        public async Task<ActionResult> _ProcessOverview(string startDate, string endDate)
        {
            return PartialView(ProcessResult(startDate, endDate));
        }

**Comment by Muchiachio** [comment]
Are you using [ajax grid](https://mvc6-grid.azurewebsites.net/Grid/Ajax) which only refreshes the grid?

**Comment by Jeffrey-Bijkerk** [comment]
Okay so I changed it to the following and then it works. But.... I don't want to do a page submit I only want the grid to be refreshed using the action

@using NonFactors.Mvc.Grid
@{
    Layout = "~/Views/Shared/_LayoutWithHeader.cshtml";
}

@using (Html.BeginForm("ProcessOverview", "ProcessOverview", FormMethod.Post))
{
    <div class="container">
        <div class="row form-group">
            <div class="col-md-1">
                Period
            </div>
            <div class="col-md-2">
                @Html.TextBoxFor(m => m.StartDate, "{0:dd-MM-yyyy}", new {@class = "form-control datepicker", id = "StartDate", onchange = "this.form.submit();"})
            </div>
            till
            <div class="col-md-2">
                @Html.TextBoxFor(m => m.EndDate, "{0:dd-MM-yyyy}", new {@class = "form-control datepicker", id = "EndDate", onchange = "this.form.submit();"})
            </div>

        </div>
    </div>
    <br/>
}
@Html.AjaxGrid(@Url.Action("_ProcessOverview", "ProcessOverview", new { startDate = Model.StartDate.ToString("dd-MM-yyyy"), endDate = Model.EndDate.ToString("dd-MM-yyyy") }))

**Comment by Muchiachio** [comment]
If you want to refresh the grid using different query parameters you can use [reload method](https://mvc6-grid.azurewebsites.net/Javascript/RequestType).

**Comment by Jeffrey-Bijkerk** [comment]
How do I do that? I tried this but it didn't refresh the grid. Loading the data is done by parameters given to the UrlAction as you can see.

**Comment by Muchiachio** [comment]
It should have refreshed the grid, is something not working the grid code?

**Comment by Jeffrey-Bijkerk** [comment]
I am getting this error: mvc-grid.js:291 POST http://localhost:5932/Processes/ProcessOverview/_ProcessOverview?startDate=01-01-2019&endDate=11-10-2019&_=1570803612145 404 (Not Found)

**Comment by Jeffrey-Bijkerk** [comment]
I don't understand the part after 11-10-2019

**Comment by Jeffrey-Bijkerk** [comment]
Code I implemented is:
     function UpdateScreen() {
        var grid = new MvcGrid(document.querySelector('.mvc-grid'));
        grid.requestType = 'post'; // defaults to get
        grid.reload();
    }
on put this in the onchange event on my start and enddate

**Comment by Muchiachio** [comment]
Underscore part is just a cache buster. Your controller is most likely serving `get` requests, so don't use request type `post` to not get not founds.

**Comment by Jeffrey-Bijkerk** [comment]
I am getting the 404 but when I click the link it's working and can be found. Although the selection is also not valid because I am taking it from the model which isn't updated because no post has been done

**Comment by Jeffrey-Bijkerk** [comment]
OK changing it to "get" works but now I have a new problem. If I change the date the refresh is done but because I am not posting it anymore it now doesn't update the model so I can't use the Model.Startdate and Model.Enddate for the @Url.Action... do you have ideas for that?

**Comment by Muchiachio** [comment]
`Url.Action` is no longer needed after ajax grid is initialized, because current grid source url is preserved.

**Comment by Jeffrey-Bijkerk** [comment]
Yes but when I update the Start and enddate in my view I want the data which are available in the grid to be refreshed

**Comment by Jeffrey-Bijkerk** [comment]
So the source url will be updated

**Comment by Muchiachio** [comment]
As I don't see any problem with the grid specified and I don't know how I can help more will close.
