### ISSUE TITLE
Hide/Remove filter options on specific columns 

### ISSUE THREAD

**Issue by Josh-Nicholson** [NonFactors/MVC6.Grid#222]
Is there a way to remove filter options on specific columns?
For example on one column leave it as default, but on the next remove "Contains","Starts with" and "Ends with" so only "Equals" and "Not equals" Remain?

It seems this functionality can be achieved as it is featured in the documentation, but there is no information/code on how to do it.

**With filter options removed:**
![image](https://user-images.githubusercontent.com/9265897/66765945-da897700-eea4-11e9-85b9-1983a696b267.png)

**Default:**
![image](https://user-images.githubusercontent.com/9265897/66765700-651da680-eea4-11e9-9c4e-03565a66d4bb.png)

I've probably missed something, but help would be greatly appreciated.

**Comment by Muchiachio** [comment]
It's only `equals` and `not equals` on enum/bool or other that kind of type columns.
To change it you will have to override string filter, similarly to how it's done on [custom filter example](https://mvc6-grid.azurewebsites.net/Column/CustomFilter).
You will only have to provide your own list of methods.

**Comment by Josh-Nicholson** [comment]
Is there a way I can specify the type of a column to enum?
For example I know one column with always contain 4 variants of a string.

**Comment by Muchiachio** [comment]
Theoretically you can use `.FilteredAs("enum")`, but some grid update might change enum filter popup.

**Comment by Josh-Nicholson** [comment]
Worked like a charm.
Thanks
