### ISSUE TITLE
Reloading ajax grid - reset pager to page 1

### ISSUE THREAD

**Issue by Josh-Nicholson** [NonFactors/MVC6.Grid#223]
Is it possible to recreate/reset the pager of a grid when .reload() is called?

The problem i'm encountering is that a grid needs to keep it's state whilst the user remains on the page.
However, if the user leaves the page and then later comes back, the grid needs to be reloaded.
Currently the reloading works and retrieves new data, but the pager remains on the page the old grid was left on.

Is there a way I can specify a parameter when calling reload to remove and then recreate the pager, or just to reset the existing pager?

**Comment by Muchiachio** [comment]
You can set grid query to match you needs
```JS
var grid = new MvcGrid(document.querySelector('.mvc-grid'));
grid.query.set('page', '0');

grid.reload();
```

**Comment by Josh-Nicholson** [comment]
Thanks for the quick response.
Again, worked like a charm.
Really enjoying your grid controls, keep up the good work.
