### ISSUE TITLE
HttpContext.Request.Headers["X-Requested-With"] == "XMLHttpRequest" Condition not working in .net core 2.2

### ISSUE THREAD

**Issue by amir6mehrabi** [NonFactors/MVC6.Grid#224]
i'm using asp.net core 2.2 mvc and using  Grid with source url for ajax 
`if (HttpContext.Request.Headers["X-Requested-With"] == "XMLHttpRequest") `
is never true in ajax call

**Comment by amir6mehrabi** [comment]
the main problem is that I want an ajax grid.but when I use ajax grid javascript for the popup that is related to the button in grid is not firing.


![Capture](https://user-images.githubusercontent.com/16825335/67337555-ebcf2500-f52f-11e9-8a79-45783f819e53.PNG)


the blue button have an on click jquery method that is not working

**Comment by Muchiachio** [comment]
You should be using `.AjaxGrid` to initialize an ajax grid so it always sends `XMLHttpRequest`.
What `.UsingSourceUrl` does is load the initial grid together with the page for seo and only then switch to ajax. So first request won't have `XMLHttpRequest`, because it loads with default request headers.

**Comment by Muchiachio** [comment]
Your buttons probably not working, because they have to be bound using `Event Delegation`.

**Comment by amir6mehrabi** [comment]
My button works when it's not an ajax grid

**Comment by Muchiachio** [comment]
Yes, because of events not being delegated to a static parent.

**Comment by amir6mehrabi** [comment]
How should i use it?

**Comment by Muchiachio** [comment]
You can find more information about event delegation in this [stackoverflow](https://stackoverflow.com/questions/1687296/what-is-dom-event-delegation/1688293#1688293) answer.

**Comment by amir6mehrabi** [comment]
It works. Thanks a lot <3
