### ISSUE TITLE
grid.request.onload results in empty responseText

### ISSUE THREAD

**Issue by Josh-Nicholson** [NonFactors/MVC6.Grid#227]
I'm currently experencing a problem where MVC6.Grid has stopped working with the latest release of .Net Core 3.

Firstly I had encountered this error "Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.", when trying to pass the partial view to the grid.
To get around this I had to include this line in startup.cs:
`services.Configure<IISServerOptions>(options =>
{
    options.AllowSynchronousIO = true;
});`

This then results in an error in this code:
`grid.request.onload = function () {
if (200 <= grid.request.status && grid.request.status < 400) {
success(grid.request.responseText);
} else if (error) {
error(grid.request.responseText);
}
};`

as it ends up passing an empty success responseText to `grid.startLoading(function (result){ ... }`
which then overwrites the outerHTML with an empty string, so you get an empty grid.

Do you know how to fix this issue?

I'm just using a standard ajax grid, where I'm populating it with data when a button is pressed.

**Comment by Muchiachio** [comment]
Synchronous IO errors will be fixed with https://github.com/aspnet/AspNetCore/issues/15367. Empty result usually means that there was an exception while rendering the view. Is there any exceptions in the error log.

**Comment by Josh-Nicholson** [comment]
Not currently seeing any errors in the log or stack trace. Would using .Net Core 3.1 preview work in the meantime?

**Comment by Muchiachio** [comment]
It works on core3 too, not sure why are you getting empty responses though. Maybe you have a small repro? Because documentation page and our projects are using core3 without problems.

**Comment by Josh-Nicholson** [comment]
Just tried 3.1 and am still getting the Synchronous errors.
It's really weird, my grid implementation was working fine last week.
Not really sure what has changed to cause these errors.

Still no idea why the responseText is empty.
It causes this error afterwards:

Uncaught TypeError: Cannot read property 'classList' of undefined                                 
    at window.location.href (mvc-grid.js:181)
    at XMLHttpRequest.grid.request.onload (mvc-grid.js:283)
mvc-grid.js:181

**Comment by Josh-Nicholson** [comment]
Ah sorry I thought the Synchronous IO fix was in the current preview.
It's actually being published as preview 3, so I'll just wait for that, and hope it fixes my issue.

**Comment by Muchiachio** [comment]
I'm 99 % sure it won't fix your issues. You can try running web project and see it working on core3.

**Comment by Josh-Nicholson** [comment]
Can you tell me what's supposed to be in the grid.request.responseText on a 200 code?

**Comment by Muchiachio** [comment]
Grid content, you can see an example [here](https://mvc6-grid.azurewebsites.net/Grid/Ajax).

**Comment by Josh-Nicholson** [comment]
Is there a way in the meantime that I can get around the SynchronousIO problems without specifiying:
`services.Configure<IISServerOptions>(options =>
            {
                options.AllowSynchronousIO = true;
            });` in startup.cs
I'm almost 100% that is causing the responseText problems.

**Comment by Muchiachio** [comment]
Async IO is caused by an exception in view rendering, which gets swallowed by it. If you can't share a repro or replicate the problem on the web project and don't see any exceptions in the logs then I don't know how more I can help :disappointed:

**Comment by Josh-Nicholson** [comment]
Just created a test repo with the same concept as my application.
Hopefully this helps in diagnosing the problems.
[Test Repo](https://github.com/Josh-Nicholson/TestMVCGridProject)

In the actual application I'm populating the grid with data from a SQL DB.

**Comment by Muchiachio** [comment]
You are getting this exception
```
System.ArgumentException: Value cannot be null or empty. (Parameter 'viewPath')
   at Microsoft.AspNetCore.Mvc.ViewEngines.CompositeViewEngine.GetView(String executingFilePath, String viewPath, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.RenderPartialCoreAsync(String partialViewName, Object model, ViewDataDictionary viewData, TextWriter writer)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.PartialAsync(String partialViewName, Object model, ViewDataDictionary viewData)
   at AspNetCore.Views_Shared_MvcGrid__Grid.ExecuteAsync() in \TestMVCGridProject\Views\Shared\MvcGrid\_Grid.cshtml:line 156
```
Which means you updated grid dll to `5.1.1`, but you are still using `5.0.1` views and static resources which are rarely compatible.

**Comment by Josh-Nicholson** [comment]
Thank you so much.
For future reference, should the view templates and static files update with the nuget package update?
Or should I always replace those files from the new ones available from this repo?

**Comment by Muchiachio** [comment]
They need to be replaced by hand, nuget used to update content in pre core days, but now it can't.

**Comment by Josh-Nicholson** [comment]
Ok, Noted for future updates.
Thank you for being such a big help with this issue!
