### ISSUE TITLE
Pager Options: Top and Bottom and Custom Text?

### ISSUE THREAD

**Issue by firstdivision** [NonFactors/MVC6.Grid#229]
I apologize if this is in the documentation somewhere and I am not seeing it, but are there options for the paging controls to:

- Display them both on the top and bottom of the grid
- Customize the text for the "Page Size" dropdown to indicate that's what it's for?

**Comment by Muchiachio** [comment]
You can customize pager partial and use your own in
```C#
.Pageable(pager =>
{
    pager.PartialViewName = "_MyCustomPager";
})
```
