### ISSUE TITLE
Unable to pass 'query' in the 'reload' request

### ISSUE THREAD

**Issue by jjkcharles** [NonFactors/MVC6.Grid#23]
I am trying to pass certain data to my controller (through query string) when reloading the Grid, and tried to pass 'query' value in Options to override the default value. But, looks like mvc-grid.js's 'set' doesn't copy the 'query' value from 'options' to the newly instantiated grid. Is it by design, not to copy the 'query' value or is it an issue. (Sample code below)

`$('.mvc-grid').mvcgrid(
{
    reload: true,
    query: 'myQueryKey=value'
});`

Also, is there any better way to pass additional data from grid to controller when reloading/performing any other actions (paging/sorting etc...)?

**Comment by Muchiachio** [comment]
This call only works once and only if called before grid is actually initialized.
[Here's and example of how to do a refresh after it's been initialized](http://mvc-grid.azurewebsites.net/Grid/GlobalSearch).

If you want to intercept every reload, you can use `reloadStarted` event.
```JS
$('.mvc-grid').mvcgrid({
    reloadStarted: function (grid) {
        grid.query = 'myQueryKey=value';
    }
});
```
I do like your approach of passing query as a grid option without the need to use grid data.
I will check if developer experience can be improved here.

**Comment by jjkcharles** [comment]
Thanks for including this and for the samples, somehow missed this one when I scanned across the samples looking for a way to send data back to controller.
