### ISSUE TITLE
Cannot manually set TotalRows

### ISSUE THREAD

**Issue by specialtrevor** [NonFactors/MVC6.Grid#230]
Hi,

Our paging is done through the database reads so we are only returning what we want to return to the browser. In theory we should be able to set TotalRows manually from our database count query, and then the pager should be able to establish the number of pages to facilitate. But due to the way TotalRows is set from the item count we cannot do this.

https://github.com/NonFactors/MVC6.Grid/blob/7e1c09be02cb5ad2e550df1dc3a10f0440e8e2fc/src/Mvc.Grid.Core/Paging/GridPager.cs#L109

Could this be changed to only set it if the TotalRows is zero?

It seems excessive to have to write our own pager routine when this one is so close to perfect :)

I believe this is the same problem as raised in Issue 58 (https://github.com/NonFactors/MVC6.Grid/issues/58), but I thought this would be a quick solution.

Alternately allow the setting of TotalPages and if that's set don't do the calculations? (less good, but also highly flexible)

Thanks very much

**Comment by Muchiachio** [comment]
Is this perhaps covered in [manual processing](https://mvc6-grid.azurewebsites.net/Grid/ManualProcessing) example, if not what is missing?

**Comment by specialtrevor** [comment]
Thanks for replying. I had missed the link there.

I'd seen issue 58 and 59, and that the changes mentioned in 59 that had been reverted. So I thought the answer to 58 was essentially the solution.

I'd gotten it working in the meantime, but that one line has saved all that extra code. So thanks.
