### ISSUE TITLE
Can I get pager info in footer

### ISSUE THREAD

**Issue by anantjaiswal339** [NonFactors/MVC6.Grid#232]
Hi,

Can we get page info like this : https://www.screencast.com/t/y0EjhsKHQ5E

**Comment by Muchiachio** [comment]
Yes, all this information is available in the pager, you can create your own pager to match your UI.

**Comment by anantjaiswal339** [comment]
Thanks for the quick response.
Do we have any demo for the same.

**Comment by Muchiachio** [comment]
There is no example for the pager, but it's very similar to custom grid partial example.
You configure the pager to use your own partial and just change razor code
```C#
.Pageable(pager =>
{
    pager.PartialViewName = "_MyCustomPager";
})
```

**Comment by anantjaiswal339** [comment]
Could you please let me know, what I'm missing here?

```.Sortable().AppendCss("mvc6-grid-custom table-responsive")
                            .Pageable(pager =>
                            {
                                pager.PartialViewName = "_PagerCustom";
                                pager.TotalRows = 20;
                                pager.RowsPerPage = 3;
                                pager.PagesToDisplay = 3;
                                pager.ShowPageSizes = true;
                            })
                            )
```
Also I have tried with removing  pager property but it didn't called my partial view.

**Comment by Muchiachio** [comment]
If it doesn't crash it probably can't find `_PagerCustom` partial.
Does the same, but in plain `Html.Partial("_PagerCustom")` works?

**Comment by anantjaiswal339** [comment]
Oh yes, it was path issue.
Thanks!
