### ISSUE TITLE
How can we get filter value with specific column while using ajax grid

### ISSUE THREAD

**Issue by anantjaiswal339** [NonFactors/MVC6.Grid#233]
I'm loading grid using ajax and I'm looking for a way to get filter value specifically by column name with applied condition.
I know we can get it by `Request.QueryString`  as in snap but it changed the column name with dash also it will be hard to extract the applied condition as contains, equal etc.
https://www.screencast.com/t/NWD3wBXy0XTO

Actually, the purpose of doing this to use server side filtration.
I'll pass the column name with value and applied condition to procedure.
Thanks in advance!

**Comment by Muchiachio** [comment]
It can only be parsed through query string, you could use a custom model binder to make it more automatic though.

**Comment by anantjaiswal339** [comment]
Do we have any little bit example for custom model binder?
Or a way where I can get something like this in query string : `filterexpressoin = firstname-contains-anant&lastname-contains-test`

**Comment by Muchiachio** [comment]
Custom model binders are document in [docs provided by microsoft](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding).
It's easy to build that from query string is a dictionary, for one key it would be
```C#
String value = key + "-" + Query[key];
```
You can specify any name using `.Named("columnname")` extension, to avoid dashes in column name.

**Comment by anantjaiswal339** [comment]
Okay, thanks I'll try this one.
Are you planning to add some feature in filtering like to get all applied filter in linq/lambda expression or `([firstname] LIKE '%test%') AND ([lastname] LIKE '%app%')`

**Comment by Muchiachio** [comment]
No plans, it's technically available in a custom grid rows implementation, but it seems like you are looking for a hacky way to make the grid work. Maybe it would be better to use some other javascript based grid which just uses an API point you fully control?

**Comment by mehmetkurt** [comment]
## Controller
```
 [HttpGet]
        public async Task<PartialViewResult> List(int? page, int? rows, [ModelBinder(binderType: typeof(MvcGridBinder))]ProductGridSearchFilter productGridSearchFilter)
        {
            var offset = (page - 1 ?? 0) * (rows ?? 24);
            var limit = rows ?? 24;
            // use productGridSearchFilter properties for filters
           return PartialView("_List", model.ToList());
        }
```
## Binder Provider and Binder

``` 
public class MvcGridBinderProvider : IModelBinderProvider
    {
        public IModelBinder GetBinder(ModelBinderProviderContext context)
        {
            if (!typeof(IFilter).IsAssignableFrom(context.Metadata.ModelType))
            {
                return null;
            }

            var binders = new Dictionary<Type, (ModelMetadata, IModelBinder)>();
            var modelMetaData = context.MetadataProvider.GetMetadataForType(typeof(IFilter));
            binders.Add(typeof(IFilter), (modelMetaData, context.CreateBinder(modelMetaData)));

            return new MvcGridBinder(binders);
        }
    }

    public class MvcGridBinder : IModelBinder
    {
        private Dictionary<Type, (ModelMetadata, IModelBinder)> binders;
        public MvcGridBinder(Dictionary<Type, (ModelMetadata, IModelBinder)> binders)
        {
            this.binders = binders;
        }

        public Task BindModelAsync(ModelBindingContext bindingContext)
        {
            if (bindingContext != null)
            {
                // dependency injection
                var model = Activator.CreateInstance(bindingContext.ModelType);
                
                var properties = model.GetType().GetProperties();
                foreach (var property in properties)
                {
                    var gridFilter = new GridFilters();

                    var propertyNameWithPrefix = property.Name.ToLower();
                    var propertyNameArray = propertyNameWithPrefix.Split('-');
                    var method = (propertyNameArray.Length <= 1 ? "equals" : propertyNameArray.LastOrDefault());
                    var originalPropertyName = propertyNameArray.FirstOrDefault();

                    var value = bindingContext.ValueProvider.GetValue(originalPropertyName);
                    if(value.Length > 0)
                    {
                        property.SetValue(model, value.FirstValue);
                    }
                }

                bindingContext.Result = ModelBindingResult.Success(model);
            }

            return Task.CompletedTask;
        }
    }
```

## Register ModelBinderProvider In .Net Core 3.0 Startup.cs

```
  services.AddControllersWithViews(c=> {
                c.ModelBinderProviders.Insert(0, new MvcGridBinderProvider());
            });

```
