### ISSUE TITLE
Filter "Contains" - expression could not be translated to SQL in EF Core 3.0

### ISSUE THREAD

**Issue by DanielStaroscik** [NonFactors/MVC6.Grid#234]
Hi, i spotted another bug in MVC grind running under EF Core 3.0:

```
System.InvalidOperationException: The LINQ expression 'Where<TransparentIdentifier<Contract, Institution>>(
    source: Where<TransparentIdentifier<Contract, Institution>>(
        source: Join<Contract, Institution, Nullable<Guid>, TransparentIdentifier<Contract, Institution>>(
            outer: Where<Contract>(
                source: DbSet<Contract>, 
                predicate: (c) => c.DateFrom <= DateTime.Now.Date && DateTime.Now.Date <= c.DateTo), 
            inner: DbSet<Institution>, 
            outerKeySelector: (c) => Property<Nullable<Guid>>(c, "InstitutionId"), 
            innerKeySelector: (i) => Property<Nullable<Guid>>(i, "Id"), 
            resultSelector: (o, i) => new TransparentIdentifier<Contract, Institution>(
                Outer = o, 
                Inner = i
            )), 
        predicate: (c) => c.Inner.OurInstitutionId == (Unhandled parameter: __SessionService_OurInstitutionId_0)), 
    predicate: (c) => c.Inner.Number != null && c.Inner.Number.ToUpper().Contains("**********"))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync().
```

It would work when change `c.Inner.Number.ToUpper().Contains("**********")` to `EF.Functions.Like(c.Inner.Number, "%***********%")`

**Comment by Muchiachio** [comment]
Don't think there is a number contains filter in the library, because of not translatable functions.
Where did you found it?

**Comment by DanielStaroscik** [comment]
On my grid, Number is a string property and varchar column in sql.
Onother exception was thrown when i used equal filter:
`predicate: (c) => c.Inner.Number != null && c.Inner.Number.ToUpper() == "I/1/OK/05/2018")'`
another solution is remove call to `ToUpper` method because it would npt be translated in EF Core 3.0.

**Comment by Muchiachio** [comment]
Strange, I'm using EF Core 3.0 without a problem, hard to believe that they would introduce a breaking change like untranslatable `.ToUpper` into the library.

**Comment by DanielStaroscik** [comment]
Oh ok I see i have `Unhandled parameter` in previuous line in exception :D my mistake ;)
