### ISSUE TITLE
Grid filtering & sorting when wrapped in a ViewComponent?

### ISSUE THREAD

**Issue by timotahti** [NonFactors/MVC6.Grid#24]
Hi,

it seems that filtering & sorting controls are disabled if I wrap the grid in a ViewComponent like in the example below - any workaround for this? Probably more of an MVC rendering thing really.

**Main View:**
`@await Component.InvokeAsync("ContractsView", new { customerId = Model.Id })`

**Component View:**

```
@using NonFactors.Mvc.Grid;

@model IEnumerable<ExampleModel.Contract>
<div class="panel panel-default">
    <div class="panel-heading">Contracts</div>
    @Html.Grid(Model).Build(columns =>
{
    columns.Add(model => model.ContractType).Titled("Contract Type").Sortable(true).Filterable(true);
}).Named("ContractsGrid").Filterable().Sortable().Css("table-hover").Empty("No data found.")
</div>
```

Regards,
-Timo

**Comment by Muchiachio** [comment]
I tried to repro, but it worked fine for me. Could you share a repro?

**Comment by timotahti** [comment]
Hi, sorry, a bit busy here. I'll try and create proper repro - cannot really share the actual project, sorry. :(

Anyways, I attached a screenshot of the 2 event listeners that are NOT being attached for some reason. Any ideas where to look? In the layout there's obviously <div> after <div> and as said, the grids are being rendered inside a ViewComponent.

-Timo

![image](https://cloud.githubusercontent.com/assets/16205779/19799689/9e187c06-9d00-11e6-8266-a98b9d82d177.png)

**Comment by Muchiachio** [comment]
They are binded by `$('.mvc-grid').mvcgrid();` call, maybe it's not being called.

**Comment by Muchiachio** [comment]
Hi @timotahti, how's your schedule going.
Maybe you can share a repro now or you managed to find a problem?

**Comment by Muchiachio** [comment]
Hi @timotahti, how's your schedule going.
Maybe you can share a repro now or you managed to find a problem?

**Comment by Muchiachio** [comment]
Sorry, but I'm closing as not reproducible.
