### ISSUE TITLE
Element binding via jQuery

### ISSUE THREAD

**Issue by antetmc2** [NonFactors/MVC6.Grid#27]
Hello,
I have a question about binding of elements to the specific events. e.g. I am working on bulk select via checkboxes and MVC6.Grid, but I'm having issues with binding of checkboxes. I tried to put the necessary code into realoadEnded event, but I could not get the desired result.

Here is the example of what I tried to do, but I need binding of elements to work from the moment the initial loading for MVC6.grid has ended:

```JS
ib.controls.grid.refresh = function () {
    $('.mvc-grid').mvcgrid({
        reload: true,
        reloadStarted: function (grid) {
            loadingModal.open();
        },

        reloadEnded: function (grid) {
            $('.mvc-grid-wrapper').show();
            loadingModal.close();
            $('.checkbox').on("click", function () {
                alert('A');
            });
        },

        reloadFailed: function (grid, result) {
            loadingModal.close();
            var message = '';
            if (result.responseJSON instanceof Array) {
                message = result.responseJSON;
            } else {
                message = result.responseJSON.join('<br />');
            }
            toastr.warning(message);
        }
    });
};
```
Is there any workaround for this?

Best regards,
Ante

**Comment by Muchiachio** [comment]
Try changing
```JS
$('.checkbox').on("click", function () {
    alert('A');
});
```
to
```JS
$(document).on('click', '.checkbox', function () {
    alert('A');
});
```
where `document` is a root `document` object or any other static element to which you add the dynamic links.
So, you have a static content and you fill it with dynamic content. The idea is to delegate the events to that static element, instead of binding handlers directly on the dynamic elements. Because they get lost on each reload.

**Comment by antetmc2** [comment]
Thank you, it worked! 

I actually tried with document, but I forgot on document's click event, this now works perfectly. :)
