### ISSUE TITLE
Reload Grid with POST data

### ISSUE THREAD

**Issue by jjkcharles** [NonFactors/MVC6.Grid#28]
Hi, Can you please extend the AjaxGrid to allow reloading Grid with POST data (supported through more options passed to mvcgrid() - like AjaxCallType : GET/POST, Data: {} etc... ). This way, it will be easier to pass complex data back to the controller rather than use cumbersome approaches with query string (especially when the data being passed is not simple enough for query strings).

**Comment by Muchiachio** [comment]
Yes, seems like a doable thing.

**Comment by jjkcharles** [comment]
Thanks for incorporating it. Can you please let me know when would these changes be pushed to the Nuget packages?

**Comment by Muchiachio** [comment]
Should be after 1-2 weeks.
