### ISSUE TITLE
Editable grid cells?

### ISSUE THREAD

**Issue by ECatherman89** [NonFactors/MVC6.Grid#29]
How difficult would it be to add editable grid cell to this project?

Is this already part of the project and I missed it?

if not what is your opinion on the difficulty of making it editable myself?

**Comment by Muchiachio** [comment]
No, it's not part of this project. And as with everything, it can be added by hand.
I can't really comment on difficulty, as I don't know which approach you would choose for implementing it.

The one thing I know that you would require saving property names somewhere in the DOM.

**Comment by Muchiachio** [comment]
Did you managed to make your grid rows editable?

**Comment by ECatherman89** [comment]
No we are currently deciding what grid we are going to use. We will probably end up using Telerik.

**Comment by Muchiachio** [comment]
Well yes, Telerik has some built in features to ease up row editing. Good luck with your choice.
