### ISSUE TITLE
DNX Core 5.0 Compatibility?

### ISSUE THREAD

**Issue by timotahti** [NonFactors/MVC6.Grid#3]
Hi, is it possible to include support for DNX Core 5.0? We cannot use the grid in a project targeting  "dnxcore50" at the moment.

**Comment by Muchiachio** [comment]
Yes it will be available, hopefully with RC2 or RTM.
Don't know when [this](https://github.com/dotnet/corefx/issues/5381) is going to be done.

**Comment by timotahti** [comment]
Thanks for the update, feel free to close the issue. Looking forward to RC2 for a couple of other reasons as well... :)
