### ISSUE TITLE
DateTime Picker for filter

### ISSUE THREAD

**Issue by codenamelxl** [NonFactors/MVC6.Grid#31]
Hi,
I was looking around for a Nugget Package that support GridView and work with MVC6. I found your awesome work. However, as i notice, the Filter for DateTime type can be improved to be more user-friendly. Maybe we can have a Datetime picker dialog instead of the Equal, Less than, etc... Do you have any plan to add that feature anytime soon?
Thanks for your great work 💯

**Comment by Muchiachio** [comment]
Currently grid date filter reacts to jQuery UI's datepicker and uses that if it's available.
Do you have something else in mind, that could be used to improve user experience?

**Comment by codenamelxl** [comment]
I see the datetime picker now. Haven't used this package in my project though so i can't say much. I will open another issue if i find something worth to share. Thank again.
