### ISSUE TITLE
RequestType lost on Sorting/filtering/subsequent reloads

### ISSUE THREAD

**Issue by jjkcharles** [NonFactors/MVC6.Grid#32]
I initialize the mvcGrid with below code, since my controller serving data to the grid is marked [HttpPost] ,
`$('.mvc-grid').mvcgrid({
requestType: 'POST'
});`

On subsequent reloads (without an option to force 'POST'), paging, sorting or filtering, a GET call is triggered causing a failure.

Can you persist the initial requestType passed in during initialization and use it across the grid life cycle. I have something like below in my mind,
`this.requestType = options.requestType || grid.data('request-type') || 'get';`

Related to #28

**Comment by jjkcharles** [comment]
As a work around, I am using a reloadStarted handler, that would set the requestType to POST prior to reloads are executed,
`$('.mvc-grid').mvcgrid({ 
requestType: 'POST',
reloadStarted: function(){
this.requestType = "POST";
} });`

**Comment by Muchiachio** [comment]
Ah yes, it's missing on automatic reload.

**Comment by jjkcharles** [comment]
Thanks for the quick fix. Can you please confirm when these changes would make it to NuGet. I see even #28 or #23 haven't yet been pushed there.

**Comment by Muchiachio** [comment]
Yes, I wanted to push them today after testing.
