### ISSUE TITLE
Filterable not showing

### ISSUE THREAD

**Issue by asafgo** [NonFactors/MVC6.Grid#34]
Hi,

I have some data from Json where I am using Convert.ChangeType to convert to DateTime.
Grid accept is as DateTime but when pressing the Filter icon nothing happens.

`var x = Convert.ChangeType(item.m_fld_value, typeof(DateTime));`
`columns.Add(model => x).Titled(item.m_fld_name).Formatted("{0:dd/MM/yyyy}").Filterable(true);`

Thanks for any help,
AG

**Comment by Muchiachio** [comment]
Make sure your `x` variable is of type `DateTime`, because `Convert.ChangeType` returns object type which is not filterable by default.

**Comment by asafgo** [comment]
Thanks, it is working.
Regards,
AG
