### ISSUE TITLE
How to set page size

### ISSUE THREAD

**Issue by Cri93** [NonFactors/MVC6.Grid#36]
Hello, I have this simple problem:
I do not understand how to set the number of lines to 20, default is 10.

`@Html.AjaxGrid(Url.Action("ListValueAction"))`

**Comment by Muchiachio** [comment]
[Here's](http://mvc-grid.azurewebsites.net/Grid/Paging) an example of configuring pager, so in the partial view which get's returned by `ListValueAction` grid should initialized with `RowsPerPage` to 10. Actually, [ajax grid](http://mvc-grid.azurewebsites.net/Grid/Ajax?mainParam=mainValue) example uses that configuration too.

**Comment by Cri93** [comment]
@(Html .AjaxGrid(Url.Action("LavorazioniPartial"))    
    .Pageable(pager =>
    {      
        pager.RowsPerPage = 20;
    })
    )

does not work :(

**Comment by Muchiachio** [comment]
No, check the [example](http://mvc-grid.azurewebsites.net/Grid/Ajax?mainParam=mainValue). Your controller action `LavorazioniPartial` needs to return a partial view which renders the actual grid. `Html.AjaxGrid` just tells where to get the grid from, so it can work through ajax.

**Comment by Cri93** [comment]
I still do not understand, returns action LavorazioniPartial a list of objects, for example, 30 objects,
but I will only visualize 10.
I do not understand where I have to apply the method: 
.Pageable (pager =>
     {
         pager.RowsPerPage = 20;
     })

**Comment by Muchiachio** [comment]
Where do you create your grid (add columns etc)?
Your `LavorazioniPartial` action should look similar to this.

```C#
public ActionResult LavorazioniPartial()
{
    return PartialView("_LavorazioniGrid");
}
```

And your `_LavorazioniGrid.cshtml` will declare the grid
```C#
@using NonFactors.Mvc.Grid;

@model IEnumerable<LavorazioniModel>

@(Html
    .Grid(Model)
    .Build(columns =>
    {
        columns.Add(model => "Test");
    })
    .Pageable(pager =>
    {
        pager.RowsPerPage = 10;
    })
)
```

And all this will be called from your `Index.cshtml` or any other one, like this
`@(Html .AjaxGrid(Url.Action("LavorazioniPartial")))`

**Comment by Cri93** [comment]
Hello, I have now solved the problem, thank you very much for supporting.
Now I'm really excited!
