### ISSUE TITLE
Dispaly Empty string instead of Date?

### ISSUE THREAD

**Issue by asafgo** [NonFactors/MVC6.Grid#37]
Hi,

How to display Empty string where date is "01/01/1900"?

`columns.Add(model => model.Birthday).Titled("Birth date").Formatted("{0:dd/MM/yyyy}";`

Thanks,
AG

**Comment by Muchiachio** [comment]
Usually empty string comes from date value being `null`.

**Comment by asafgo** [comment]
Thanks!
