### ISSUE TITLE
How to get the current Model object in Build Enumerable?

### ISSUE THREAD

**Issue by asafgo** [NonFactors/MVC6.Grid#38]
Hi,

I would like to have the current PersonModel inside Build method as for example the line
        var CurrentModelEnum = ???

Thanks,
AG

```C#
@model IEnumerable<PersonModel>

@(Html
    .Grid(Model)
    .Build(columns =>
    {
        columns.Add(model => model.Name).Titled("Nom");
        columns.Add(model => model.Surname).Titled("Nom de famille");

        var CurrentModelEnum = ???

        columns.Add(model => model.Age).Titled("Âge");
        columns.Add(model => model.Birthday).Titled("Date de naissance");
        columns.Add(model => model.IsWorking).Titled("Employé");
    })
    .MultiFilterable()
    .Filterable()
    .Sortable()
)
```

**Comment by Muchiachio** [comment]
It will be available as `model` in `columns.Add(model => model.Age)` for example, so you can write any code block in side if you want to.

**Comment by asafgo** [comment]
I have a model class with sub items as list in other class so for each object in the main class I would like to get the list of the sub class with foreach and inside it to use columns.Add

**Comment by Muchiachio** [comment]
You can't add columns dynamically, they have to be known from the start.
If you know them you can use iterate them and add columns as needed.

Maybe you could share an example of what is not working?

**Comment by asafgo** [comment]
Hi,

Attached a zip file with .NET Core code of what I would like to do.
In Models folder you can find the MainClass and SubClass(List).
My code for grid is at Index.cshtml and I am using HomeController and Index action.

Thanks,
AG

[MVC6.Grid_Test.zip](https://github.com/NonFactors/MVC6.Grid/files/627168/MVC6.Grid_Test.zip)

**Comment by Muchiachio** [comment]
Well I don't think you can do that, the best you could do is create a child grid within a main grid.

**Comment by asafgo** [comment]
Thanks you for your help, I will look how to solve this...
