### ISSUE TITLE
Problem using AjaxGrid

### ISSUE THREAD

**Issue by vzdesic** [NonFactors/MVC6.Grid#39]
Hi all,

I found an issue, so, inside MvcGridExtensions.cs there is one extension method:

        public static IHtmlContent AjaxGrid(this IHtmlHelper html, String dataSource)
        {
            return html.Partial("MvcGrid/_AjaxGrid", dataSource);
        }

Because html.Partial expects second parameter to be an object of type: 

    Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary 

and we send string instead it gives this error when using in ASP.NET Core project:

    InvalidOperationException: The model item passed into the ViewDataDictionary is of type 'System.String', but this ViewDataDictionary instance requires a model item of type 'System.Collections.Generic.IEnumerable`1[AyurAtNet.Gui.Models.PersonAddress]'.

----------------------------------------
Also it seems something is wrong when using AjaxGrid as it is proposed in this web examples:
https://github.com/LeonardoDaga/MVC6.Grid.Demo1stAspNetApp 

Why would we call this line in our View:
    @Html.AjaxGrid(Url.Action("GridPartial", new { param = "value" }))

Because it will never call GridPartial and send parameter 'param' to this action method. It will just send string to the helper.

Thanks,
Vedran

**Comment by Muchiachio** [comment]
Everything is ok with `AjaxGrid` and official examples repo is [here](https://github.com/NonFactors/MVC6.Grid.Web). As you can see [ajax grid helper](http://mvc6-grid.azurewebsites.net/Grid/Ajax?mainParam=mainValue) takes an url source, which can have parameters if you would need them to help you load the data.

**Comment by vzdesic** [comment]
Hi Muchiachio,

I am new here, I am trying to use this grid in my ASP.NET Core project, but I have some problems. Probably I messed versions or something.

So, I am sure you are right! I will just accept that :)

I found this piece of code in Mvc.Grid.Core project, inside Html folder and there is file MvcGridExtensions.cs ...
src -> Mvc.Grid.Core -> Html -> MvcGridExtensions.cs

Thanks,
Vedran

**Comment by vzdesic** [comment]
I think I found all I need in a help you sent me! Thanks.

**Comment by Muchiachio** [comment]
It is possible to render it yourself, there is no build it functionality for that.

**Comment by vzdesic** [comment]
Ok, thanks!
