### ISSUE TITLE
Creating links in grid cells

### ISSUE THREAD

**Issue by dnataraj** [NonFactors/MVC6.Grid#4]
Hi - how would we go about creating a href for the content displayed in the row? e.g so that when a user clicks on the data in a row, we can display another partial/view. Thanks!

**Comment by Muchiachio** [comment]
[Here's](http://mvc6-grid.azurewebsites.net/Column/Encoding) an example on how to add html content using html helpers. You can also add them by hand, the only important thing is to use `.Encoded(false)`, because all grid data is encoded by default.

**Comment by dnataraj** [comment]
Thank you - we got it working as well!
