### ISSUE TITLE
Better support for Selectable RowsPerPage

### ISSUE THREAD

**Issue by jjkcharles** [NonFactors/MVC6.Grid#42]
Current version of Grid, allows changing RowsPerPage by introducing a Select element inside the Pager (backed by an hidden input). This has a problem, when the PageSize is set to anything greater than the current result set. When such page size is set (for instance, number of records in result is 25, and I have chosen a PageSize of 50), Pager is not displayed (which also means the hidden input is not rendered). Thus preventing any further PageSize changes. 

Changing RowsPerPage should probably not be tied to the Pager, as it is something that should be displayed irrespective of the page size (but, only when paging is enabled & always when paging is enabled)

**Comment by Muchiachio** [comment]
Well it's debatable if pager should be showed or not on a single page, but I agree that now, default pager partial doesn't allow changing that easily. As for `RowsPerPage`, the current example shows how to create your own partial with the added rows per page selection, as it is your own partial you could just remove the check [here](https://github.com/NonFactors/MVC6.Grid/blob/97e71f218782dcc3b2bae328bd9a5bbde91c04e6/src/Mvc.Grid/Views/Shared/MvcGrid/_Pager.cshtml#L12).

I'm thinking of adding an empty pager class to the pager div, so people can style it accordingly. This would allow showing or hiding it. What do you think?

**Comment by jjkcharles** [comment]
Well, I do agree it is up to the developer to override the partial pager and ensure RowsPerPage is better supported. In the default Pager partial view though, in a certain case RowsPerPage is completely disabled preventing any further changes to be done to the PageSize, which I feel shouldn't be the case - and the API to wire-up the PageSize customization should be something exposed as part of JS's mvcgrid() options (just a random suggestion, I haven't given much thought on this)

Not sure if I understood your last statement, can you please explain.

**Comment by Muchiachio** [comment]
When is the `RowsPerPage` being disabled? Even if pager isn't shown, it still works. You can see that from entering `RowsPerPage` by hand in the url. Default api just uses `.mvc-grid-pager-rows` input to get the page.

My last sentence was a suggestion, on how to enable showing or not showing the pager while not breaking current API and compatibility. So I was thinking of adding a class indicating if pager is single paged or not.

**Comment by jjkcharles** [comment]
Yes, RowsPerPage is still available (and up to the developer introducing custom view to make sure it is present irrespective of single/multi-page results, based on his requirement) - I might have got confused looking at multiple versions of the _Pager.cshtml implementations when I made that remark. 

But, I still feel that there should be a better way to trigger the the RowsPerPage changes, rather than the Grid having to listen to the OnChange of a html element within Pager,

`grid.pager.rowsPerPage.on('change', function () {
...
};`

With the current Grid implementation, if I need to have a RowsPerPage selector outside Pager area, I either have to manually trigger the OnChange event of '.mvc-grid-pager-rows' within the Pager, or modify the query string of SourceUrl and reload the grid. Both of which doesn't seem to be a neat way of doing it.

**Comment by Muchiachio** [comment]
What would be a neat way of changing it?

**Comment by jjkcharles** [comment]
Like I mentioned earlier, one way would be to expose it as an Option parameter, so that the usage would be something like, 

`$('.mvcgrid').mvcgrid({
PageOptions: {
RowsPerPage: 10,
PageNo: 1
},
reload: true
});`

**Comment by Muchiachio** [comment]
I made pager always visible then it's enabled. With that said, I'm not going to add paging options for now, because they would created conflicts with a query parameter. But it's definitely a good idea for the next release with breaking changes :+1:

**Comment by jjkcharles** [comment]
Sounds good. Thanks!
