### ISSUE TITLE
Dynamic Columns

### ISSUE THREAD

**Issue by MarcAir** [NonFactors/MVC6.Grid#43]
Ive been playing around with creating an extension either through gridprocessor or within the actual grid call in a partial view to build out the columns to sql stored fields.
ive played with a few different ways to get the values for each model
I'm having issues with selecting the column again and replacing the values with the ones stored for each Model.
(ive also tried various other methods but this is the closest to the result I need.)

I thought I would ask, if there was a function /hack to point me in the right direction
partialview
```cshtml
   @(Html.Grid(Model)
    .Build(columns =>
    {
        columns.Add(model => model.FirstName).Titled("First Name").Filterable(true);
        columns.Add(model => model.Surname).Titled("Last Name").Filterable(true);
        foreach (var demo in Model.Take(1))
        {
            foreach (var col in demo.Details.OrderBy(s=>s.question.SortOrder))
            {
                columns.Add(model => **col.question.Id).**Titled(col.question.Value).Filterable(true);

            }

        }


    })
    .Pageable(pager =>
    {
        pager.PagesToDisplay = 2;
        pager.RowsPerPage = 2;
    })
    .Filterable()
    .Sortable()
    .Empty("No data found")
    )

```
Model Class
```csharp
public class ProjectUser
    {
        public string Id { get; set; }
        [Display(Name = "First Name")]
        public string FirstName { get; set; }
        [Display(Name = "Surname")]
        public string Surname { get; set; }
        public virtual ICollection<ProjectUserDetail> Details { get; set; }
       
    }
public class ProjectUserDetail
    {
        public int Id { get; set; }
        public string DetailLabel { get; set; }
        public virtual Question question { get; set; }
        [JsonIgnore]
        [IgnoreDataMember]
        public virtual DemographicResponse Response { get; set; }
    }
```

**Comment by Muchiachio** [comment]
The only problem to solve here is to avoid variable capturing in lambda expression.
I usually used child access by index or a key.

**Comment by MarcAir** [comment]
Thanks for the tip.
I was able to get it working:
```csharp
 public DemographicResponse ResponseById(int QuestionId)
        {
           return Details.FirstOrDefault(s => s.question.Id == QuestionId).Response;
         }
```
```cshtml
foreach(Question col in questions) //external method to setup the questionvalues
        {
            columns.Add(model => model.ResponseById(col.Id).Response).Titled(col.Value).Filterable(true);
                 }
```

**Comment by herin** [comment]
Hi MarcAir, I have also have similar problem having dynamic columns and rows, Can you please share details of your code/solution ?

Thanks.

**Comment by Muchiachio** [comment]
What's the data source you are using?

**Comment by herin** [comment]
I am using excel file as source of data, and in that excel file there are N number of columns and rows. So Need to create dynamic columns as per available in excel file...

Thanks.

**Comment by Muchiachio** [comment]
Yes, but how do your store them in C#?

**Comment by herin** [comment]
Hey, I got some solution, but now my filtering is not working, as My columns Name is dynamic. So its not properly generating querystring by filtering

Here is my Grid:

`@(Html.Grid(Model)
    .Build(columns =>
    {
        foreach (var demo in Model.Take(1))
        {
            foreach (var item2 in demo.Details)
            {
                string title = item2.question.valueData;
                columns.Add(model => model.getDataById(item2.question.Id).valueData).Titled(title).Filterable(true);
            }
        }
    })
    .Pageable(pager =>
    {
        pager.RowsPerPage = 5;
    })
    .Filterable()
    .Sortable()
    .Empty("No data found")
)`

And Also :

`public BodyValue getDataById(int QuestionId)
        {
            //return ListData.FirstOrDefault(z=>z.)
            return Details.FirstOrDefault(s => s.question.Id == QuestionId).Response;
        }`

So, here its showing different title on the Grid, but while making any filtering, its internally taking title as "valuData" for all columns.

Can you please help me out ?

Thanks.

**Comment by Muchiachio** [comment]
It's not generating correct filter query, because your value expression is not a property, but a function call.
You could try using `.Named` on column to form a unique name for each column.

**Comment by herin** [comment]
But, there no 

`.Named`

kind of property available.

**Comment by Muchiachio** [comment]
`(...).Filterable(true).Named("xxx");` should work.

**Comment by herin** [comment]
Yehhh, 
Thats working nice...
Thanks Muchiachio for kind help.

Thanks

**Comment by herin** [comment]
Hello,

I have also done the same thing, and it works well, but the only problem is there - Sorting is not working, It building the sort query in a right way but not applying the Sorting.

Can you help me please....

Thanks.

**Comment by Muchiachio** [comment]
Could you share a small repro of sorting not working?

**Comment by herin** [comment]
Here is my code :

`@(Html.Grid(Model)
    .Build(columns =>
    {
        foreach (var demo in Model.Take(1))
        {
            foreach (var item2 in demo.Details)
            {
                string title = item2.question.valueData;
                columns.Add(model => model.getDataById(item2.question.Id).valueData).Titled(title).Filterable(true).Named(title).Sortable(true)
            }
        }

    })
    .Pageable(pager =>
    {
        pager.RowsPerPage = 5;
    })
    .Filterable()
    .Sortable()
    .Empty("No data found")
)`
