### ISSUE TITLE
Wish I could use it ..

### ISSUE THREAD

**Issue by MeesterJeem** [NonFactors/MVC6.Grid#44]
Hi, 

I stumbled on your Grid component for MVC6 (CORE) -- I installed it, but don't understand the instructions -- for example, where do I find: ~/.nuget/packages/NonFactors.Grid.Mvc6/1.3.0/content. ???

Did they install somewhere in my Project when I installed the package?  I cannot find any information on how to get it working properly.   Looks great, but I could use some help using it, it's not intuitive (yet).

**Comment by Muchiachio** [comment]
It's the global nuget installation folder, back in MVC5 it used to install it in solution folder in `packages` folder.
Now it's in your user folder under a name of `.nuget`, which holds all the files.
If you are on windows it's something like this: `C:\Users\<user>\.nuget`

**Comment by Muchiachio** [comment]
Did you managed to get it working?

**Comment by MeesterJeem** [comment]
Yes - Thanks for the info about where nuget places the files in MVC6.  It's a well done grid.  I'll test it some more when I get back to my Views and let you know of any problems.  Thanks for your help.

**Comment by MiroValchev** [comment]
@Muchiachio can you please include this in the Installation guide as I can across this one too. I know it might be obvious for some folks, but not so much for others. Thanks for the great work!

**Comment by Muchiachio** [comment]
@MiroValchev, this is for core and .net installations, although a sentence about that was already included
`Include grid css files, they can be found ~/.nuget/packages/NonFactors.Grid.Mvc6/{version}/content.`

But I'm not sure how to specify the path for all the platforms (win, linux, etc), so I wrote
`~/.nuget/packages/...`. Any suggestions on what you expected but didn't found?

`NonFactors.Grid.Core.Mvc6` version only contains the grid dll, all the content is at `NonFactors.Grid.Mvc6`.

**Comment by MiroValchev** [comment]
@Muchiachio probably something like this:
Included grid partial views to your Views/Shared folder, they can be found at ~/.nuget/packages/NonFactors.Grid.Mvc6/{version}/content.
(On Windows nuget's path should be something like this: C:\Users\<user>\.nuget )

**Comment by Muchiachio** [comment]
Ok, I will try reworking the installation notes.
