### ISSUE TITLE
Can we use TagHelpers in the Grid?

### ISSUE THREAD

**Issue by MeesterJeem** [NonFactors/MVC6.Grid#46]
I created a TagHelper to build a Bootstrap Popup on Hover e.g., <popup-phones>123-345-4567</popup-phones> to show additional phone numbers;  When I use it as such:
 
`columns.Add(m => $"<popup-phones unit-id='{m.ID}'>{m.PrimaryPhone}</popup-phones>").Encoded(false);`

It does not seem to trigger the TagHelper and the results show 123-345-4567 with popup-phones html suppressed from view but visible when inspected in Html source.  The source does not show all the extra HTML created by the TagHelper.  As a test, The TagHelper worked outside of the grid using  `<popup-phones unit-id='100'>123-345-4567</popup-phones>` on its own.

Is there an option I need to use to force the TagHelper to trigger?

**Comment by Muchiachio** [comment]
No tag helper won't work on a string. It works by injecting C# code into a razor file if a tag falls under a tag helper rules, that's why it can not work as a grid column which is just a string value.
