### ISSUE TITLE
Grid reloading is not resetting pager's current page to 0

### ISSUE THREAD

**Issue by vcaraulean** [NonFactors/MVC6.Grid#48]
I'm reloading a grid after some user's actions:
```JS
function RefreshGridData() {
    $('.mvc-grid')
        .mvcgrid({
            reload: true,
 ......

$('#list').on('change', RefreshGridData);
$('#indexQueryForm').on('submit', function(form) {
    form.preventDefault();
    RefreshGridData();
});
```

I noticed that if I'm on a second page and re-loading the grid with additional filtering (external to grid) then pager is keeping it's previous position, which might be confusing for users...

Is there an easy way to tell, while re-loading, to reset the grid to first page?
I tried to add a parameter to options, but can't make it work reliably...

**Comment by Muchiachio** [comment]
If you are reloading grid with additional filtering, you are changing the query right?
If that's true it should be reset already as in:
```JS
$('.mvc-grid').mvcgrid({
    query: 'search=' + '<filter_value>',
    reload: true
});
```
Otherwise, you can remove the page part from the query:
```JS
var grid = $('.mvc-grid').data('mvc-grid');
grid.queryRemove(grid, grid.name + '-Page');
$('.mvc-grid').mvcgrid({
    reload: true
});
```
But keep in mind that `queryRemove` is a private undocument function, which could change on any release.
If you want to be safe remove `grid.name + '-Page'` key of the query by hand.

**Comment by vcaraulean** [comment]
In my code I was actually posting the request with filter options as a payload. But your point about passing them in query might be a better option and give some other advantages... 

I do have the grid using an IQueryable model. If I pass the page as a query parameter, will it be handled properly on reload?

**Comment by Muchiachio** [comment]
Yes, grid itself is passing paging information like that.

**Comment by vcaraulean** [comment]
Thanks for your help!
