### ISSUE TITLE
How to do Row selection and adding buttons to columns?

### ISSUE THREAD

**Issue by bangonkali** [NonFactors/MVC6.Grid#51]
I tried on render and added an a href on some columns but it seems it is html encoding the string.

How do I add custom Columns, on rows that respond to click event?

**Comment by Muchiachio** [comment]
You either render `HtmlContent` which is not encoded by default or render a string with `Encoded` option set to false. You see encoding examples [here](http://mvc6-grid.azurewebsites.net/Column/Encoding).

**Comment by Muchiachio** [comment]
Did you got it working?

**Comment by bangonkali** [comment]
Thanks! it solved my issue!
