### ISSUE TITLE
AjaxGrid Success Handler

### ISSUE THREAD

**Issue by amkuchta** [NonFactors/MVC6.Grid#52]
Sorry for yet another issue...

Is there a way to have an action performed upon the successful loading of an AjaxGrid? I'd like to show a progress bar while the grid is loading, then hide it once the grid is rendered.

**Comment by Muchiachio** [comment]
Yes there are grid events, please make sure you read through example [pages](http://mvc6-grid.azurewebsites.net/).
Grid reload events are shown [here](http://mvc6-grid.azurewebsites.net/Javascript/ReloadEvents).

**Comment by amkuchta** [comment]
Awesome, thank you!
