### ISSUE TITLE
Can't get the grid to work

### ISSUE THREAD

**Issue by MiroValchev** [NonFactors/MVC6.Grid#54]
My setup:
Visual Studio 17RC
Microsoft.AspNetCore 1.1.0
Microsoft.AspNetCore.Mvc 1.1.1

The grid doesn't work and I get this strange error:
http://localhost:50275/Forms net::ERR_CONNECTION_RESET

If I remove the grid everything works just fine :(
Tried with the AJAX Grid (I was desperate), same result.

View:
```
<link href="~/Content/MvcGrid/mvc-grid.css" rel="stylesheet" />
<script src="~/Scripts/MvcGrid/mvc-grid.js"></script>

@using NonFactors.Mvc.Grid;
@model ListViewModel
<div>
 @Html.Grid(Model.Forms).Build(columns =>
   {
       columns.Add(x => x.ID).Titled("ID");
   })
</div>

<script type="text/javascript">
    console.log(1);
    $('.mvc-grid').mvcgrid({
        rowClicked: function (grid, row, data, e) {
            console.log('data: ' + data);
            console.log('grid: ' + grid);
        }
    })
</script>
```

Controller:
```
public ActionResult Index()
        {            
            var forms = _context.Forms.ToListAsync().Result;
            var model = new ListViewModel(forms);
            return View(model);
        }        
```

![image](https://cloud.githubusercontent.com/assets/7013750/23211100/0540e7b0-f909-11e6-8e2c-899945f50d88.png)

In the screenshot I've removed the Build call, i.e. just @Html.Grid(Model.Forms), still there's this strange error.

**Comment by Muchiachio** [comment]
Building grid columns is required so you shouldn't remove that :)

Other than that, did you register the grid at startup? If that doesn't help try creating a small new project and see if it still gives errors, if it does upload it to github and I will look into that :+1:

**Comment by MiroValchev** [comment]
F Me. Tried with a new project and it works. Makes absolutely no sense.
Thanks for your time!

**Comment by MiroValchev** [comment]
@Muchiachio just FYI I managed to reproduce it. Have no clue as to why, but if you create your project with Individual User Authentication, then this error appears. Same code that works with no authentication.

**Comment by Muchiachio** [comment]
Well if it's not grid related you don't have to. Or you are saying that grid + auth doesn't work, but only auth works?

**Comment by MiroValchev** [comment]
As long as there is no auth, the grid works fine. The only difference between the two test projects is that one uses auth and the other not. In the later one the grid works unlike the project with auth.
