### ISSUE TITLE
Uninstalled MVC5.Grid and installed MVC6.Grid

### ISSUE THREAD

**Issue by retthom** [NonFactors/MVC6.Grid#55]
Hi

I uninstalled MV5.Grid and installed MVC6.Grid.

I added to my Bundle the following

            bundles.Add(new ScriptBundle("~/bundles/jquery").Include(
                "~/Scripts/jquery-{version}.js",
                "~/Scripts/MvcGrid/mvc-grid.js"));

            bundles.Add(new StyleBundle("~/Content/css").Include(
                      "~/Content/bootstrap.css",
                      "~/Content/mvc-grid.css",
                      "~/Content/site.css"));

I also added to my "Startup.cs"

        public void Configuration(IAppBuilder app)
        {
            ConfigureAuth(app);
        }

        public void ConfigureServices(IServiceCollection services)
        {
            //services.AddMvc();
            services.AddMvcGrid();
        }
        public void Configure(IApplicationBuilder app)
        {
            app.UseMvcWithDefaultRoute();
            //app.UseStaticFiles();
        }

When I try to use

@(Html
    .Grid(Model)

I get the following error message.

**HtmlHelper<dynamic> does not contain a definition 'Grid' and the best extension method overload 'MvcGridExtensions.Grid<T>**

**I am also getting this error message when reviewing the** _Grid.cshtml

**The type 'IGid' exists in both 'Mvc.Grid.Core, Version=1.4.0.0 culture=neutral, PublicKeyToken=null' and 'NonFactores.Mvc.Grid, Version=3.4.0.0, culture=neutral, PublicKeyToken=null**

I have uninstalled and installed several time cleaned my registry.

Looks like I am having a reference issue.  How do I resolve my problem.

Thanks

**Comment by Muchiachio** [comment]
Are you upgrading your project from MVC5 to ASP NET Core?
Otherwise you shouldn't be able to just migrate to MVC6 version.

**Comment by retthom** [comment]
Okay.

So I have to upgrade to MVC6 as well.

When I installed MVC6.Grid.  Looks like I was updated to MVC6.

I think I will go back to MVC5.

**Comment by Muchiachio** [comment]
Yes, NuGet shouldn't escape into different grid package, if you just do an update with
`update-package NonFactors.Grid.Mvc5`.

**Comment by retthom** [comment]
Ok

The reference is there but I am not getting this error message.

The type or namespace name 'NonFactors' could not be found (are you missing a using directive or an assembly reference)

**Comment by retthom** [comment]
Please disregard my last message.

Its working now.

Thanks for your help
