### ISSUE TITLE
Problem with examples

### ISSUE THREAD

**Issue by fgonc124** [NonFactors/MVC6.Grid#56]
Hi

I can't get success with any of examples provided. I'm using Visual Studio 2015. All of them generate compile errors

Can you provide a simple project with grid that compiles and works in VStudio 2015

Thank you

**Comment by Muchiachio** [comment]
Which examples are you using? Official examples [page](http://mvc6-grid.azurewebsites.net/) is using [this repository](https://github.com/NonFactors/MVC6.Grid.Web) as it's source, which is already converted to VS2017+ and can only be run in VS2015 by checking out it's [older version](https://github.com/NonFactors/MVC6.Grid.Web/tree/ae11d10160738baa3096df81e11747e43be4db95).

If you are just copying the code from the example pages it should just work on VS2015.

**Comment by fgonc124** [comment]
Hi

Thank for your help.

I tried several versions. THe last one was
https://github.com/NonFactors/MVC6.Grid/tree/417252be974d2f5c379a5f4d349aa83886e1437e

That fails too.


2017-03-20 12:44 GMT+00:00 Muchiachio <notifications@github.com>:

**Comment by Muchiachio** [comment]
Well it worked on 3 of my machines, maybe you are missing latest ASP NET tooling installed?
And what kind of errors do you get?

**Comment by fgonc124** [comment]
I updated all components but no luck

I tried to build a project that use mvc6.grid but could make to work. to
many errors during the build.

DO yo have a simple project that with the grid that works and that  I can
look at?

Thank you for your been patient

2017-03-20 16:00 GMT+00:00 Muchiachio <notifications@github.com>:

**Comment by Muchiachio** [comment]
You can try compiling [example pages](https://github.com/NonFactors/MVC6.Grid.Web) or my [mvc template](https://github.com/NonFactors/MVC6.Template) projects.

**Comment by fgonc124** [comment]
I can't make to work.

When I install mvc6.grid using nuget, does this package is prepare for
VStudio 2015 or just works with 2017

Thanks

2017-03-20 17:30 GMT+00:00 Muchiachio <notifications@github.com>:

**Comment by Muchiachio** [comment]
Just installing it is not enough, you have to follow [these](http://mvc6-grid.azurewebsites.net/Home/Installation) installation steps.

**Comment by fgonc124** [comment]
I already did that but I'm missing something.

I you have the time and patience, please the run this project I built

The link is https://drive.google.com/open?id=0B81NB8fneX1USjhNa1VoWnJFcDg

I got this error when run it

*Compilation Error**Description: *An error occurred during the compilation
of a resource required to service this request. Please review the following
specific error details and modify your source code appropriately.

*Compiler Error Message: *CS1929: 'HtmlHelper<IEnumerable<TablTeste>>' does
not contain a definition for 'Grid' and the best extension method overload
'MvcGridExtensions.Grid<TablTeste>(IHtmlHelper, IEnumerable<TablTeste>)'
requires a receiver of type 'IHtmlHelper'

*Source Error:*

Line 4:  @model IEnumerable<GridFG.Models.TablTeste>
Line 5:  Line 6:  @(HtmlLine 7:      .Grid(Model)
Line 8:      .Sortable()


*Source File:* C:\Users\p040305\Downloads\MVC6.Grid-develop\MVC6.Grid-develop\GridFG\Views\Teste\Index.cshtml
   *Line:* 6

In order to compile the project I had to comment out this two lines

public void ConfigureServices(IServiceCollection services)
        {
          //  services.AddMvc();
            services.AddMvcGrid();
        }
        public void Configure(IApplicationBuilder app)
        {
            app.UseMvcWithDefaultRoute();
          //  app.UseStaticFiles();
        }

Thank you again





2017-03-20 19:18 GMT+00:00 Muchiachio <notifications@github.com>:

**Comment by Muchiachio** [comment]
I think you are running a wrong version of MVC for this grid to work, if you are developing with ASP.NET MVC 5, you would have to use `NonFactors.Grid.Mvc5` package and not `NonFactors.Grid.Mvc6`.

**Comment by Muchiachio** [comment]
Did you managed to fix your project?

**Comment by fgonc124** [comment]
HI
Yes manage to solve the problem

You were wright. It was version of asp.net. I have version 5.
I also installed vstudio 2017.

Thank you for your concern

2017-03-23 8:57 GMT+00:00 Muchiachio <notifications@github.com>:
