### ISSUE TITLE
Conversion of grid to a Microsoft.NETCore.App instead of a net standard core project

### ISSUE THREAD

**Issue by thorne991** [NonFactors/MVC6.Grid#57]
I would like to know your thoughts on doing this. Are there parts that require windows? What would be the fastest way?

Thanks

**Comment by Muchiachio** [comment]
No there is not, it works on core applications out of the box.

**Comment by thorne991** [comment]
Yes, Seems you have 2 versions 
1. Old .csproj -  2013 version your mvc5 version
2. New .csproj - 2017 version your mvc6 version

What we need is an .xproj version. 

Any help?

**Comment by thorne991** [comment]
P.S. We would really like to use your grid, it's great!

**Comment by Muchiachio** [comment]
If you are developing `Microsoft.AspNet.Mvc` web application, you should use MVC5 version.
And if you developing `Microsoft.AspNetCore.Mvc` web application, you should use MVC6 version.

**Comment by thorne991** [comment]
Thank you for your response.

**Comment by thorne991** [comment]
Follow up. Your libraries work great for vs 2017 projects that target netcoreapp1.1 but not  netcoreapp1.0. We are considering moving to the newer target type pending research on getting our build server to work with the newer project type ( .csproj  and netcoreapp1.1 ), which is a kind of back to the future move. 

:)

I do have a question. 

Do you plan on creating a version of your grid that will support grid row editing?

Thanks again for the excellent grid.

**Comment by Muchiachio** [comment]
Strange that it doesn't work on `netcoreapp1.0`, I will try creating a project and see why.
As for inline editing, I'm currently leaving it out of the core grid functionality as it crosses grid functionality boundaries by quite a lot and is hard to implement correctly.

**Comment by thorne991** [comment]
Yes it is strange, we have decided to go to netcoreapp1.1 so it is a mute point for us. We will now use your grid with a scaffolding approach since it does not do row based editing. 

It is still a really nice bit of work. 

Thanks for developing it.
