### ISSUE TITLE
AjaxGrid Paging

### ISSUE THREAD

**Issue by garethdhopkins** [NonFactors/MVC6.Grid#58]
Hi, thank you for the great work. 

I'm trying to get AjaxGrid with paging to work without having to return the entire data set on each request.
Here is the partial called _ListGrid
```
@model IEnumerable<DoIT.Profiler.Core.Entities.Client>

@(Html.Grid(Model)
    .Named("ClientsGrid")
    .Empty("No clients found")
    .Build(columns =>
    {
        columns.Add(p => p.Code).Titled("Code");
        columns.Add(p => p.Name).Titled("Name");
        columns.Add(p => p.DateCreated).Titled("Date Created").Formatted("{0:dd/MM/yyyy}");
        columns.Add(model => $"<a href='/Client/Edit/{model.ClientGuid}' class='btn btn-default'>Edit</a>").Encoded(false);
    })
    .Filterable()
    .Sortable()
    .Pageable(pager =>
    {
        pager.PagesToDisplay = 10;
        pager.RowsPerPage = 20;
    })
)
```

Here is the method that is called by AjaxGrid
```
        public async Task<ActionResult> ListGrid(string search = "")
        {
            var page = Request.Query["ClientsGrid-Page"].ToString().ToNullable<int>();
            var rows = Request.Query["ClientsGrid-Rows"].ToString().ToNullable<int>();

            IEnumerable<Client> clients = null;
            if (page == null || rows == null)
                clients = await _clientService.SearchClients(search);
            else
                clients = await _clientService.SearchClients(search, page ?? 0, rows ?? 0);
            return PartialView("_ListGrid", clients.OrderBy(x => x.DateCreated));
        }
```
If I call `clients = await _clientService.SearchClients(search);` every time it will work but that takes ~20 seconds due to the number of records. As it's coded above the grid loads first time correctly with the paging set-up correctly, showing many pages. Then once I click to go to the next page (and the smaller call is made for just the 20 records of a single page), it reloads the grid and the paging just shows one page.

Is it possible for the grid to remember the total number of records from the first call, or even better for me to pass a simple count of the total number of records on each request to keep the paging working correctly? I've tried the latter manually by passing counts back but the 'TotalRows' and 'TotalPages' properties on the pager config are both read only.

Thanks again!
Gareth

**Comment by Muchiachio** [comment]
Grid already takes care of paging for you, unless you are doing manual paging on raw sql queries?
Otherwise you will have to implement or extend the `GridPager`. The easiest way would be to create your own extension, similar to [this](https://github.com/NonFactors/MVC6.Grid/blob/709477c82d5586697573e4a71ef0c905ac4c364b/src/Mvc.Grid.Core/Grids/HtmlGrid.cs#L95), which would set your own pager implementation.

I was thinking about making `TotalRows` and `TotalPages` mutable, but I couldn't find a proper use case.
I guess I should try implementing user controlled paging and see if their mutability can be used in some way.

**Comment by garethdhopkins** [comment]
From what I can see it makes a call each time the grid is loaded and requires the entire collection of models to be returned to the partial each time, is that right? 
```
        public virtual IQueryable<T> Process(IQueryable<T> items)
        {
            TotalRows = items.Count();

            return items.Skip((CurrentPage - 1) * RowsPerPage).Take(RowsPerPage);
        }
```

As I say, if I return the entire collection of models every time it's ok but when it's a huge collection that's very inefficient. I'll take a look at making a GridPager of my own.

It looks as though it would be the Process method I'd have to rewrite to take the smaller collection of models but to set total rows for the entire collection count. I'll have a think..

**Comment by Muchiachio** [comment]
Yes you have to write your own processing, which in this case should just be `return items` as they are already paged by your controller. And total rows are actually mutable from grid pager implementation.

So the view code could look like this
```C#
@(Html
    .Grid(Model)
    .Build(columns =>
    {
        columns.Add(p => p.Code);
    })
    .YourPageableExtension(pager =>
    {
        pager.TotalRows = <your precalculated total rows>;
        pager.PagesToDisplay = 10;
        pager.RowsPerPage = 20;
    })
)
```

**Comment by garethdhopkins** [comment]
Gotcha, thanks!

**Comment by garethdhopkins** [comment]
In HtmlGrid you have 

```
public virtual IHtmlGrid<T> Pageable(Action<IGridPager<T>> builder)
{
    Grid.Pager = Grid.Pager ?? new GridPager<T>(Grid);
    ....
```

How would you set Grid.Pager, as far as I can see it would always be null at this point?

**Comment by Muchiachio** [comment]
You would change `new GridPager<T>(Grid)` with your own implementation and use `Action<GridPager<T>>` or `Action<YourGridPager<T>>` so that total rows are available.

**Comment by garethdhopkins** [comment]
I was hoping there was a way for me to extend it without changing the core package. Also, wouldn't I also have to change the interface IGridPager to make TotalRows mutable?

**Comment by Muchiachio** [comment]
No grid pager interface is immutable, but it's implementation adds a setter for internal use.
