### ISSUE TITLE
Integration of MVC6.Grid in an existing project

### ISSUE THREAD

**Issue by LeonardoDaga** [NonFactors/MVC6.Grid#6]
First of all thanks for this library, it's wonderful. I compiled the example (MVC6.Web) and it works like a charm.
What I can't do (probably because I'm pretty new to MVC6), is to integrate the grid in my project.
I'm starting from a simple project like this:
https://docs.asp.net/en/latest/tutorials/your-first-aspnet-application.html
and I want to replace the existing grid with the MVC6.Grid you created.
What I have done is:
- create the wwwroot/js/MvcGrid folder like the one that is in the sample MVC6.Web, 
- Add the Mvc.Grid binding in site.js as in the installation instructions ($(function () {$('.mvc-grid').mvcgrid();});
- Add the NonFactors.Grid.Mvc6 version 0.9.0-rc1-final from nuget as in the installation instructions
- Register  mvc grid at start up as in the installation instructions (added services.AddMvcGrid(); in Startup.cs after ConfigureServices)
- Include grid scripts after jQuery scripts (in _Layout.cshtml after site.js)

Probably I missed something because the MVC6.Web sample contains a lot more of stuff I can't connect to what is not working. If I try to show the page what I got is a HTTP Error 502.3 - Bad Gateway error.
What I'm trying to implement is only the grid sorting and I've implemented more or less the code in the http://mvc6-grid.azurewebsites.net/Grid/Sorting page adapted to my case.

Any suggestion is welcome. Thank you in advance.

**Comment by Muchiachio** [comment]
Try adding this to your configure method
```C#
public class Startup
{
    public void Configure(IApplicationBuilder app)
    {
        app.UseDeveloperExceptionPage();
    }
}
```
You should be able to find what is failing from the stack trace, unless you have incorrect DNX configuration or mixed nuget references.

**Comment by LeonardoDaga** [comment]
Hello Muchiachio, thank you very much for the quick reply.
UseDeveloperExceptionPage is already in my Configure, but the result is the same (HTTP Error 502.3 - Bad Gateway error).
I created this temporary repository (https://github.com/LeonardoDaga/MVC6.Grid.Demo1stAspNetApp) with, in parallel, your MVC6.Grid.Web demo and the demo I'm trying to make.

Obviously this repository is just to show you the code. If you like I can give you the sample (or maybe a better one) when I solve the integration problem.

Thank you in advance if you can help me with some suggestions.

**Comment by Muchiachio** [comment]
[This line right here](https://github.com/LeonardoDaga/MVC6.Grid.Demo1stAspNetApp/blob/FirstAspnetAppSample/src/Mvc.Grid.Demo/Views/Books/Index.cshtml#L68) is causing you problems, because it's not valid razor/html syntax. It should be surrounded by <script></script>. And it should be included after jQuery and grid scripts for it to work. So I would recommend you moving it to layout page or using scripts section to render it out.

The other thing is, you didn't include grid partial views to your [shared views folder](https://github.com/LeonardoDaga/MVC6.Grid.Demo1stAspNetApp/tree/FirstAspnetAppSample/src/Mvc.Grid.Web/Views/Shared). I actually forgot to add this step to installation instructions, because it was done automatically in MVC5 :disappointed:

**Comment by LeonardoDaga** [comment]
Still working on the example. 
In the new version I posted, I added also an Ajax grid in the Authors page.
It works fine, but I saw that if I put a breakpoint in the GridPartial function
`        [HttpGet]
        public ActionResult GridPartial()
        {
            return PartialView("_AjaxGrid", _context.Author.ToList());
        }
`
it seems that the client is still (not always) invoking the server when trying to reorder the columns. You can check it yourself putting a breakpoint in the analogous function in the GridController of your Mvc.Grid.Web project.
Is this the expected behaviour?

**Comment by Muchiachio** [comment]
I actually hit a break point 10/10, what are you doing exactly?

**Comment by Muchiachio** [comment]
Did you find why it's happening?

**Comment by ProfMaxSilva** [comment]
Olá Muchiachio e Leornado parabéns pela atitude pessoal, revolveu meu problema tb.
