### ISSUE TITLE
Ajax Grid using RenderPartialViewToString by Ajax call in MVC6

### ISSUE THREAD

**Issue by herin** [NonFactors/MVC6.Grid#61]
Hi,

I am trying to use My Ajax grid in one my partial view. Now I am trying to use that partial view inside another partial view, and I am rendering that partial view by using RenderPartialViewToString. So I am returning Partial view as string in Ajax call, but Its not working as I have putted my Ajax Grid inside that Partial view string.

So, how can I achieve that ?

Thanks.

**Comment by Muchiachio** [comment]
Did you initialize the grid after rendering it?

**Comment by herin** [comment]
Yes, i have initialize the grid, after Partial view gets render on DOM.

**Comment by Muchiachio** [comment]
Hmm, I don't know then. Try debugging the scripts and see why it's not working or create a repro project on github, which I can look at.

**Comment by Muchiachio** [comment]
Did you managed to found an issue?
