### ISSUE TITLE
more control over the appearance of the filter icon

### ISSUE THREAD

**Issue by dkent600** [NonFactors/MVC6.Grid#62]
Hi,

I would like to be able to change the color of the filter icon that appears in the header of a filterable column.  I would also like to be able to change the icon itself. If the icon were implemented as a font character this ability would be easy (like one can do with font-awesome).

As a single font character, would be easy to override the color, or any other attribute via CSS, as well as the icon itself (by specifying a different character, which could be done either via an additional API or via CSS with no change to the API).

**Comment by Muchiachio** [comment]
Yes, this is something I have in my backlog. The current filter is just an image, so if you want to change it you can repaint the current image and override it or use your own styling.

I will be changing it to some pure css solution (like styling a div into an icon). I didn't really want to have a dependency on other fonts just for a single icon.

**Comment by dkent600** [comment]
You may already know this:    You can create your own custom SVG font with a whole set of icons in it and package the font files with the rest of your content.
