### ISSUE TITLE
Ajax Grid Pager doesn't work when in bootstrap table-reponsive

### ISSUE THREAD

**Issue by dotnetshadow** [NonFactors/MVC6.Grid#63]
Hi there,

I wrapped my Grid in a 

`<div class="table-responsive">`

And I noticed the pager stopped working, no click events were being registered. As soon as I took it out of the responsive div everything worked.

Also are there any client events to indicate when the mvcgrid has loaded, or when the ajax has loaded?

**Comment by Muchiachio** [comment]
Make sure you are wrapping your grid outside of the partial view, as in
```HTML
<div class="table-responsive">
    @Html.AjaxGrid(Url.Action("IndexGrid"))
</div>
```

**Comment by dotnetshadow** [comment]
@Muchiachio ahh thank you I'll give that a try I was including it in my partial view
