### ISSUE TITLE
how to group column headers

### ISSUE THREAD

**Issue by sai30** [NonFactors/MVC6.Grid#64]
Hi,

I am new to asp.net. I started using this grid and loved it.

Is there a way to group column headers? i want to club three columns A, B and C with group name as X like this
[New Microsoft Office Excel Worksheet.xlsx](https://github.com/NonFactors/MVC6.Grid/files/958231/New.Microsoft.Office.Excel.Worksheet.xlsx)

**Comment by Muchiachio** [comment]
There is currently no way to do it from the given grid API.
However you can do that by using your own grid partial.
