### ISSUE TITLE
Controller action function does not get the global search parameter

### ISSUE THREAD

**Issue by mirind4** [NonFactors/MVC6.Grid#65]
Hey all!

I hope it is the right place to post my issue. First of all, thanks in advance your help! I have been struggling for days to solve an issue, but could no figure out what the problem is. My issue is the following:
I would like to set up a global search functionality using this tutorial example: http://mvc6-grid.azurewebsites.net/Grid/GlobalSearch 

My controller is:
```c#
        [HttpGet]
        public IActionResult ContainersGrid(String search)
        {
            return PartialView("_ContainersGrid", new InMemoryContainerData().GetOne(Convert.ToInt32(search)));
        }
```

My main view is:
```c#
<input class="grid-search" />

@Html.AjaxGrid(Url.Action("ContainersGrid"))


<script type="text/javascript">
    $(document).on('keyup', '.grid-search', function() {
        $('.mvc-grid').mvcgrid({
            query: 'search=' + this.value,
            reload: true
        });
    });
</script>

```
And last but not least my partial view is the following:

```c#
@model IEnumerable<MokaKukaMap.Data.Container>

@(Html
    .Grid(Model)
    .Build(columns =>
    {
        columns.Add(model => model.Id).Titled("Id");
        columns.Add(model => model.LinkedCustomer.Address).Titled("Customer Addres");
    })
    .Sortable()
)
```

Well If I write something in the search box, the "ContainersGrid" controller functions is invoked, which is a good point. But unfortunately the value what I write in the search box is not passed to this function so search string in my ContainersGrid method is always null. The other parts of code works properly. If I check it with developer tools of chrome I see the following information of GET:
```
Request URL:http://localhost:13078/Home/ContainersGrid?
Request Method:GET
Status Code:200 OK
Remote Address:[::1]:13078
Referrer Policy:no-referrer-when-downgrade
```
So it seems that the request URL also does not have the search parameter. Here I am stuck :/ Would you be so kind as to help me in this issue? Thanks a lot, I appreciate your help!

**Comment by Muchiachio** [comment]
Everything seems ok, you could just debug `.mvcgrid(...)` line in the browser and you should be able to find the root cause pretty quickly. And btw, that `contentType` parameter get's ignored, so you can remove that.

**Comment by mirind4** [comment]
Waoo, thanks for your super quick reply! ;)
Inside .mvcgrid(...), the "this.value" equals to my search parameter, so it seems ok. What do you think, should I go deeper in the code and check the functions inside mvc-grid.js?

**Comment by mirind4** [comment]
I think i figured out something! To be honest it is my first time debugging javascript code like that...What I have figured out is:
```javascript
1. $.fn.mvcgrid = function (options) {
2.    return this.each(function () {
3.        if (!$.data(this, 'mvc-grid')) {
4.            $.data(this, 'mvc-grid', new MvcGrid($(this), options));
5.        } else if (options) {
6.            $.data(this, 'mvc-grid').set($.data(this, 'mvc-grid'), options);
7.        }
    });
};
```

At the first line of this code, the options object holds my search parameter. but at the 4th line, options does not contain my search parameter anymore :O mhh, very interesting. What do you think? Thanks in advance!

**Comment by mirind4** [comment]
Of course I can! Here it is: https://github.com/mirind4/ContainersMap/tree/master/MokaKukaMap
The directory structure of the relevant files:
-MokaKukaMap/Controllers/HomeController.cs
-MokaKukaMap/Views/Home/Containers.cshtml
-MokaKukaMap/Views/Shared/ _ContainersGrid.cshtml

Thanks a lot, I really appreciate your help, so kind of you  👍

**Comment by Muchiachio** [comment]
You are using old grid `0.9.0`, updating to the newest version should fix your problems.
Because your version is missing [this patch](https://github.com/NonFactors/MVC6.Grid/commit/7013c54387bf3ed047ad9e68d286d66ce844e20f).

**Comment by mirind4** [comment]
It works like charm! Thank you very much, I am so happy! :)
There is a small issue, it still does not work in debug mode of visual studio, since if i run the webapp in debug mode, the old mvc-grid.js is used, and i dont know why. But I think it is not related to this issue-ticket, so i investigate further about this. Thanks again, I wish u a following nice week! ;)

**Comment by mirind4** [comment]
I just solved it! I close this issue then, cheers my friend! :)
