### ISSUE TITLE
Page reloading when sorting/filtering or interacting with grid.

### ISSUE THREAD

**Issue by DazEdword** [NonFactors/MVC6.Grid#66]
Hi,

I am using MVC6.Grid for [AKClipper](https://github.com/DazEdword/AKClipper), a pet project to parse Kindle clippings. I was able to install and show Grid easily as a wrapped ViewComponent, but things ar getting rough when it comes to interacting with the grid rather than rendering it. I set up my grid view in Results.cshtml like this:

```HTML
<!DOCTYPE html>
<html>
<head>
    <environment names="Development">
    </environment>

    <environment names="Staging, Production">
    </environment>
</head>

<body>
    <div id="akc-component">
        @{
             var expandoDict = (IDictionary<string, object>)Model;
             var model = (ParserWebHelper)expandoDict["model"];
             var clippingData = model.parserClientContent.clippingData;
        }

        @(Html
            .Grid(clippingData)
            .Build(columns => {
                columns.Add(item => item.Author).Titled("Author");
                columns.Add(item => item.BookName).Titled("Book Name");
                columns.Add(item => item.ClippingType).Titled("ClippingType");
                columns.Add(item => item.DateAdded).Titled("Date Added");
                columns.Add(item => item.Location).Titled("Location");
                columns.Add(item => item.Text).Titled("Text");
            })
        .Filterable()
        .Sortable()
        .Pageable()  
        )   
    </div>
</body>
</html>
```

That is rendered in my Index view as a ViewComponent if the parse succeeds; otherwise, the Main view is inserted instead, so that the user can try again. The model is passed on to the ViewComponent like this:

return View("~/Views/Shared/Components/Clipper/Results.cshtml", new { model = Helper }.ToExpando());

The Grid is initialised in a helper js file, after returning the ViewComponent from an AJAX call:

```JS
$.ajax({
    url: 'http://localhost:60362/home/parse',
    data: {
            content: content,
            language: language
        },
        type: "post",
        success: function (response) {
            stop_loading();
            var component = document.getElementById('akc-container').innerHTML = response;
            $('.mvc-grid').mvcgrid();  
        },
        error: function (dataerror) {
            stop_loading();
            alert("Failed to parse. Please refresh your browser and try again.");
        }
    });
```
As you can see, everything looks alright. Mouse hover on the pagination buttons work, filtering sub-menu, etc.

![chrome_2017-04-30_16-31-43](https://cloud.githubusercontent.com/assets/10813745/25565629/8c6092de-2dc2-11e7-9341-7a96a9197263.png)

I expected sorting to work automatically after instantiating the ViewComponent, but instead I get redirected to Index when I attempt to. Would you please let me know if this is a known issue, or if I am missing something? If you need more code than the one exposed here feel free to take a look into the repo, linked at the beginning of the message :). Thanks in advance!

**Comment by Muchiachio** [comment]
Sorry, I couldn't run your project, because I no longer have sdk supporting `project.json` format.
Does it redirect with grid query parameters or just to an empty index `/`?
Maybe you need an ajax grid so it doesn't refresh the page.

**Comment by DazEdword** [comment]
It redirects to an empty index indeed, but even it I knew how to handle the grid query parameters (honestly, at this moment I don't know) I also do think that an Ajax Grid is better in this case; my emphasis was on bringing as much work as possible to the client side, so that certainly seems to be the option. I've seen [your example here](http://mvc6-grid.azurewebsites.net/Grid/Ajax?mainParam=mainValue), but if you don't mind me asking: any pitfall to avoid or special consideration to take when using AjaxGrid vs Grid? Thanks for your prompt reply by the way!

**Comment by Muchiachio** [comment]
Ajax and simple grid have the same functionality, so use whichever is more suited to your needs.
I'm not sure why it redirects to an empty index. It should add sort parameters automatically.
You could try debugging the `click` event and see what's missing.

**Comment by DazEdword** [comment]
I think I found the problem. As I said, Index returns a view that has a ViewComponent that chooses between Results view (now grid) and Main view. A "results" bool flag marks whether the Results are going to be shown or not, and the grid is not sending that query string. Look what happens if I manually add the query string (http://localhost:60362/?Grid-Sort=Author&Grid-Order=Asc&results=true)

![chrome_2017-04-30_19-10-54](https://cloud.githubusercontent.com/assets/10813745/25566789/c3f4b5a2-2dd8-11e7-91d9-e0fa9eb00617.png)

Working! I certainly don't know how to fix this, but at least we know what's happening.

**Comment by Muchiachio** [comment]
Well, debugging js should tell you why it's empty.

**Comment by Muchiachio** [comment]
Did you found why it's not working?

**Comment by DazEdword** [comment]
Sadly not yet, but will take a look at it again this week.

**Comment by DazEdword** [comment]
So after a few more hours of debugging, I'd say JS is behaving as expected (and thus, the request to the server is coming accompanied by a proper query string), but something is failing on the server side when it comes to its processing :/. Wish I had a bit more of experience with ASP.NET, this is getting frustrating.

**Comment by Muchiachio** [comment]
Maybe you forgot to register mvc grid services?

**Comment by DazEdword** [comment]
Good point, but double checked it is not the case:

https://github.com/DazEdword/AKClipper/blob/master/AKCWebCore/Startup.cs

**Comment by Muchiachio** [comment]
Well your `http://localhost:60362/parse` link doesn't open the results if you refresh that page again.
So grid is not even shown.

**Comment by DazEdword** [comment]
I've been rewriting the parse method and ViewComponent logic recently, and it's in a very unstable state as you could see. Will be working on that this weekend (+ expanding test coverage), hope to have more details soon. Thanks!

**Comment by DazEdword** [comment]
You were totally right, once the URL routing was stable on my end, the grid sorting started to work automatically; two comments for anyone having similar errors:

- I was activating the grid from AJAX sucess function. That works, but caused lots of unnecessary trouble here. Instead, activate on the view in which the grid is going to be used:

`<script>
            $('.mvc-grid').mvcgrid();
    </script>`

Thank you for your lovely piece of software and help, on my end this issue can be considered resolved.
