### ISSUE TITLE
Use different source than Model

### ISSUE THREAD

**Issue by codenamelxl** [NonFactors/MVC6.Grid#67]
Hi, nice project. I've been heavily use this in my project. However, i can't find anywhere in the doc the way to build a grid from an IEnumerable that i queried and put into ViewBag. Is it event possible?
Thanks in advance.
Edit: Something like this
`@(Html.Grid(ViewBag.MyItemList).....)`

**Comment by Muchiachio** [comment]
Just cast it back to an enumerable, before passing it to the grid.

**Comment by codenamelxl** [comment]
Yes, i tried to used (List<Type>)ViewBag.MyItemList and it let me do that, but then i don't know what to used to replace the "model" in columns builder. I could have checked the source but i don't really familiar with C#. So please bare with me. Thanks!

**Comment by Muchiachio** [comment]
`List` is non-generic construct, you probably created that list somewhere inside the controller, so you can copy a generic version of that here `(List<MyModel>)ViewBag.MyItemList` or use a `.Cast<MyModel>` on `List`.

**Comment by codenamelxl** [comment]
Oops, my bad. What i tried to use is exactly what you just  replied `Grid((List<MyModel>)ViewBag.MyItemList)`.
Then i don't know what to put in columns Add() instead of  `model`. I guess i have to do something to type cast it in the view too ?
```
.Build(columns =>
    {
        columns.Add(model => model.Name).Titled("Name");
```

**Comment by Muchiachio** [comment]
You mean you don't know what properties are used inside your model?

**Comment by codenamelxl** [comment]
It works now. That was my mistake that i wrote this
``@(Html.Grid((List<MyModel>)ViewBag.MyItemList)
        .Build(columns =>
        {
            columns.Add(mm => mm.Name).Titled(Html.DisplayNameFor(mm => mm.Name);
        })
        .Empty("No data")
)``
The Html.DisplayNameFor only work for the `@model` of the view. Thought that i can use that for any Item( Or can i? Still trying to learn, i was not really familiar with ASP.NET and C# as a whole...)
Thank for your very fast response!

**Comment by Muchiachio** [comment]
Yes, it only works for the `@model`, you could check out how the `.DisplayNameFor(...)` get's it's value and make a call to a helper function or use static `resx` classes.

**Comment by codenamelxl** [comment]
Thank you. I believe my question now off-topic. Greatly thank for your help.
