### ISSUE TITLE
Pass parameters when reloading the grid

### ISSUE THREAD

**Issue by TonyWoo** [NonFactors/MVC6.Grid#68]
Hi, I want to allow user to enter some search criteria, and pass these search criteria to the server when user click the search/reload? is this doable? Thanks in advance.

**Comment by Muchiachio** [comment]
Yes, you can reload your grid with given parameters, [here's an example](http://mvc6-grid.azurewebsites.net/Grid/GlobalSearch) on that.

**Comment by TonyWoo** [comment]
Thank you @Muchiachio. So I can pass any number of parameters to the server? I have a mvc action that need to accept a few parameters. Thanks again.

**Comment by Muchiachio** [comment]
Yes, its just a query string for the action.

**Comment by Muchiachio** [comment]
Did you get it working?
