### ISSUE TITLE
Rendering boolean fields as checkboxes

### ISSUE THREAD

**Issue by Fletchemon** [NonFactors/MVC6.Grid#69]
I'm sure there's a way to do this, but things I'm trying isn't working.  Is there a way to render a true/false field as a checkbox in the grid?  I'm trying to use .RenderedAs to get this done but my n00bness gets in the way. =/

**Comment by Fletchemon** [comment]
Scratch this.  I figured it out.  For those reading this years from now, after the collapse of civilization and the rise of the machines, here's the code I used:

`columns.Add(model => model.isDelivered).Encoded(false).RenderedAs(model => Html.CheckBoxFor(a => model.isDelivered)).Titled(@Html.DisplayNameFor(model => model.isDelivered));`

**Comment by paulvanbladel** [comment]
Very nice, but the checkbox is editable, which feels wrong in a grid.

**Comment by Muchiachio** [comment]
Well, `Html.CheckBoxFor` takes html attributes, so you can make them readonly if you need to.
And people usually use check boxes to post data from the grid, so they make them editable.

**Comment by paulvanbladel** [comment]
Cool. Thanks a lot for the prompt reply. 
Only using for one hour this amazing grid, I guess I'll figure out how to make it readonly.
Cheers
