### ISSUE TITLE
Adding buttons to a column?

### ISSUE THREAD

**Issue by primico** [NonFactors/MVC6.Grid#7]
This isn't really an issue, but rather a question. I was playing around with this MVC6 grid and I see how you can use the rowclicked event. However, I was curious if there was a way to add a button or hyperlink to a column, so I can provide a way for each row to have multiple events (details, edit, delete)
Thanks. This grid looks great!!

**Comment by Muchiachio** [comment]
Yes, just put `IHtmlContent` as column value as shown [here](http://mvc6-grid.azurewebsites.net/Column/Encoding). Or use a raw string with encode set to false.

**Comment by primico** [comment]
Thanks, worked great!
