### ISSUE TITLE
Multiselect filter

### ISSUE THREAD

**Issue by sebastiengunther** [NonFactors/MVC6.Grid#71]
Hello,

Is it possible to make a multi select filtering column with a custom filter?
I want to select some values like in Excel, for example I have a list of employee and I want to select some of them with their contract type.

**Comment by sebastiengunther** [comment]
I mean multiselect, not multifiler. I want to select some values like in Excel, for exemple I have a list of employee and I want to select some of them with their contract type.

**Comment by yannicksch** [comment]
Hello, 

I have a need equivalent as this point. I want to make an "Excel like" filter with the ability of filtering with the distinct values in the column.

I've check the sample but none of them sounds to look like what I am looking for.

thx for your help

**Comment by Muchiachio** [comment]
With which part of the implementation are you having trouble with?
