### ISSUE TITLE
Filter button does not respond on click

### ISSUE THREAD

**Issue by mirind4** [NonFactors/MVC6.Grid#72]
Hey buddy!

I am having an issue with filtering, and I could not get it solved. I checked also the stackoverflow [(link)](http://stackoverflow.com/questions/25894890/sorting-filtering-attributes-not-working-in-grid-mvc) for some solution but could not figure it out what cause is. I am using the latest library of MVC6.Grid.

My issue is the following: If I click on the  filter button, nothing happens. I also checked it with code inspector, and the following line is rendered:
```html
<th class="mvc-grid-header filterable" data-filterable="True" data-sortable="">
       <span class="mvc-grid-header-title">Id</span>
             <span class="mvc-grid-filter "></span>
</th>
```

So the filter is rendered.But if I am not mistaken the button should also be rendered here, right?

My model looks like the following, it is an partial view (just like last time):
ContainersMap/MokaKukaMap/Views/Shared/_ContainersGrid.cshtml:

```c#
@model IEnumerable<MokaKukaMap.Domain.Container>


@(Html
    .Grid(Model)
    .Build(columns =>
    {
        columns.Add(model => model.Id).Titled("Id").Filterable(true);
        columns.Add(model => model.Customer.Address).Titled("Customer Addres").Filterable(true);
    })
    .Filterable(true)
)
```

As you can see I have properly set the Filterable() both at the column and grid level. Furthermore I also imported the mvc-grid.cs and the mvc-grid.js file in the _Layout.cshtml. What is your opinion where my problem lies? 
Would you be so kind as to help me in this matter? Thank you very much in advance!
The project can be found at : https://github.com/mirind4/ContainersMap

**Comment by Muchiachio** [comment]
Your page doesn't have `mvc-grid.js` included.

**Comment by mirind4** [comment]
Hey Muchiachio.

First of all, thank you for your fast relpy! Well, it is actually loaded at _Layout.cshtml, at line 80. I had some caching issue, and the only solution I could do is to rename the mvc-grid.js to mvc-gridR.js. On the other hand the searchbox of containers page (via ContainersController.cs) works fine so I suppose that it is well loaded. I am now wondering whether this renaming can cause some issue, for example the .js file is referenced somewhere. What do you think?

**Comment by Muchiachio** [comment]
Well I looked at the page source and the whole script tag was missing.
And developer console is throwing javascript errors.

**Comment by mirind4** [comment]
mhh, you might be right! I just started working, after I finish, I dive into this issue and I keep you updated ;) Untill then, have a nice day! :)

**Comment by mirind4** [comment]
You were right, I have some problem with the imports. I also figured out an interesting issue: If I use the mvc-grid.js version 0.9, the filter works well, but the global search functionality not. On the other hand If I use mvc-grid.js version 2.0, the global search works perfectly, but the filter does not...Of course, I would like to use the version 2.0. I investigate further, please give me some time before we close this issue thread...Thanks! ;)

**Comment by mirind4** [comment]
mhh, still interesting.
I started a new dummy project just playing around with it: https://github.com/mirind4/GridProba
Here I imported the mvc-grid.js 2.0 (at _Layout.cshtml line 75). And the filter button does also not work. I thought that maybe some other .css or .js file could cause this issue (at my big private project (MokaKukaMap)), but at this new project there are no more external files added, only the standard ones and included.
Would you be so kind as to check it for me? In the meantime I am also checking it parallel :)
The grid can be found at "GridProba/GridProba/Views/Home/Index.cshtml"
Thanks a lot, I really appreciate your help ;)

**Comment by Muchiachio** [comment]
Your grid proba project doesn't work, because you are using an old `_Grid.cshtml` partial.

**Comment by mirind4** [comment]
Thanks for your response! I feel that we are getting closer and closer to the solution. :) I replaced the old files, now the latest ones are used.
Now If i try open the wepage, it keeps hanging. I had the feeling that it has something to do with my IIS. But If I remove the whole setting-up of grid table (at Index.cshtml) the webpage works well. Have you ever experienced this kind of behavior? 
I also get the following error: 
"GET http://localhost:8935/ net::ERR_CONNECTION_RESET"

Thanks in advance!

**Comment by Muchiachio** [comment]
It happens because you took `_Grid.cshtml` sources from github which are not yet released and are not supported by the dll you are using from nuget, please follow [installation guidelines](http://mvc6-grid.azurewebsites.net/Home/Installation) as only use nuget provided sources.

**Comment by mirind4** [comment]
Aaa works like charm! I really thank you for your effort, so kind of you! If everyone would be like you, there would be no problems in the world! As for me, it was a nice lesson, and I will always use nuget provide sources instead of some other 'ninja' source...
Thanks again, I wish you a very nice weekend ;)
