### ISSUE TITLE
Freeze panes feature

### ISSUE THREAD

**Issue by VenkateshSrini** [NonFactors/MVC6.Grid#73]
Hi,
I'm asking something like the infrajustics control, where we will be able to freeze at columns. That is if a freeze first 3 columns then the horizontal scrolling will happen from fourth to nth column. Similarly if I freeze the header row or second row then vertical scroll will happen only from next row.

If it is achievable today please let me know ho to do the same

**Comment by Muchiachio** [comment]
Nothing built it, but you can find css based solution on the internet and use those without a problem.
