### ISSUE TITLE
Cell selection and edit

### ISSUE THREAD

**Issue by VenkateshSrini** [NonFactors/MVC6.Grid#74]
Hi, 
How to achieve command buttons in the grid cell. Say each row will have edit and delete button. Clicking on that I should be able to trigger that event?

Thanks and regards

**Comment by Muchiachio** [comment]
Buttons or actions can be rendered using `HtmlHelper` methods, [here's](http://mvc6-grid.azurewebsites.net/Column/Encoding) are few examples.

Triggering something will have to be done by your javascript.

**Comment by Fletchemon** [comment]
Along this same line, how would I display buttons just below the parent row?

**Comment by Muchiachio** [comment]
If I understand this correctly, when you would have to use [your own partial view](http://mvc6-grid.azurewebsites.net/Grid/Partial) to do that @Fletchemon.

**Comment by Fletchemon** [comment]
Hi @Muchiachio ,

Thanks for the quick response!  I was just looking at that... 
`@(Html
                                    .Grid(row.Model.Children)
                                    .Build(columns =>
                                    {
                                        columns.Add(model => model.Name).Titled("Child name");
                                        columns.Add(model => model.Age).Titled("Age");
                                        columns.Add(model => model.Birthday).Titled("Birth date");
                                    })`

In what I want to do, I assume I need to replace the above snippet with columns that render buttons... I'm okay with that, but in your declaration of the grid you make reference to row.Model.Children.  Obviously I don't have this in my model... in fact, I don't think I even need a model reference to draw the buttons.  However, Grid() requires a model for reference... not sure how to code this.

**Comment by Muchiachio** [comment]
How would `display buttons just below the parent row` look visually?

**Comment by Fletchemon** [comment]
Something like this:
![capture](https://cloud.githubusercontent.com/assets/1022062/26645941/d25ead7c-4607-11e7-95cf-613ece5bb61c.PNG)

**Comment by Muchiachio** [comment]
Hmm, rendering it like this could work
`columns.Add(model => model.Id + "<br><button>Accept<button>").Encoded(false);`

**Comment by Fletchemon** [comment]
That works, thanks! :)
