### ISSUE TITLE
Enum properties

### ISSUE THREAD

**Issue by sgilja** [NonFactors/MVC6.Grid#75]
Hi,

Enum property values are not translated, they have Display attribute

**Comment by Muchiachio** [comment]
Yes, because grid renders the value you specify without changing it.
If you use `.Add(model => model.Value)`, it's value will be a simple call to `row.Model.Value`.

**Comment by sgilja** [comment]
Thanks,

I have found solution with, I think, renderas method.

Btw, this is the best bootstrap grid what I have found. If you need someone to contribute, let me know. 
In my next project I will use your grid.

Sent from my Windows 10 phone

**Comment by Muchiachio** [comment]
I'm actually trying to completely remove bootstrap dependency, so it can be used in more environments.
But ye, glad you found a solution.
