### ISSUE TITLE
jQuery datepicker

### ISSUE THREAD

**Issue by Fletchemon** [NonFactors/MVC6.Grid#77]
Howdy,

I'm trying to get the jQuery datepicker to show in a filterable date column, but am unable to.  I read through your past issues and found one where you mention that mvcgrid6 checks for the existence of the datepicker and uses it by default.  I'm wondering if there are steps I need to take to let the grid know about datepicker?  I have it showing up in a non-grid area, but can't get it to show up in the filter popup.  

Any help would be greatly appreciated!

**Comment by Muchiachio** [comment]
Try debugging [this line](https://github.com/NonFactors/MVC6.Grid/blob/3393058db217da5a8bd29fb6e554204f06fbb64f/src/Mvc.Grid/Scripts/MvcGrid/mvc-grid.js#L637) and see what goes wrong.

**Comment by Fletchemon** [comment]
Upon clicking the filter icon, fn.datepicker is undefined.

**Comment by Fletchemon** [comment]
The original creator of this website had it set for global usage, but I neglected to add the css that was required to make it work properly.  It's working now, thank you!
