### ISSUE TITLE
How to get value of a column?

### ISSUE THREAD

**Issue by Fletchemon** [NonFactors/MVC6.Grid#78]
I'm wanting to get a list of rows where a specific column (a rendered checkbox value).  How do I go about doing so?  Specifically, for each row that is checked I want to record that row's ID in an array so that if the same grid data is reloaded I can re-check it if it's in my array.

Thus far I've set up catching [reloadEnded](http://mvc6-grid.azurewebsites.net/Javascript/ReloadEvents) and can see the returned grid, but I'm not seeing how I can access the rows within that grid.

**Comment by Muchiachio** [comment]
You can only get the final html in those events.

As for your scenario, you would have to use your recorded id array to append them to grid's query in `reloadStarted` event and when set them somewhere so they can be accessed in grid rendering functions like `columns.Add(model => /* Check box => ViewBag.Selected.Contains(model.Id) ? "checked" : "" */`.

Or use that id array to add checked values after the grid reloaded with javascript.

**Comment by Fletchemon** [comment]
Ok, thank you!  

I decided to do some Javascript to get/set the values as needed.  It worked well! :)
