### ISSUE TITLE
Rename MVC6.Grid to AspNetCore.Grid

### ISSUE THREAD

**Issue by neman** [NonFactors/MVC6.Grid#79]
What do you think of renaming the project to AspNetCore.Grid since it's more accurate and in line with naming of ASP .NET Core products?

**Comment by Muchiachio** [comment]
I would have renamed if Microsoft announced the name change earlier, but it will be MVC6 for now as I don't want to change package names mid way, I will probably have a chance on changing it on ASP.NET Core 2.0 release.
