### ISSUE TITLE
Azure Website Throws Error When Accessed

### ISSUE THREAD

**Issue by Samuel-Harbord** [NonFactors/MVC6.Grid#8]
I would like to know how this works so I can use it in my project but the Azure website gives the following error whenever I access it: "The specified CGI application encountered an error and the server terminated the process". It has been doing this for at least a few days and I cannot seem to find how to get this plugin working as all I can seem to find is help for MVC5.

**Comment by Muchiachio** [comment]
Yes, I still don't know how to deploy it correctly on azure using RC2 or even if azure supports it?
Redeploying RC1 seems to not work anymore either, your best choice now would be to clone this repo and run it locally.
