### ISSUE TITLE
Cannot read property 'lang' of undefined   -> mvc-grid.js error

### ISSUE THREAD

**Issue by Puky96** [NonFactors/MVC6.Grid#80]
I am trying to make filterable work, but I get this error. I have followed all the instalation steps, and the grid loads, and also Sortable and Pageable works, but I couldn`t make Filterable work.

My project looks like this:
Solution tree:
![mvc-grid-tree](https://user-images.githubusercontent.com/23583779/28813134-a23ca436-76a0-11e7-97da-2f67bd19253d.png)

Preview of the grid:
![ps-grid](https://user-images.githubusercontent.com/23583779/28813141-ae0685c0-76a0-11e7-9221-50c6c9e0af4c.png)

and also some code:
View Page:
`@model IEnumerable<eComplaints.Models.ReportViewModels.InvestigatorListItem>

@(Html
    .Grid(Model)
    .Build(columns =>
    {
        columns.Add(model => model.ReportId).Titled("# Plangere").Sortable(true).Filterable(true);
        columns.Add(model => model.Line).Titled("Linie").Sortable(true);
        columns.Add(model => model.PhenomenaCategory).Titled("Material").Sortable(true);
        columns.Add(model => model.Problem).Titled("Problema").Sortable(true);
    })
    .Sortable()
    .Pageable()
    .Empty("Momentan, nu exista plangeri pentru aprobare!")
    )

@section Scripts {
@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}`

I have also reffereneced in the _Layout.cshtml, mvc-grid.js and mvc-grid.css but it still won`t work, and put in the Startup.cs --> services.AddMvcGrid()

**Comment by Muchiachio** [comment]
Did you include `jquery.js` before `mvc-grid.js`?

**Comment by Puky96** [comment]
Yes, I included jquery.js before mvc-gris.js. i will post immediately a SS with the error from chrome so you can see the lines where it fails

**Comment by Puky96** [comment]
![prev_erori](https://user-images.githubusercontent.com/23583779/28814427-341b622a-76a6-11e7-8505-413d8b4689ac.png)

**Comment by Puky96** [comment]
And also, there iss the code from the _Layout.cshtml that renders the body

`<div class="container body-content">
        @RenderBody()

        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/js/mvc-grid.js"></script>
        <script>
            $('.mvc-grid').mvcgrid();
        </script> </div>`

**Comment by Muchiachio** [comment]
It seems like `$.fn.mvcgrid` is missing, maybe you have overwritten in somewhere?
Because `mvc-grid.js` initializes it, it's strange that it's undefined.

**Comment by Puky96** [comment]
I have not overwritten anything, all I did was copying the files from .nuget/... to my project and then run it. Also, I checked if  `$.fn.mvcgrid` is missing  but it is there, starting at 777 row

**Comment by Muchiachio** [comment]
I don't know then if it's being set at 777th line it should not be `undefined` :frowning_face:

**Comment by Muchiachio** [comment]
Did you managed to find why it's happening or have a repro?

**Comment by Puky96** [comment]
Noy really, i put it on hold for the moment

**Comment by Puky96** [comment]
hi,

I managed to solve that problem. I simply moved the refference to jquery and mvc-grid.js from the Layout to the page I needed. Now, I have another problem. Filterable() is not working, and I get no console error. Can you help me with that?

**Comment by Puky96** [comment]
The problem is next: 
Let`s take the example from you website. 
For example I apply filter to the surname column (Contains "Lisel"). The link should be .../?Surname-Contains=lisel&Rows=4. 

When I use it in my webpage, after filtering the link is next .../?Surname-Contains=&Rows=4. 

So it fails to bring the filtering parameter to the link. If I put it manually it works, so I need some help, I don`t know what to modify in your code.

**Comment by Muchiachio** [comment]
Try debugging `mvc-grid.js` and see where it loses the value, filtering script is on the bottom part of the script.
