### ISSUE TITLE
Cannot bind to row event

### ISSUE THREAD

**Issue by TrentArwine** [NonFactors/MVC6.Grid#82]
I would like to add data-attributes to each row so we could allow the clicking of the row to launch a bootstrap modal. The code below does not work because we try to add the attribute after the row is clicked. Looking through your documentation I cannot see a rowCreated or anything similar which is where I would expect to add these attributes.

`    $('.mvc-grid').mvcgrid({
        rowClicked: function (row, data, e) {
            console.log(data);
            $(row).attr("data-id", data.Id);
            $(row).attr("data-toggle", 'modal');
            $(row).attr("data-target", 'modal-travel-document-edit');
        }
    });

    $('#modal-travel-document-edit').on('shown.bs.modal', function (e) {
        $('.modal-footer').hide();

        var id = $(e.relatedTarget).data('id');
        var $modal = $(this);`

**Comment by Muchiachio** [comment]
There is no support for adding row attributes.
However, you could add hidden columns and use `data` parameter values for your modal dialog.

**Comment by vbisbest** [comment]
@Muchiachio do you have an example of using the hidden column?  Thanks!

**Comment by Muchiachio** [comment]
@vbisbest add a column with a css class which has `display:none` and then use that column name to get data, for example:
```C#
columns.Add(model => model.Id).Css("collapse");
```
```JS
$('.mvc-grid').mvcgrid({
    rowClicked: function (row, data, e) {
        console.log('id: ', row['Id']);
    }
});
```
