### ISSUE TITLE
Dynamic loading dropdown filter

### ISSUE THREAD

**Issue by FBueckert** [NonFactors/MVC6.Grid#87]
I've found a need for a more user friendly filter option, so that there is less risk of a user mistyping what it is they're looking for.  I've managed to write a rather rough dropdown filter that uses Ajax to populate the dropdown as soon as the popup loads.  It works rather well with EF and .net core.  If that's a worthwhile feature, I can submit it for review.

**Comment by Muchiachio** [comment]
Hows does it know what and how to load it? The problem I saw with dropdowns is that they have to introduce a lot of new API and code surface to the code base, which is why I didn't do them.

But yes, would be great if you could share your project if it's public, maybe it's I didn't thought of.

**Comment by FBueckert** [comment]
It's nothing so fancy as a project; I just used your filter as an example.  Here's what I came up with:

```
var MvcGridDropdownFilter = (function () {
    function MvcGridDropdownFilter(name, func) { this.name = name; this.func = func; }
    MvcGridDropdownFilter.prototype = {
        render: function (grid, popup, filter) {
            popup.html(
                '<div class="popup-arrow"></div>' +
                '<div class="popup-content">' +
                '<div class="first-filter popup-group">' +
                'Choose category: ' +
                '<select id="' + this.name + '" class="form-control"></select>' +
                '</div>' +
                '<div class="popup-button-group">' +
                '<button class="btn btn-success mvc-grid-apply" type="button">✔</button>' +
                '<button class="btn btn-danger mvc-grid-cancel" type="button">✘</button>' +
                '</div>' +
                '</div>');

            var x = eval(this.func);
            if (typeof x == 'function') {
                x();
            }
        },

        init: function (grid, column, popup) {
            this.bindApply(grid, column, popup);
            this.bindCancel(grid, column, popup);
        },
        bindApply: function (grid, column, popup) {
            var apply = popup.find('.mvc-grid-apply');
            apply.on('click.mvcgrid', function () {
                popup.removeClass('open');
                column.filter.first.val = popup.find('.first-filter select')[0].value;
                column.filter.first.type = 'Equals';

                grid.applyFilter(column);
                grid.reload();
            });
        },
        bindCancel: function (grid, column, popup) {
            var cancel = popup.find('.mvc-grid-cancel');
            cancel.on('click.mvcgrid', function () {
                popup.removeClass('open');

                if (column.filter.first.type) {
                    grid.cancelFilter(column);
                    grid.reload();
                }
            });
        }
    };;;

    return MvcGridDropdownFilter;
})();
```
The filter is activated with ` 'filter': new MvcGridDropdownFilter('filter', 'populateFilter')`

And the populateCategories function is: 
```

function populateCategories() {
        $.ajax({
            url: '@Url.Action("populateFilter", "modelController")'
        }).done(function (result) {
            $.each(result, function (i, item) {
                $("#filter").append($('<option value="' + item.text + '">' + item.text + '</option>'));
            })
        })
    };
```

I ran into the same issue; how do you know what to populate it with?  For that, take a look at the end of the render event; I pass it a function name, which then runs after the popup finishes showing.  This is probably an extremely insecure way of going about it; passing function names seems like a code smell to me, but it does work.  Could definitely use some polishing, as it currently needs a hardcoded select name, and it doesn't choose selected value after filtering.

**Comment by FBueckert** [comment]
@Muchiachio Hey, just following up on this.  Is this something you'd want to include? I can submit a pull request if you'd like to go through that route.

**Comment by Muchiachio** [comment]
No, not yet. Source url could be saved on the filter, but I still didn't figure out how would generic implementation look like, as we would still have to add events for long/failed requests and so on.
So I'm debating if it's worth adding at all.

**Comment by Muchiachio** [comment]
Finally got time to dig into this and tried implementing and as I was afraid it got over-complicated to a point it was not worth adding. Thank you for a suggestion and a code sample though, it helped me find pain points in current grid design. So I can make incremental changes in the future major released to make these things more accessible.
