### ISSUE TITLE
Phone number formatting

### ISSUE THREAD

**Issue by Fletchemon** [NonFactors/MVC6.Grid#88]
Greetings,

Firstly, got your grid working really well in our app - Thank you for the great work you've done and continue to do, it make our work here much easier!

I am trying to get a phone number column to display in a formatted fashion, but my formatting I've specified seems to be ignored.  

The column I'm trying to format is varchar, but has only numbers in it.  Here's the line I'm using to attempt a proper viewing:

`          columns.Add(model => model.Phone).Formatted("{0:(###) ###-####}");`

The value shows, but the formatting is not.  I was able to verify that the formatting is correct using LinqPad.  I'm curious if you have any suggestions as to what I may be missing?

Alias,
Fletch

**Comment by Muchiachio** [comment]
What's phone's type?
Formatted is using `String.Format("{0}", value)`, if this works it should also work on the grid.

**Comment by Fletchemon** [comment]
Phone's type is string.  I used the same format in LinqPad, and got the expected value using the following statement:

string.Format("{0:(###) ###-####}",5551239988);

The confusing part is that the value shows up (unformatted, of course) in the grid.

**Comment by Muchiachio** [comment]
Yes, but that's `5551239988` not a string, try `"5551239988"` in linq pad and you will get incorrect results also.
So you need to change phone's type to `int` or `long`.

**Comment by Fletchemon** [comment]
Yep, checked that last night before I left work - definitely the issue, thanks!
