### ISSUE TITLE
AjaxGrid in Modal

### ISSUE THREAD

**Issue by Luciano888** [NonFactors/MVC6.Grid#89]
Hi!
I've a problem, i need add a @Html.AjaxGrid(Url.Action("Some", "some")) inside a modal, but in the moment show the view, i can't see the list or nothing. 
In the console of the navigator, i can see 

> "<div class="mvc-grid" data-source-url="/some/some">
> </div>" 

But i can't see anythind about of the grid. You can help a resolve this problem?

**Comment by Luciano888** [comment]
Firts tnx for take a moment for answer. 
Second I render the modal outside of my modal, and yes, you right. 
I see for console, this error (in the page of the modal) 

"Uncaught ReferenceError: gris is not defined"
Code 114:  "gris.sourceUrl = options.sourceUrl;"

You have any idea about this?

PD:

**Comment by Muchiachio** [comment]
How do you initialize the grid?

**Comment by Luciano888** [comment]
@Html.AjaxGrid(Url.Action("IndexGrid", "Calidad"))
It is inside of modal-body, I can initialize and show other grids in the modals, no problems with that.
But in this modal in particular, also the grid, it have a Create, in the modal-body. 
I seeing in the debug of the navigator, "Networks", the IndexGrid for the others grids in the modals, show "Status:200".
But I can see the grid especified, not even brings it

**Comment by Muchiachio** [comment]
[Here's](https://github.com/NonFactors/MVC6.Grid.Web/tree/89) a modal working in documentation's ajax page.
Could you check what are you doing differently?

**Comment by Luciano888** [comment]
Yes! Tnx
I can resolved the problem. The problem was because I showed the PartiaView, this screen lost the JS necessary .
