### ISSUE TITLE
Dependencies conflict

### ISSUE THREAD

**Issue by silentcross** [NonFactors/MVC6.Grid#9]
Currently I'm using ASP.NET 5 RC1 when i use `0.9.5-rc2-final` and it creates type conflicts across different assemblies. If i use `0.9.0-rc1-final` it say `IServiceCollection` does not contain a definition for `AddMvcGrid`.

**Comment by Muchiachio** [comment]
You should not mix RC1 and RC2 versions, because they don't go well together. If you did mix them, you will need to delete package and bin folders and do a complete restore/build. I also suggest migrating from RC1 to RC2 from a clean RC2 solution, by adding needed stuff one by one.
