### ISSUE TITLE
How to get current page of AJAX Grid in JavaScript?

### ISSUE THREAD

**Issue by Giancarlos** [NonFactors/MVC6.Grid#91]
I'm wondering how I can use JavaScript to find out what page the AJAX Grid is currently in?

Somewhat related: what would then be the best way to define the page I want to set the grid to?

Thanks,
Giancarlos

**Comment by Muchiachio** [comment]
`window.location` should be pointing to current page address or is that not enough?

**Comment by Giancarlos** [comment]
I don't think I can get the current page that way from an AJAX grid since it doesn't update the window location for the current grid page.

**Comment by Muchiachio** [comment]
Oh you meant ajax grid's source url:
```JS
var source = $('.mvc-grid').data('mvc-grid').sourceUrl;
var query = $('.mvc-grid').data('mvc-grid').query;
```

**Comment by Giancarlos** [comment]
Thank you, now what if I want to update the page the AJAX Grid is on? Is there a clean way to trigger this?

Thanks again,
Giancarlos

**Comment by Muchiachio** [comment]
Yes, [configuration](http://mvc6-grid.azurewebsites.net/Grid/Configuration) page was showing which parameters to use, keep in mind that as of `v2.1.1` setting `sourceUrl` doesn't work, because of [this issue](https://github.com/NonFactors/MVC5.Grid/pull/106) and will be fixed with `v2.2.2` this weekend.
If you only have to change the query you can do that now.

**Comment by RichJ-BPI** [comment]
The link in the answer above does not work. Is there an updated link please?

**Comment by Muchiachio** [comment]
I updated the url.

**Comment by RichJ-BPI** [comment]
thanks for updating the link. I'm trying to get an ajaxgrid to trigger via JS and take paging data.

Here is some JS from a razor page that calls an ajaxgrid (it's called once the page is loaded):
`    function setUpGrid() {
        var urlParams = new URLSearchParams(window.location.search);
        page = urlParams.get('page');
        rows = urlParams.get('rows');
        var element = document.querySelector('.mvc-grid');
        new MvcGrid(document.querySelector('.mvc-grid'), {
            reloadStarted: function() {
                $('.gridDiv').innerHtml('<div class="loadingDiv" style="margin:auto;"><h5>Grid loading ...</h5></div>');
            },
            reloadEnded: function() {
                $('loadingDiv').remove();
            },
            query: 'page=' + page + '&rows=' + rows
        });
    }`

It doesn't work. What am I doing wrong please?

**Comment by Muchiachio** [comment]
What exactly doesn't work?

**Comment by RichJ-BPI** [comment]
sorry, should have been clearer. The grid reloads, but ignores the paging data.

**Comment by Muchiachio** [comment]
Do you see paging information being passed to the controller in developer tools?
Is grid name empty to use `page` and `rows` parameters?
Is paging enabled on the grid?

If everything above is true, it should work. Otherwise create a small repro project and I can take a look.
