### ISSUE TITLE
Grid Server Paging and Custom pager class

### ISSUE THREAD

**Issue by maspr** [NonFactors/MVC6.Grid#92]
Hi,
I want to implement server paging for large tables. 
Data is retrieved in batches of 10-15 or 20 rows, the query string is parsed so I know my current page, nr of rows per page, sorting etc. 
I have retrieved the total nr of rows and can pass it to the pager.
The problem is that the pager is directly coupled to the data currently retrieved and the TotalRows  property is always overwritten by the nr of items.
A simple fix would be to overwrite TotalRows only if it is 0:
        public virtual IQueryable<T> Process(IQueryable<T> items)
        {
            ...
            if (TotalRows == 0)
                  TotalRows = items.Count();
            ...

But I don't want to mess with the code :)

Or I could just replace the pager with a custom one that does that.  So, How do I use an alternative pager class?

**Comment by Muchiachio** [comment]
You can you `pager.ProcessorType = GridProcessorType.Manual;` and do a [manual paging](http://mvc6-grid.azurewebsites.net/Grid/ManualPaging).

**Comment by maspr** [comment]
That works great! 
Ofcource I had to implement my own filtering but it was fun :)
Thanks.
