### ISSUE TITLE
Cannot filter or sort anymore when replaced the partial view in Ajax call

### ISSUE THREAD

**Issue by xigolle** [NonFactors/MVC6.Grid#94]
I am doing filtering through some selection boxes and refreshing works perfect with the new data.
I does this replacement with: 
```
$.ajax({
                    url: "@Url.Action("OverviewImporterProducerReports","Admin")",
                    type: "POST",
                    data: $("form").serialize(),
                    success: function(result) {
                        $("#partial").html(result);
                    }
                });
```
Where the grid is then rendered inside the #partial div. 
But after this filtering the default sort and filter options on the grid don't work anymore.
Am I doing something wrong or am I missing something?

**Comment by Muchiachio** [comment]
You are most likely missing grid re-initialization part with `$('.mvc-grid').mvcgrid()`.

**Comment by xigolle** [comment]
Omg that works really great :) But now when I true to sort/filter it takes the normal data. 
I understand that is the normal way the grid works, but is there a way to only sort on the newly returned grid?

**Comment by xigolle** [comment]
Fixed it! Thanks very much for your help :)
