### ISSUE TITLE
how to add rows select dropdownlist for mvc gridview

### ISSUE THREAD

**Issue by tommyjiajia** [NonFactors/MVC6.Grid#95]
Hi:
    for now, i want to add a "select page rows" dropdownlist near by "pager button" list? Does mvc grid view  support this? can anyone give me some idea about this?

![results](https://user-images.githubusercontent.com/28645280/33247163-f34e8f16-d356-11e7-848b-be53eb0c9117.png)
Best Regards
Tommy

**Comment by Muchiachio** [comment]
Yes, you can see an example [here](http://mvc6-grid.azurewebsites.net/Pager/SelectableRowsPerPage).
