### ISSUE TITLE
Question: Is it possible for the date filter to ignore time of day when filtering?

### ISSUE THREAD

**Issue by rwatjen** [NonFactors/MVC6.Grid#97]
I'm using MVC6Grid - and it is great.

One of the columns is a datetime2 in SQL. DateTime in .NET. The DateFilter in the grid works fine for it.

I would like to use the DateFilter to filter on dates only, so the data values' time of day should be ignored.

It seems when I filter on "date equals 2017-11-30" it will only take those values which are exactly at midnight. Is it possible to change the filters comparison so it only looks at the date?

**Comment by Muchiachio** [comment]
Simplest way would be to return your date time column with a `<DateTime property>.Date` through selected or mapper, don't know if you are using anything.

If you still want to show time but filter by date, you can used `.Add` and `.RenderedAs` combination to add truncated date as value, but render actual date value.
```C#
.Add(model => model.TruncatedDate).RenderedAs(model => model.FullDate)
```

**Comment by rwatjen** [comment]
Thank you, that was pretty much exactly what I was looking for. As per your suggestion, I added an unmapped property to the entity class, that gets the Date part of the DateTime:

    [NotMapped]
    public DateTime? DownloadDate => DownloadDateTime?.Date;

And then used the `columns.Add` method as you suggested with `RenderedAs` for displaying the full date and time.
