### ISSUE TITLE
Ajax Grid render.

### ISSUE THREAD

**Issue by tellur21** [NonFactors/MVC6.Grid#98]
Hi, 
I have menu in my MainPage like this
` <ul class="dropdown-menu forAnimate" role="menu">
                                    <li>     
                                        @Ajax.ActionLink("Services", "Services", "PrivateCabinet", new AjaxOptions { UpdateTargetId = "main" })
                                    </li>
                                    <li>
                                        @Ajax.ActionLink("Service categories", "ServiceCategories", "PrivateCabinet", new AjaxOptions { UpdateTargetId = "main" })`

and div what I updateting
`<div id="main" class="col-md-10"/>`

Than I would like to show some partialViews on click ActionLink in main div. I place in those partialView MvcGrid.

`@model IEnumerable<Service>
@(Html    
    .Grid(Model)
    .Build(columns =>
    {
        columns.Add(model => model.ServiceCategory.Name).Titled("Service category");
        columns.Add(model => model.Description).Titled("Description");
        columns.Add(model => model.SortOrder).Titled("Sort order");
    })
    .Filterable()
    .Sortable()
    .Pageable(pager =>
    {        
        pager.RowsPerPage = 14;
    })
    .Css("table-hover")
)`

But need to change it as AjaxGrid because of paging not working on this what I have now.  

I don't know how to use `@Html.AjaxGrid(Url.Action("Services"))`

Please help me.

Thank you.

**Comment by Muchiachio** [comment]
Does it not work at all or after loading your content? Could you share a small repro?

**Comment by tellur21** [comment]
Hi here is som repro solution. Go to About View.. There is some comments.
[TestGrid (2).zip](https://github.com/NonFactors/MVC6.Grid/files/1562630/TestGrid.2.zip)

Thank you.

**Comment by Muchiachio** [comment]
There are a few possibilities here, on click you could:
- Load a new partial with ajax grid included in that partial view (don't forget to intialize the grid after load).
- Render the grid in hidden container and just unhide it.
