### ISSUE TITLE
Pull requesting

### ISSUE THREAD

**Issue by DanielMaestro** [NonFactors/MVC6.Grid#99]
Hello There!

Great work you are doing here. I would like to contribuite in this project, I think I could add some feaures, the first thing to come to my mind is adding Dynamic Fields enhacement.

Thanks in advance and Sorry for bad english.

**Comment by Muchiachio** [comment]
As per `contribution.md`, you should first create an issue with your proposed features and if you have ideas on how to implement it you can share the API and your thought on how it can be implemented on the same issue too.
